In [26]:
# Query 1 : Results
s='{"schema": {"round": "int64", "round 1": "object", "circuit": "object", "day": "object", "pole position": "object", "fastest lap": "object", "driver": "object"},"categories":["motorsport", "car", "seasons"]}'
s=s.lower()
s=json.loads(s)
input_schema=s['schema'];input_categories=-1;transformations=-1;stats=-1
if "categories" in s:
    input_categories=s["categories"]
if "transformations" in s:
    transformations=s["transformations"]
if "stats" in s:
    stats=s["stats"]
# display query
print("Input Schema : ",input_schema)
if input_categories==-1:
    print("Input Categories : None")
else:
    print("Input Categories : ",input_categories)
if transformations==-1:
    print("Input Transformations : None")
else:
    print("Input Transformations : ",transformations)
if stats==-1:
    print("Input Condition based conditions : None")
else:
    print("Input Content based Conditions : ",stats)
print()
comp_score={}
no_of_rows={}
no_of_rows={}
check_possible_category_included_matches()
ranking_display(comp_score,no_of_rows)

Input Schema :  {'round': 'int64', 'round 1': 'object', 'circuit': 'object', 'day': 'object', 'pole position': 'object', 'fastest lap': 'object', 'driver': 'object'}
Input Categories :  ['motorsport', 'car', 'seasons']
Input Transformations : None
Input Condition based conditions : None

Matching Tables
203_181.csv  :  1990 IndyCar season
203_514.csv  :  2008 Superleague Formula season
203_742.csv  :  1995 IndyCar season
204_253.csv  :  1990 Superbike World Championship season
204_569.csv  :  1998 Swedish Touring Car Championship season
204_63.csv  :  2002 Italian Formula Three season


203_181.csv(1990 IndyCar season)
Missing Values(NANs score):  {'date': '0/17', 'rnd': '0/17', 'race name': '0/17', 'circuit': '0/17', 'city/location': '0/17', 'pole position': '0/17', 'winning driver': '0/17', 'winning team': '0/17', 'report': '0/17'}
Columns that match with input_schema:
 203_181.csv :  {'circuit': 'circuit', 'pole position': 'pole position', 'date': 'day', 'winning driver': 'driver'}
Coverage Score :  0.5714285714285714 	 Completeness Score :  0.5714285714285714

203_514.csv(2008 Superleague Formula season)
Missing Values(NANs score):  {'round': '0/12', 'round 1': '0/12', 'race': '0/12', 'date': '0/12', 'pole position': '6/12', 'fastest lap': '0/12', 'winning club': '0/12', 'winning team': '0/12', 'report': '0/12'}
Columns that match with input_schema:
 203_514.csv :  {'round': 'round', 'round 1': 'round 1', 'pole position': 'pole position', 'fastest lap': 'fastest lap', 'date': 'day'}
Coverage Score :  0.7142857142857143 	 Completeness Score :  0.6428571428571429

203_742.csv(1995 IndyCar season)
Missing Values(NANs score):  {'rnd': '0/17', 'date': '0/17', 'race name': '0/17', 'circuit': '0/17', 'city/location': '0/17', 'pole position': '0/17', 'fastest lap': '0/17', 'winning driver': '0/17', 'winning team': '0/17', 'report': '0/17'}
Columns that match with input_schema:
 203_742.csv :  {'circuit': 'circuit', 'pole position': 'pole position', 'fastest lap': 'fastest lap', 'date': 'day', 'winning driver': 'driver'}
Coverage Score :  0.7142857142857143 	 Completeness Score :  0.7142857142857143

204_253.csv(1990 Superbike World Championship season)
Missing Values(NANs score):  {'round': '0/26', 'round 1': '0/26', 'circuit': '0/26', 'date': '0/26', 'pole position': '0/26', 'fastest lap': '0/26', 'winning rider': '0/26'}
Columns that match with input_schema:
 204_253.csv :  {'round': 'round', 'round 1': 'round 1', 'circuit': 'circuit', 'pole position': 'pole position', 'fastest lap': 'fastest lap', 'date': 'day'}
Coverage Score :  0.8571428571428571 	 Completeness Score :  0.8571428571428571

204_569.csv(1998 Swedish Touring Car Championship season)
Missing Values(NANs score):  {'round': '0/12', 'round 1': '0/12', 'circuit': '0/12', 'date': '0/12', 'pole position': '6/12', 'fastest lap': '0/12', 'winning driver': '0/12', 'winning team': '0/12', 'winning privateer': '0/12'}
Columns that match with input_schema:
 204_569.csv :  {'round': 'round', 'round 1': 'round 1', 'circuit': 'circuit', 'pole position': 'pole position', 'fastest lap': 'fastest lap', 'date': 'day', 'winning driver': 'driver'}
Coverage Score :  1.0 	 Completeness Score :  0.9285714285714286

204_63.csv(2002 Italian Formula Three season)
Missing Values(NANs score):  {'round': '0/9', 'circuit': '0/9', 'date': '0/9', 'pole position': '0/9', 'winning driver': '0/9', 'winning team': '0/9', 'trophy winner': '0/9'}
Columns that match with input_schema:
 204_63.csv :  {'round': 'round', 'circuit': 'circuit', 'pole position': 'pole position', 'date': 'day', 'winning driver': 'driver'}
Coverage Score :  0.7142857142857143 	 Completeness Score :  0.7142857142857143


Rank  1   :  204_569.csv          completeness score : 0.9285714285714286 		number of rows:  12
Rank  2   :  204_253.csv          completeness score : 0.8571428571428571 		number of rows:  26
Rank  3   :  203_742.csv          completeness score : 0.7142857142857143 		number of rows:  17
Rank  4   :  204_63.csv           completeness score : 0.7142857142857143 		number of rows:  9
Rank  5   :  203_514.csv          completeness score : 0.6428571428571429 		number of rows:  12
Rank  6   :  203_181.csv          completeness score : 0.5714285714285714 		number of rows:  17

Ranking Complete!!

In [52]:
# Query 2 : Results
s='{"schema": {"nationality": "object", "tonnage (grt)": "int64", "fate": "object","ship":"object"}}'
s=s.lower()
s=json.loads(s)
input_schema=s["schema"];input_categories=-1;transformations=-1;stats=-1
if "categories" in s:
    input_categories=s["categories"]
if "transformations" in s:
    transformations=s["transformations"]
if "stats" in s:
    stats=s["stats"]
# display query
print("Input Schema : ",input_schema)
if input_categories==-1:
    print("Input Categories : None")
else:
    print("Input Categories : ",input_categories)
if transformations==-1:
    print("Input Transformations : None")
else:
    print("Input Transformations : ",transformations)
if stats==-1:
    print("Input Condition based conditions : None")
else:
    print("Input Content based Conditions : ",stats)
print()
get_matches(kg=1)

Input Schema :  {'nationality': 'object', 'tonnage (grt)': 'int64', 'fate': 'object', 'ship': 'object'}
Input Categories : None
Input Transformations : None
Input Condition based conditions : None

only schema
Matching Tables
202_117.csv  :  German submarine U-559
203_148.csv  :  German submarine U-9 (1935)
203_268.csv  :  German submarine U-502
204_100.csv  :  Hans-Rudolf Rosing


202_117.csv(German submarine U-559)
Missing Values(NANs score):  {'date': '0/6', 'ship': '0/6', 'nationality': '0/6', 'tonnage': '0/6', 'fate': '0/6'}
Columns that match with input_schema:
 202_117.csv :  {'ship': 'ship', 'nationality': 'nationality', 'fate': 'fate', 'tonnage': 'tonnage (grt)'}
Coverage Score :  1.0 	 Completeness Score :  1.0

,date,ship,nationality,tonnage (grt),fate
0,19 August 1941,SS Aguila,United Kingdom,3255,Sunk
1,27 November 1941,HMAS Parramatta,Royal Australian Navy,1060,Sunk
2,23 December 1941,SS Shuntien,United Kingdom,3059,Sunk
3,26 December 1941,SS Warszawa,Poland,2487,Sunk
4,10 June 1942,MV Athene,Norway,4681,Sunk
5,10 June 1942,SS Brambleleaf,United Kingdom,5917,Damaged

203_148.csv(German submarine U-9 (1935))
Missing Values(NANs score):  {'date': '0/9', 'name': '0/9', 'nationality': '0/9', 'tonnage (grt)': '0/9', 'fate': '0/9'}
Columns that match with input_schema:
 203_148.csv :  {'nationality': 'nationality', 'tonnage (grt)': 'tonnage (grt)', 'fate': 'fate'}
Coverage Score :  0.75 	 Completeness Score :  0.75

,date,name,nationality,tonnage (grt),fate
0,18 January 1940,Flandria,Sweden,1179,Sunk
1,19 January 1940,Patria,Sweden,1188,Sunk
2,11 February 1940,Linda,Estonia,1213,Sunk
3,4 May 1940,San Tiburcio,United Kingdom,5995,Sunk (mine)
4,9 May 1940,Doris,French Navy,552,Sunk
5,11 May 1940,Tringa,United Kingdom,1930,Sunk
6,11 May 1940,Viiu,Estonia,1908,Sunk
7,23 May 1940,Sigurd Faulbaum,Belgium,3256,Sunk
8,11 May 1944,Shtorm,Soviet Union,412,Damaged

203_268.csv(German submarine U-502)
Missing Values(NANs score):  {'date': '0/16', 'name': '0/16', 'nationality': '0/16', 'tonnage (grt)': '0/16', 'fate': '0/16'}
Columns that match with input_schema:
 203_268.csv :  {'nationality': 'nationality', 'tonnage (grt)': 'tonnage (grt)', 'fate': 'fate'}
Coverage Score :  0.75 	 Completeness Score :  0.75

,date,name,nationality,tonnage (grt),fate
0,7 October 1941,Svend Foyn,United Kingdom,14795,Damaged
1,16 February 1942,Monagas,Venezuela,2650,Sunk
2,16 February 1942,San Nicholas,United Kingdom,2391,Sunk
3,16 February 1942,Tia Juana,United Kingdom,2395,Sunk
4,22 February 1942,J.N.Pew,United States,9033,Sunk
5,23 February 1942,Sun,United States,9002,Damaged
6,23 February 1942,Thalia,Panama,8329,Sunk
7,11 May 1942,Cape of Good Hope,United Kingdom,4963,Sunk
8,24 May 1942,Gonçalves Dias,Brazil,4996,Sunk
9,28 May 1942,Alcoa Pilgrim,United States,6759,Sunk
10,3 June 1942,M.F. Ellliot,United States,6940,Sunk
11,9 June 1942,Bruxelles,Belgium,5085,Sunk
12,9 June 1942,Franklin K. Lane,United States,6589,Sunk
13,15 June 1942,Cold Harbor,Panama,5010,Sunk
14,15 June 1942,Scottsburg,United States,8010,Sunk
15,15 June 1942,West Hardaway,United States,5702,Sunk

204_100.csv(Hans-Rudolf Rosing)
Missing Values(NANs score):  {'date': '0/13', 'name of ship': '0/13', 'nationality': '0/13', 'tonnage': '0/13', 'fate': '0/13'}
Columns that match with input_schema:
 204_100.csv :  {'nationality': 'nationality', 'fate': 'fate', 'tonnage': 'tonnage (grt)', 'name of ship': 'ship'}
Coverage Score :  1.0 	 Completeness Score :  1.0

,date,ship,nationality,tonnage (grt),fate
0,5 June 1940,SS Stancor,United Kingdom,798,Sunk at 58°48′N 08°45′W﻿ / ﻿58.800°N 8.750°W
1,7 June 1940,SS Frances Massey,United Kingdom,4212,Sunk at 55°33′N 08°26′W﻿ / ﻿55.550°N 8.433°W
2,7 June 1940,SS Eros,United Kingdom,5888,Damaged at 55°33′N 08°26′W﻿ / ﻿55.550°N 8.433°W
3,11 June 1940,SS Violando N Goulandris,Greece,2375,Sunk at 44°04′N 12°30′W﻿ / ﻿44.067°N 12.500°W
4,19 June 1940,MV Tudor,Norway,6607,Sunk at 45°10′N 11°50′W﻿ / ﻿45.167°N 11.833°W
5,19 June 1940,SS Baron Loudoun,United Kingdom,3164,Sunk at 45°00′N 11°21′W﻿ / ﻿45.000°N 11.350°W
6,19 June 1940,SS British Monarch,United Kingdom,5661,Sunk at 45°00′N 11°21′W﻿ / ﻿45.000°N 11.350°W
7,20 June 1940,MV Moerdrecht,Netherlands,7493,Sunk at 43°34′N 14°20′W﻿ / ﻿43.567°N 14.333°W
8,16 August 1940,SS Hedrun,Sweden,2325,Sunk at 57°10′N 16°37′W﻿ / ﻿57.167°N 16.617°W
9,19 August 1940,SS Ville de Gand,Belgium,7590,Sunk at 55°28′N 15°10′W﻿ / ﻿55.467°N 15.167°W
10,24 August 1940,SS La Brea,United Kingdom,6666,Sunk at 57°24′N 11°21′W﻿ / ﻿57.400°N 11.350°W
11,25 August 1940,SS Empire Merlin,United Kingdom,5763,Sunk at 58°30′N 10°15′W﻿ / ﻿58.500°N 10.250°W
12,25 August 1940,MV Athelcrest,United Kingdom,6825,Sunk at 58°24′N 11°25′W﻿ / ﻿58.400°N 11.417°W

1
1.csv : 202_117.csv		203_148.csv		203_268.csv
Missing Values(NANs):  {'date': '0/31', 'ship': '0/31', 'nationality': '0/31', 'tonnage (grt)': '0/31', 'fate': '0/31'}
Columns that match with input_schema:
202_117.csv :  {'ship': 'ship', 'nationality': 'nationality', 'fate': 'fate', 'tonnage': 'tonnage (grt)'}
203_148.csv :  {'nationality': 'nationality', 'tonnage (grt)': 'tonnage (grt)', 'fate': 'fate'}
203_268.csv :  {'nationality': 'nationality', 'tonnage (grt)': 'tonnage (grt)', 'fate': 'fate'}
Coverage Score :  1.0 	 Completeness Score :  1.0

,date,ship,nationality,tonnage (grt),fate
0,19 August 1941,SS Aguila,United Kingdom,3255,Sunk
1,27 November 1941,HMAS Parramatta,Royal Australian Navy,1060,Sunk
2,23 December 1941,SS Shuntien,United Kingdom,3059,Sunk
3,26 December 1941,SS Warszawa,Poland,2487,Sunk
4,10 June 1942,MV Athene,Norway,4681,Sunk
5,10 June 1942,SS Brambleleaf,United Kingdom,5917,Damaged
6,18 January 1940,Flandria,Sweden,1179,Sunk
7,19 January 1940,Patria,Sweden,1188,Sunk
8,11 February 1940,Linda,Estonia,1213,Sunk
9,4 May 1940,San Tiburcio,United Kingdom,5995,Sunk (mine)
10,9 May 1940,Doris,French Navy,552,Sunk
11,11 May 1940,Tringa,United Kingdom,1930,Sunk
12,11 May 1940,Viiu,Estonia,1908,Sunk
13,23 May 1940,Sigurd Faulbaum,Belgium,3256,Sunk
14,11 May 1944,Shtorm,Soviet Union,412,Damaged
15,7 October 1941,Svend Foyn,United Kingdom,14795,Damaged
16,16 February 1942,Monagas,Venezuela,2650,Sunk
17,16 February 1942,San Nicholas,United Kingdom,2391,Sunk
18,16 February 1942,Tia Juana,United Kingdom,2395,Sunk
19,22 February 1942,J.N.Pew,United States,9033,Sunk
20,23 February 1942,Sun,United States,9002,Damaged
21,23 February 1942,Thalia,Panama,8329,Sunk
22,11 May 1942,Cape of Good Hope,United Kingdom,4963,Sunk
23,24 May 1942,Gonçalves Dias,Brazil,4996,Sunk
24,28 May 1942,Alcoa Pilgrim,United States,6759,Sunk
25,3 June 1942,M.F. Ellliot,United States,6940,Sunk
26,9 June 1942,Bruxelles,Belgium,5085,Sunk
27,9 June 1942,Franklin K. Lane,United States,6589,Sunk
28,15 June 1942,Cold Harbor,Panama,5010,Sunk
29,15 June 1942,Scottsburg,United States,8010,Sunk
30,15 June 1942,West Hardaway,United States,5702,Sunk

2
2.csv : 202_117.csv		203_148.csv
Missing Values(NANs):  {'date': '0/15', 'ship': '0/15', 'nationality': '0/15', 'tonnage (grt)': '0/15', 'fate': '0/15'}
Columns that match with input_schema:
202_117.csv :  {'ship': 'ship', 'nationality': 'nationality', 'fate': 'fate', 'tonnage': 'tonnage (grt)'}
203_148.csv :  {'nationality': 'nationality', 'tonnage (grt)': 'tonnage (grt)', 'fate': 'fate'}
Coverage Score :  1.0 	 Completeness Score :  1.0

,date,ship,nationality,tonnage (grt),fate
0,19 August 1941,SS Aguila,United Kingdom,3255,Sunk
1,27 November 1941,HMAS Parramatta,Royal Australian Navy,1060,Sunk
2,23 December 1941,SS Shuntien,United Kingdom,3059,Sunk
3,26 December 1941,SS Warszawa,Poland,2487,Sunk
4,10 June 1942,MV Athene,Norway,4681,Sunk
5,10 June 1942,SS Brambleleaf,United Kingdom,5917,Damaged
6,18 January 1940,Flandria,Sweden,1179,Sunk
7,19 January 1940,Patria,Sweden,1188,Sunk
8,11 February 1940,Linda,Estonia,1213,Sunk
9,4 May 1940,San Tiburcio,United Kingdom,5995,Sunk (mine)
10,9 May 1940,Doris,French Navy,552,Sunk
11,11 May 1940,Tringa,United Kingdom,1930,Sunk
12,11 May 1940,Viiu,Estonia,1908,Sunk
13,23 May 1940,Sigurd Faulbaum,Belgium,3256,Sunk
14,11 May 1944,Shtorm,Soviet Union,412,Damaged

3
3.csv : 202_117.csv		203_268.csv
Missing Values(NANs):  {'date': '0/22', 'ship': '0/22', 'nationality': '0/22', 'tonnage (grt)': '0/22', 'fate': '0/22'}
Columns that match with input_schema:
202_117.csv :  {'ship': 'ship', 'nationality': 'nationality', 'fate': 'fate', 'tonnage': 'tonnage (grt)'}
203_268.csv :  {'nationality': 'nationality', 'tonnage (grt)': 'tonnage (grt)', 'fate': 'fate'}
Coverage Score :  1.0 	 Completeness Score :  1.0

,date,ship,nationality,tonnage (grt),fate
0,19 August 1941,SS Aguila,United Kingdom,3255,Sunk
1,27 November 1941,HMAS Parramatta,Royal Australian Navy,1060,Sunk
2,23 December 1941,SS Shuntien,United Kingdom,3059,Sunk
3,26 December 1941,SS Warszawa,Poland,2487,Sunk
4,10 June 1942,MV Athene,Norway,4681,Sunk
5,10 June 1942,SS Brambleleaf,United Kingdom,5917,Damaged
6,7 October 1941,Svend Foyn,United Kingdom,14795,Damaged
7,16 February 1942,Monagas,Venezuela,2650,Sunk
8,16 February 1942,San Nicholas,United Kingdom,2391,Sunk
9,16 February 1942,Tia Juana,United Kingdom,2395,Sunk
10,22 February 1942,J.N.Pew,United States,9033,Sunk
11,23 February 1942,Sun,United States,9002,Damaged
12,23 February 1942,Thalia,Panama,8329,Sunk
13,11 May 1942,Cape of Good Hope,United Kingdom,4963,Sunk
14,24 May 1942,Gonçalves Dias,Brazil,4996,Sunk
15,28 May 1942,Alcoa Pilgrim,United States,6759,Sunk
16,3 June 1942,M.F. Ellliot,United States,6940,Sunk
17,9 June 1942,Bruxelles,Belgium,5085,Sunk
18,9 June 1942,Franklin K. Lane,United States,6589,Sunk
19,15 June 1942,Cold Harbor,Panama,5010,Sunk
20,15 June 1942,Scottsburg,United States,8010,Sunk
21,15 June 1942,West Hardaway,United States,5702,Sunk

4
4.csv : 203_148.csv		203_268.csv
Missing Values(NANs):  {'date': '0/25', 'name': '0/25', 'nationality': '0/25', 'tonnage (grt)': '0/25', 'fate': '0/25'}
Columns that match with input_schema:
203_148.csv :  {'nationality': 'nationality', 'tonnage (grt)': 'tonnage (grt)', 'fate': 'fate'}
203_268.csv :  {'nationality': 'nationality', 'tonnage (grt)': 'tonnage (grt)', 'fate': 'fate'}
Coverage Score :  0.75 	 Completeness Score :  0.75

,date,name,nationality,tonnage (grt),fate
0,18 January 1940,Flandria,Sweden,1179,Sunk
1,19 January 1940,Patria,Sweden,1188,Sunk
2,11 February 1940,Linda,Estonia,1213,Sunk
3,4 May 1940,San Tiburcio,United Kingdom,5995,Sunk (mine)
4,9 May 1940,Doris,French Navy,552,Sunk
5,11 May 1940,Tringa,United Kingdom,1930,Sunk
6,11 May 1940,Viiu,Estonia,1908,Sunk
7,23 May 1940,Sigurd Faulbaum,Belgium,3256,Sunk
8,11 May 1944,Shtorm,Soviet Union,412,Damaged
9,7 October 1941,Svend Foyn,United Kingdom,14795,Damaged
10,16 February 1942,Monagas,Venezuela,2650,Sunk
11,16 February 1942,San Nicholas,United Kingdom,2391,Sunk
12,16 February 1942,Tia Juana,United Kingdom,2395,Sunk
13,22 February 1942,J.N.Pew,United States,9033,Sunk
14,23 February 1942,Sun,United States,9002,Damaged
15,23 February 1942,Thalia,Panama,8329,Sunk
16,11 May 1942,Cape of Good Hope,United Kingdom,4963,Sunk
17,24 May 1942,Gonçalves Dias,Brazil,4996,Sunk
18,28 May 1942,Alcoa Pilgrim,United States,6759,Sunk
19,3 June 1942,M.F. Ellliot,United States,6940,Sunk
20,9 June 1942,Bruxelles,Belgium,5085,Sunk
21,9 June 1942,Franklin K. Lane,United States,6589,Sunk
22,15 June 1942,Cold Harbor,Panama,5010,Sunk
23,15 June 1942,Scottsburg,United States,8010,Sunk
24,15 June 1942,West Hardaway,United States,5702,Sunk

Rank  1   :  output_1.csv         completeness score : 1.0000000000000000 		number of rows:  31
Rank  2   :  output_3.csv         completeness score : 1.0000000000000000 		number of rows:  22
Rank  3   :  output_2.csv         completeness score : 1.0000000000000000 		number of rows:  15
Rank  4   :  204_100.csv          completeness score : 1.0000000000000000 		number of rows:  13
Rank  5   :  202_117.csv          completeness score : 1.0000000000000000 		number of rows:  6
Rank  6   :  output_4.csv         completeness score : 0.7500000000000000 		number of rows:  25
Rank  7   :  203_268.csv          completeness score : 0.7500000000000000 		number of rows:  16
Rank  8   :  203_148.csv          completeness score : 0.7500000000000000 		number of rows:  9

Ranking Complete!!

In [64]:
# Query 3 : Results
s='{"schema": {"rank": "object", "name": "object", "height": "object", "no of floors": "int64", "year": "int64"}}'
s=s.lower()
s=json.loads(s)
input_schema=s['schema'];input_categories=-1;transformations=-1;stats=-1
if "categories" in s:
    input_categories=s["categories"]
if "transformations" in s:
    transformations=s["transformations"]
if "stats" in s:
    stats=s["stats"]
# display query
print("Input Schema : ",input_schema)
if input_categories==-1:
    print("Input Categories : None")
else:
    print("Input Categories : ",input_categories)
if transformations==-1:
    print("Input Transformations : None")
else:
    print("Input Transformations : ",transformations)
if stats==-1:
    print("Input Condition based conditions : None")
else:
    print("Input Content based Conditions : ",stats)
print()
comp_score={}
no_of_rows={}
no_of_rows={}
get_matches(1)

Input Schema :  {'rank': 'object', 'name': 'object', 'height': 'object', 'no of floors': 'int64', 'year': 'int64'}
Input Categories : None
Input Transformations : None
Input Condition based conditions : None

only schema
Matching Tables
203_837.csv  :  List of tallest buildings in Columbus, Ohio
203_84.csv  :  List of tallest buildings in Oakland, California
204_541.csv  :  List of tallest buildings in Kanpur
204_649.csv  :  List of tallest buildings in Cleveland


203_837.csv(List of tallest buildings in Columbus, Ohio)
Missing Values(NANs score):  {'rank': '0/30', 'name': '0/30', 'height ft / m': '0/30', 'floors': '0/30', 'year': '0/30', 'notes': '24/30'}
Columns that match with input_schema:
 203_837.csv :  {'rank': 'rank', 'name': 'name', 'year': 'year', 'height ft / m': 'height', 'floors': 'no of floors'}
Coverage Score :  1.0 	 Completeness Score :  1.0

,rank,name,height,no of floors,year,notes
0,1,Rhodes State Office Tower,629 / 192,41,1973,Has been the tallest building in Columbus and ...
1,2,LeVeque Tower,555 / 169,47,1927,Tallest building constructed in Columbus in th...
2,3,William Green Building,530 / 162,33,1990,Tallest building constructed in Columbus in th...
3,4,Huntington Center,512 / 156,37,1984,Tallest building constructed in Columbus in th...
4,5,Vern Riffe State Office Tower,503 / 153,32,1988,NaN
5,6,One Nationwide Plaza,485 / 148,40,1976,NaN
6,7,Franklin County Courthouse,464 / 141,27,1991,NaN
7,8,AEP Building,456 / 139,31,1983,NaN
8,9,Borden Building,438 / 134,34,1974,NaN
9,10,Three Nationwide Plaza,408 / 124,27,1989,NaN
10,11,One Columbus Center,366 / 112,26,1987,NaN
11,12,Columbus Center,357 / 109,25,1964,Tallest building constructed in Columbus in th...
12,13,Capitol Square,350 / 107,26,1984,NaN
13,14,Continental Center,348 / 106,26,1973,NaN
14,15,PNC Bank Building,317 / 97,25,1977,NaN
15,16,Miranova Condominiums,314 / 96,26,2001,Tallest residential building in the state of O...
16,17,Fifth Third Center,302 / 92,25,1998,NaN
17,18,Motorists Mutual Building,286 / 87,21,1973,NaN
18,19,Midland Building,280 / 85,21,1970,NaN
19,20,The Condominiums at North Bank Park,267 / 81,20,2007,NaN
20,21=,Lincoln Tower Dormitory,260 / 79,26,1967,NaN
21,21=,Morrill Tower Dormitory,260 / 79,26,1967,NaN
22,23,Hyatt Regency Columbus,256 / 78,20,1980,NaN
23,24,Key Bank Building,253 / 77,20,1963,NaN
24,25,Adam's Mark Hotel,243 / 74,16,1961,NaN
25,26,Town Center,226 / 69,17,1974,NaN
26,27,8 East Broad Street,212 / 64.6,17,1906,NaN
27,28,Huntington Building,202 / 59.4,13,1926,NaN
28,29,Ohio Judicial Center,200 / 57.9,14,1933,NaN
29,30,16 East Broad Street,180 / 64.4,13,1900,NaN

203_84.csv(List of tallest buildings in Oakland, California)
Missing Values(NANs score):  {'rank': '0/21', 'name': '0/21', 'height ft (m)': '0/21', 'floors': '0/21', 'year': '2/21', 'coordinates': '0/21', 'notes': '14/21'}
Columns that match with input_schema:
 203_84.csv :  {'rank': 'rank', 'name': 'name', 'height ft (m)': 'height', 'floors': 'no of floors'}
Coverage Score :  1.0 	 Completeness Score :  0.980952380952381

,rank,name,height,no of floors,year,coordinates,notes
0,1,Ordway Building,404 (123),28,1970.0,37°48′36″N 122°15′51″W﻿ / ﻿37.81000°N 122.26417°W,Tallest building in both Oakland and in the Ba...
1,2,Kaiser Center,390 (119),28,1960.0,37°48′32″N 122°15′52″W﻿ / ﻿37.80889°N 122.26444°W,Tallest building constructed in the 1960s
2,3,Lake Merritt Plaza,371 (113),27,1988.0,37°48′27″N 122°15′54″W﻿ / ﻿37.80750°N 122.26500°W,Tallest building constructed in the 1980s
3,4,1111 Broadway,360 (110),24,1990.0,37°48′10″N 122°16′22″W﻿ / ﻿37.80278°N 122.27278°W,Tallest building constructed in the 1990s
4,5,Kaiser Engineering Building,336 (102),25,1984.0,37°48′21″N 122°15′54″W﻿ / ﻿37.80583°N 122.26500°W,NaN
5,6,Clorox Building,330 (101),24,1976.0,37°48′12″N 122°16′20″W﻿ / ﻿37.80333°N 122.27222°W,NaN
6,7=,EM Harris State Office Building,328 (100),22,1998.0,37°48′23″N 122°16′24″W﻿ / ﻿37.80639°N 122.27333°W,NaN
7,7=,Ronald V. Dellums Federal Building South,328 (100),18,1994.0,37°48′16″N 122°16′29″W﻿ / ﻿37.80444°N 122.27472°W,NaN
8,7=,Ronald V. Dellums Federal Building North,328 (100),18,1994.0,37°48′18″N 122°16′28″W﻿ / ﻿37.80500°N 122.27444°W,NaN
9,10,Oakland City Hall,320 (98),14,1914.0,37°48′19″N 122°16′21″W﻿ / ﻿37.80528°N 122.27250°W,Tallest building constructed in the 1910s; Nat...
10,11,Tribune Tower,310 (94),22,1906.0,37°48′11″N 122°16′14″W﻿ / ﻿37.80306°N 122.27056°W,Tallest building constructed in the 1920s
11,12,1330 Broadway,297 (91),21,NaN,37°48′14″N 122°16′14″W﻿ / ﻿37.80389°N 122.27056°W,NaN
12,13,Pacific Bell Building,296 (90),20,1985.0,37°48′37″N 122°15′57″W﻿ / ﻿37.81028°N 122.26583°W,NaN
13,14,555 City Center,279 (85),20,2002.0,37°48′13″N 122°16′31″W﻿ / ﻿37.80361°N 122.27528°W,NaN
14,15,Park Bellevue Tower,270 (82),25,1969.0,37°48′28″N 122°15′20″W﻿ / ﻿37.80778°N 122.25556°W,NaN
15,16,St. Paul's Towers,267 (81),22,1966.0,37°48′42″N 122°15′37″W﻿ / ﻿37.81167°N 122.26028°W,NaN
16,17,The Grand Apartments,263 (80),22,2008.0,37°48′41″N 122°15′53″W﻿ / ﻿37.81139°N 122.26472°W,NaN
17,18,Central Building,235 (72),15,1926.0,37°48′15″N 122°16′14″W﻿ / ﻿37.80417°N 122.27056°W,NaN
18,19,Bank of America Building,225 (69),18,1907.0,37°48′10″N 122°16′17″W﻿ / ﻿37.80278°N 122.27139°W,Tallest building constructed in the decade of ...
19,20,Financial Center Building,214 (65),14,1929.0,37°48′13″N 122°16′13″W﻿ / ﻿37.80361°N 122.27028°W,NaN
20,21,SBC Building,203 (62),15,NaN,37°48′21″N 122°16′08″W﻿ / ﻿37.80583°N 122.26889°W,NaN

204_541.csv(List of tallest buildings in Kanpur)
Missing Values(NANs score):  {'name': '0/7', 'area': '0/7', 'height': '0/7', 'floors': '0/7', 'year': '0/7'}
Columns that match with input_schema:
 204_541.csv :  {'name': 'name', 'height': 'height', 'year': 'year', 'floors': 'no of floors'}
Coverage Score :  0.8 	 Completeness Score :  0.8

,name,area,height,no of floors,year
0,Ratan Planet,"Opp. ALIMCO, Naramau, G.T Road, Kalianpur",90 metres (295 ft),16,2013
1,The Landmark Hotel,"Near Navin Market, Mall Road, Downtown",80 metres (262 ft),14,2000
2,Ratan Orbit,"Mukherjee Vihar, Kalianpur",70 metres (230 ft),14,2011
3,BSNL Tower,"Opp. Resrve Bank of India, Mall Road, Downtown",65 metres (213 ft),15,2001
4,Som Business Square (EL Mart),"Mega Mall Crossing, The Mall, Downtown",80 metres (262 ft),15,2005
5,Akashganga Heights,"City Bypass, Chakeri",60 metres (197 ft),15,1995
6,Krishna Tower,"Opp. Green Park Stadium, Parwati Bagla Road, C...",48 metres (157 ft),10,2003

204_649.csv(List of tallest buildings in Cleveland)
Missing Values(NANs score):  {'rank': '0/32', 'name': '0/32', 'height ft (m)': '0/32', 'floors': '0/32', 'year': '0/32', 'notes': '15/32'}
Columns that match with input_schema:
 204_649.csv :  {'rank': 'rank', 'name': 'name', 'year': 'year', 'height ft (m)': 'height', 'floors': 'no of floors'}
Coverage Score :  1.0 	 Completeness Score :  1.0

,rank,name,height,no of floors,year,notes
0,1,Key Tower,947 (289),57,1991,104th-tallest building in the world 20th-talle...
1,2,Terminal Tower,723 (220),52,1930,114th-tallest building in the United States St...
2,3,200 Public Square,658 (201),45,1985,Also known as the BP Building Tallest building...
3,4,Tower at Erieview,529 (161),40,1964,Tallest building constructed in Cleveland in t...
4,5,One Cleveland Center,450 (137),31,1983,NaN
5,6,Fifth Third Center,446 (136),27,1992,NaN
6,7,Federal Court House Tower,430 (131),23,2002,Tallest building constructed in the city in th...
7,8,Justice Center Complex,420 (128),26,1977,Tallest building constructed in the city in th...
8,9,Anthony J. Celebrezze Federal Building,419 (128),31,1967,NaN
9,10,PNC Center,410 (125),35,1980,Originally known as the National City Center; ...
10,11,AT Tower,390 (119),28,1971,Previously known as Cleveland Trust Tower Curr...
11,12,AT&T Huron Road Building,365 (111),24,1927,Commonly known as Ohio Bell Buildinh Previousl...
12,13,Rhodes Tower,363 (111),20,1971,Originally known as the University Tower
13,14,Eaton Center,356 (109),28,1983,NaN
14,15,Ernst & Young Tower,330 (101),21,2013,Phase I of the Flats East Bank redevelopment p...
15,16,Marriott at Key Center,320 (98),28,1991,Tallest all-hotel building in the city
16,17,McDonald Investment Center,308 (94),23,1968,Also known as Key Center Formerly known as the...
17,18,55 Public Square,300 (91),22,1958,Tallest building constructed in the city the 1...
18,19,Huntington Bank Building,289 (88),21,1924,NaN
19,20,North Point Tower,285 (87),20,1990,NaN
20,21=,Diamond Building,282 (86),23,1972,NaN
21,21=,Standard Building,282 (86),21,1925,NaN
22,23,1717 East Ninth Building,275 (84),21,1959,Also known as the East Ohio Building
23,24,Keith Building,272 (83),21,1922,NaN
24,25=,East Tower,266 (81),25,1973,Tallest all-residential building in the city A...
25,25=,Embassy Suites Tower,266 (81),26,1969,Also known as Embassy Suites at Reserve Square
26,27,Superior Building,265 (81),22,1922,NaN
27,28,Fenn Tower,265 (81),21,1930,NaN
28,29,Landmark Office Towers,260 (79),22,1930,NaN
29,30=,Penton Media Building,253 (77),21,1972,NaN
30,30=,Ohio Savings Plaza,253 (77),17,1969,NaN
31,30=,Ameritech Center,253 (77),16,1983,NaN

1.csv : 203_837.csv		203_84.csv		204_541.csv		204_649.csv
Missing Values(NANs):  {'rank': '7/90', 'name': '0/90', 'height': '0/90', 'no of floors': '0/90', 'year': '2/90'}
Columns that match with input_schema:
203_837.csv :  {'rank': 'rank', 'name': 'name', 'year': 'year', 'height ft / m': 'height', 'floors': 'no of floors'}
203_84.csv :  {'rank': 'rank', 'name': 'name', 'height ft (m)': 'height', 'floors': 'no of floors'}
204_541.csv :  {'name': 'name', 'height': 'height', 'year': 'year', 'floors': 'no of floors'}
204_649.csv :  {'rank': 'rank', 'name': 'name', 'year': 'year', 'height ft (m)': 'height', 'floors': 'no of floors'}
Coverage Score :  1.0 	 Completeness Score :  0.9800000000000001

,rank,name,height,no of floors,year
0,1,Rhodes State Office Tower,629 / 192,41,1973.0
1,2,LeVeque Tower,555 / 169,47,1927.0
2,3,William Green Building,530 / 162,33,1990.0
3,4,Huntington Center,512 / 156,37,1984.0
4,5,Vern Riffe State Office Tower,503 / 153,32,1988.0
5,6,One Nationwide Plaza,485 / 148,40,1976.0
6,7,Franklin County Courthouse,464 / 141,27,1991.0
7,8,AEP Building,456 / 139,31,1983.0
8,9,Borden Building,438 / 134,34,1974.0
9,10,Three Nationwide Plaza,408 / 124,27,1989.0
10,11,One Columbus Center,366 / 112,26,1987.0
11,12,Columbus Center,357 / 109,25,1964.0
12,13,Capitol Square,350 / 107,26,1984.0
13,14,Continental Center,348 / 106,26,1973.0
14,15,PNC Bank Building,317 / 97,25,1977.0
15,16,Miranova Condominiums,314 / 96,26,2001.0
16,17,Fifth Third Center,302 / 92,25,1998.0
17,18,Motorists Mutual Building,286 / 87,21,1973.0
18,19,Midland Building,280 / 85,21,1970.0
19,20,The Condominiums at North Bank Park,267 / 81,20,2007.0
20,21=,Lincoln Tower Dormitory,260 / 79,26,1967.0
21,21=,Morrill Tower Dormitory,260 / 79,26,1967.0
22,23,Hyatt Regency Columbus,256 / 78,20,1980.0
23,24,Key Bank Building,253 / 77,20,1963.0
24,25,Adam's Mark Hotel,243 / 74,16,1961.0
25,26,Town Center,226 / 69,17,1974.0
26,27,8 East Broad Street,212 / 64.6,17,1906.0
27,28,Huntington Building,202 / 59.4,13,1926.0
28,29,Ohio Judicial Center,200 / 57.9,14,1933.0
29,30,16 East Broad Street,180 / 64.4,13,1900.0
...,...,...,...,...,...
60,3,200 Public Square,658 (201),45,1985.0
61,4,Tower at Erieview,529 (161),40,1964.0
62,5,One Cleveland Center,450 (137),31,1983.0
63,6,Fifth Third Center,446 (136),27,1992.0
64,7,Federal Court House Tower,430 (131),23,2002.0
65,8,Justice Center Complex,420 (128),26,1977.0
66,9,Anthony J. Celebrezze Federal Building,419 (128),31,1967.0
67,10,PNC Center,410 (125),35,1980.0
68,11,AT Tower,390 (119),28,1971.0
69,12,AT&T Huron Road Building,365 (111),24,1927.0
70,13,Rhodes Tower,363 (111),20,1971.0
71,14,Eaton Center,356 (109),28,1983.0
72,15,Ernst & Young Tower,330 (101),21,2013.0
73,16,Marriott at Key Center,320 (98),28,1991.0
74,17,McDonald Investment Center,308 (94),23,1968.0
75,18,55 Public Square,300 (91),22,1958.0
76,19,Huntington Bank Building,289 (88),21,1924.0
77,20,North Point Tower,285 (87),20,1990.0
78,21=,Diamond Building,282 (86),23,1972.0
79,21=,Standard Building,282 (86),21,1925.0
80,23,1717 East Ninth Building,275 (84),21,1959.0
81,24,Keith Building,272 (83),21,1922.0
82,25=,East Tower,266 (81),25,1973.0
83,25=,Embassy Suites Tower,266 (81),26,1969.0
84,27,Superior Building,265 (81),22,1922.0
85,28,Fenn Tower,265 (81),21,1930.0
86,29,Landmark Office Towers,260 (79),22,1930.0
87,30=,Penton Media Building,253 (77),21,1972.0
88,30=,Ohio Savings Plaza,253 (77),17,1969.0
89,30=,Ameritech Center,253 (77),16,1983.0

2.csv : 203_837.csv		203_84.csv		204_541.csv
Missing Values(NANs):  {'rank': '7/58', 'name': '0/58', 'height': '0/58', 'no of floors': '0/58', 'year': '2/58'}
Columns that match with input_schema:
203_837.csv :  {'rank': 'rank', 'name': 'name', 'year': 'year', 'height ft / m': 'height', 'floors': 'no of floors'}
203_84.csv :  {'rank': 'rank', 'name': 'name', 'height ft (m)': 'height', 'floors': 'no of floors'}
204_541.csv :  {'name': 'name', 'height': 'height', 'year': 'year', 'floors': 'no of floors'}
Coverage Score :  1.0 	 Completeness Score :  0.9689655172413794

,rank,name,height,no of floors,year
0,1,Rhodes State Office Tower,629 / 192,41,1973.0
1,2,LeVeque Tower,555 / 169,47,1927.0
2,3,William Green Building,530 / 162,33,1990.0
3,4,Huntington Center,512 / 156,37,1984.0
4,5,Vern Riffe State Office Tower,503 / 153,32,1988.0
5,6,One Nationwide Plaza,485 / 148,40,1976.0
6,7,Franklin County Courthouse,464 / 141,27,1991.0
7,8,AEP Building,456 / 139,31,1983.0
8,9,Borden Building,438 / 134,34,1974.0
9,10,Three Nationwide Plaza,408 / 124,27,1989.0
10,11,One Columbus Center,366 / 112,26,1987.0
11,12,Columbus Center,357 / 109,25,1964.0
12,13,Capitol Square,350 / 107,26,1984.0
13,14,Continental Center,348 / 106,26,1973.0
14,15,PNC Bank Building,317 / 97,25,1977.0
15,16,Miranova Condominiums,314 / 96,26,2001.0
16,17,Fifth Third Center,302 / 92,25,1998.0
17,18,Motorists Mutual Building,286 / 87,21,1973.0
18,19,Midland Building,280 / 85,21,1970.0
19,20,The Condominiums at North Bank Park,267 / 81,20,2007.0
20,21=,Lincoln Tower Dormitory,260 / 79,26,1967.0
21,21=,Morrill Tower Dormitory,260 / 79,26,1967.0
22,23,Hyatt Regency Columbus,256 / 78,20,1980.0
23,24,Key Bank Building,253 / 77,20,1963.0
24,25,Adam's Mark Hotel,243 / 74,16,1961.0
25,26,Town Center,226 / 69,17,1974.0
26,27,8 East Broad Street,212 / 64.6,17,1906.0
27,28,Huntington Building,202 / 59.4,13,1926.0
28,29,Ohio Judicial Center,200 / 57.9,14,1933.0
29,30,16 East Broad Street,180 / 64.4,13,1900.0
30,1,Ordway Building,404 (123),28,1970.0
31,2,Kaiser Center,390 (119),28,1960.0
32,3,Lake Merritt Plaza,371 (113),27,1988.0
33,4,1111 Broadway,360 (110),24,1990.0
34,5,Kaiser Engineering Building,336 (102),25,1984.0
35,6,Clorox Building,330 (101),24,1976.0
36,7=,EM Harris State Office Building,328 (100),22,1998.0
37,7=,Ronald V. Dellums Federal Building South,328 (100),18,1994.0
38,7=,Ronald V. Dellums Federal Building North,328 (100),18,1994.0
39,10,Oakland City Hall,320 (98),14,1914.0
40,11,Tribune Tower,310 (94),22,1906.0
41,12,1330 Broadway,297 (91),21,NaN
42,13,Pacific Bell Building,296 (90),20,1985.0
43,14,555 City Center,279 (85),20,2002.0
44,15,Park Bellevue Tower,270 (82),25,1969.0
45,16,St. Paul's Towers,267 (81),22,1966.0
46,17,The Grand Apartments,263 (80),22,2008.0
47,18,Central Building,235 (72),15,1926.0
48,19,Bank of America Building,225 (69),18,1907.0
49,20,Financial Center Building,214 (65),14,1929.0
50,21,SBC Building,203 (62),15,NaN
51,NaN,Ratan Planet,90 metres (295 ft),16,2013.0
52,NaN,The Landmark Hotel,80 metres (262 ft),14,2000.0
53,NaN,Ratan Orbit,70 metres (230 ft),14,2011.0
54,NaN,BSNL Tower,65 metres (213 ft),15,2001.0
55,NaN,Som Business Square (EL Mart),80 metres (262 ft),15,2005.0
56,NaN,Akashganga Heights,60 metres (197 ft),15,1995.0
57,NaN,Krishna Tower,48 metres (157 ft),10,2003.0

3.csv : 203_837.csv		203_84.csv		204_649.csv
Missing Values(NANs):  {'rank': '0/83', 'name': '0/83', 'height': '0/83', 'no of floors': '0/83', 'year': '2/83'}
Columns that match with input_schema:
203_837.csv :  {'rank': 'rank', 'name': 'name', 'year': 'year', 'height ft / m': 'height', 'floors': 'no of floors'}
203_84.csv :  {'rank': 'rank', 'name': 'name', 'height ft (m)': 'height', 'floors': 'no of floors'}
204_649.csv :  {'rank': 'rank', 'name': 'name', 'year': 'year', 'height ft (m)': 'height', 'floors': 'no of floors'}
Coverage Score :  1.0 	 Completeness Score :  0.9951807228915662

,rank,name,height,no of floors,year
0,1,Rhodes State Office Tower,629 / 192,41,1973.0
1,2,LeVeque Tower,555 / 169,47,1927.0
2,3,William Green Building,530 / 162,33,1990.0
3,4,Huntington Center,512 / 156,37,1984.0
4,5,Vern Riffe State Office Tower,503 / 153,32,1988.0
5,6,One Nationwide Plaza,485 / 148,40,1976.0
6,7,Franklin County Courthouse,464 / 141,27,1991.0
7,8,AEP Building,456 / 139,31,1983.0
8,9,Borden Building,438 / 134,34,1974.0
9,10,Three Nationwide Plaza,408 / 124,27,1989.0
10,11,One Columbus Center,366 / 112,26,1987.0
11,12,Columbus Center,357 / 109,25,1964.0
12,13,Capitol Square,350 / 107,26,1984.0
13,14,Continental Center,348 / 106,26,1973.0
14,15,PNC Bank Building,317 / 97,25,1977.0
15,16,Miranova Condominiums,314 / 96,26,2001.0
16,17,Fifth Third Center,302 / 92,25,1998.0
17,18,Motorists Mutual Building,286 / 87,21,1973.0
18,19,Midland Building,280 / 85,21,1970.0
19,20,The Condominiums at North Bank Park,267 / 81,20,2007.0
20,21=,Lincoln Tower Dormitory,260 / 79,26,1967.0
21,21=,Morrill Tower Dormitory,260 / 79,26,1967.0
22,23,Hyatt Regency Columbus,256 / 78,20,1980.0
23,24,Key Bank Building,253 / 77,20,1963.0
24,25,Adam's Mark Hotel,243 / 74,16,1961.0
25,26,Town Center,226 / 69,17,1974.0
26,27,8 East Broad Street,212 / 64.6,17,1906.0
27,28,Huntington Building,202 / 59.4,13,1926.0
28,29,Ohio Judicial Center,200 / 57.9,14,1933.0
29,30,16 East Broad Street,180 / 64.4,13,1900.0
...,...,...,...,...,...
53,3,200 Public Square,658 (201),45,1985.0
54,4,Tower at Erieview,529 (161),40,1964.0
55,5,One Cleveland Center,450 (137),31,1983.0
56,6,Fifth Third Center,446 (136),27,1992.0
57,7,Federal Court House Tower,430 (131),23,2002.0
58,8,Justice Center Complex,420 (128),26,1977.0
59,9,Anthony J. Celebrezze Federal Building,419 (128),31,1967.0
60,10,PNC Center,410 (125),35,1980.0
61,11,AT Tower,390 (119),28,1971.0
62,12,AT&T Huron Road Building,365 (111),24,1927.0
63,13,Rhodes Tower,363 (111),20,1971.0
64,14,Eaton Center,356 (109),28,1983.0
65,15,Ernst & Young Tower,330 (101),21,2013.0
66,16,Marriott at Key Center,320 (98),28,1991.0
67,17,McDonald Investment Center,308 (94),23,1968.0
68,18,55 Public Square,300 (91),22,1958.0
69,19,Huntington Bank Building,289 (88),21,1924.0
70,20,North Point Tower,285 (87),20,1990.0
71,21=,Diamond Building,282 (86),23,1972.0
72,21=,Standard Building,282 (86),21,1925.0
73,23,1717 East Ninth Building,275 (84),21,1959.0
74,24,Keith Building,272 (83),21,1922.0
75,25=,East Tower,266 (81),25,1973.0
76,25=,Embassy Suites Tower,266 (81),26,1969.0
77,27,Superior Building,265 (81),22,1922.0
78,28,Fenn Tower,265 (81),21,1930.0
79,29,Landmark Office Towers,260 (79),22,1930.0
80,30=,Penton Media Building,253 (77),21,1972.0
81,30=,Ohio Savings Plaza,253 (77),17,1969.0
82,30=,Ameritech Center,253 (77),16,1983.0

4.csv : 203_837.csv		204_541.csv		204_649.csv
Missing Values(NANs):  {'rank': '7/69', 'name': '0/69', 'height': '0/69', 'no of floors': '0/69', 'year': '0/69'}
Columns that match with input_schema:
203_837.csv :  {'rank': 'rank', 'name': 'name', 'year': 'year', 'height ft / m': 'height', 'floors': 'no of floors'}
204_541.csv :  {'name': 'name', 'height': 'height', 'year': 'year', 'floors': 'no of floors'}
204_649.csv :  {'rank': 'rank', 'name': 'name', 'year': 'year', 'height ft (m)': 'height', 'floors': 'no of floors'}
Coverage Score :  1.0 	 Completeness Score :  0.9797101449275363

,rank,name,height,no of floors,year
0,1,Rhodes State Office Tower,629 / 192,41,1973
1,2,LeVeque Tower,555 / 169,47,1927
2,3,William Green Building,530 / 162,33,1990
3,4,Huntington Center,512 / 156,37,1984
4,5,Vern Riffe State Office Tower,503 / 153,32,1988
5,6,One Nationwide Plaza,485 / 148,40,1976
6,7,Franklin County Courthouse,464 / 141,27,1991
7,8,AEP Building,456 / 139,31,1983
8,9,Borden Building,438 / 134,34,1974
9,10,Three Nationwide Plaza,408 / 124,27,1989
10,11,One Columbus Center,366 / 112,26,1987
11,12,Columbus Center,357 / 109,25,1964
12,13,Capitol Square,350 / 107,26,1984
13,14,Continental Center,348 / 106,26,1973
14,15,PNC Bank Building,317 / 97,25,1977
15,16,Miranova Condominiums,314 / 96,26,2001
16,17,Fifth Third Center,302 / 92,25,1998
17,18,Motorists Mutual Building,286 / 87,21,1973
18,19,Midland Building,280 / 85,21,1970
19,20,The Condominiums at North Bank Park,267 / 81,20,2007
20,21=,Lincoln Tower Dormitory,260 / 79,26,1967
21,21=,Morrill Tower Dormitory,260 / 79,26,1967
22,23,Hyatt Regency Columbus,256 / 78,20,1980
23,24,Key Bank Building,253 / 77,20,1963
24,25,Adam's Mark Hotel,243 / 74,16,1961
25,26,Town Center,226 / 69,17,1974
26,27,8 East Broad Street,212 / 64.6,17,1906
27,28,Huntington Building,202 / 59.4,13,1926
28,29,Ohio Judicial Center,200 / 57.9,14,1933
29,30,16 East Broad Street,180 / 64.4,13,1900
...,...,...,...,...,...
39,3,200 Public Square,658 (201),45,1985
40,4,Tower at Erieview,529 (161),40,1964
41,5,One Cleveland Center,450 (137),31,1983
42,6,Fifth Third Center,446 (136),27,1992
43,7,Federal Court House Tower,430 (131),23,2002
44,8,Justice Center Complex,420 (128),26,1977
45,9,Anthony J. Celebrezze Federal Building,419 (128),31,1967
46,10,PNC Center,410 (125),35,1980
47,11,AT Tower,390 (119),28,1971
48,12,AT&T Huron Road Building,365 (111),24,1927
49,13,Rhodes Tower,363 (111),20,1971
50,14,Eaton Center,356 (109),28,1983
51,15,Ernst & Young Tower,330 (101),21,2013
52,16,Marriott at Key Center,320 (98),28,1991
53,17,McDonald Investment Center,308 (94),23,1968
54,18,55 Public Square,300 (91),22,1958
55,19,Huntington Bank Building,289 (88),21,1924
56,20,North Point Tower,285 (87),20,1990
57,21=,Diamond Building,282 (86),23,1972
58,21=,Standard Building,282 (86),21,1925
59,23,1717 East Ninth Building,275 (84),21,1959
60,24,Keith Building,272 (83),21,1922
61,25=,East Tower,266 (81),25,1973
62,25=,Embassy Suites Tower,266 (81),26,1969
63,27,Superior Building,265 (81),22,1922
64,28,Fenn Tower,265 (81),21,1930
65,29,Landmark Office Towers,260 (79),22,1930
66,30=,Penton Media Building,253 (77),21,1972
67,30=,Ohio Savings Plaza,253 (77),17,1969
68,30=,Ameritech Center,253 (77),16,1983

5.csv : 203_84.csv		204_541.csv		204_649.csv
Missing Values(NANs):  {'rank': '7/60', 'name': '0/60', 'height': '0/60', 'no of floors': '0/60', 'year': '2/60'}
Columns that match with input_schema:
203_84.csv :  {'rank': 'rank', 'name': 'name', 'height ft (m)': 'height', 'floors': 'no of floors'}
204_541.csv :  {'name': 'name', 'height': 'height', 'year': 'year', 'floors': 'no of floors'}
204_649.csv :  {'rank': 'rank', 'name': 'name', 'year': 'year', 'height ft (m)': 'height', 'floors': 'no of floors'}
Coverage Score :  1.0 	 Completeness Score :  0.97

,rank,name,height,no of floors,year
0,1,Ordway Building,404 (123),28,1970.0
1,2,Kaiser Center,390 (119),28,1960.0
2,3,Lake Merritt Plaza,371 (113),27,1988.0
3,4,1111 Broadway,360 (110),24,1990.0
4,5,Kaiser Engineering Building,336 (102),25,1984.0
5,6,Clorox Building,330 (101),24,1976.0
6,7=,EM Harris State Office Building,328 (100),22,1998.0
7,7=,Ronald V. Dellums Federal Building South,328 (100),18,1994.0
8,7=,Ronald V. Dellums Federal Building North,328 (100),18,1994.0
9,10,Oakland City Hall,320 (98),14,1914.0
10,11,Tribune Tower,310 (94),22,1906.0
11,12,1330 Broadway,297 (91),21,NaN
12,13,Pacific Bell Building,296 (90),20,1985.0
13,14,555 City Center,279 (85),20,2002.0
14,15,Park Bellevue Tower,270 (82),25,1969.0
15,16,St. Paul's Towers,267 (81),22,1966.0
16,17,The Grand Apartments,263 (80),22,2008.0
17,18,Central Building,235 (72),15,1926.0
18,19,Bank of America Building,225 (69),18,1907.0
19,20,Financial Center Building,214 (65),14,1929.0
20,21,SBC Building,203 (62),15,NaN
21,NaN,Ratan Planet,90 metres (295 ft),16,2013.0
22,NaN,The Landmark Hotel,80 metres (262 ft),14,2000.0
23,NaN,Ratan Orbit,70 metres (230 ft),14,2011.0
24,NaN,BSNL Tower,65 metres (213 ft),15,2001.0
25,NaN,Som Business Square (EL Mart),80 metres (262 ft),15,2005.0
26,NaN,Akashganga Heights,60 metres (197 ft),15,1995.0
27,NaN,Krishna Tower,48 metres (157 ft),10,2003.0
28,1,Key Tower,947 (289),57,1991.0
29,2,Terminal Tower,723 (220),52,1930.0
30,3,200 Public Square,658 (201),45,1985.0
31,4,Tower at Erieview,529 (161),40,1964.0
32,5,One Cleveland Center,450 (137),31,1983.0
33,6,Fifth Third Center,446 (136),27,1992.0
34,7,Federal Court House Tower,430 (131),23,2002.0
35,8,Justice Center Complex,420 (128),26,1977.0
36,9,Anthony J. Celebrezze Federal Building,419 (128),31,1967.0
37,10,PNC Center,410 (125),35,1980.0
38,11,AT Tower,390 (119),28,1971.0
39,12,AT&T Huron Road Building,365 (111),24,1927.0
40,13,Rhodes Tower,363 (111),20,1971.0
41,14,Eaton Center,356 (109),28,1983.0
42,15,Ernst & Young Tower,330 (101),21,2013.0
43,16,Marriott at Key Center,320 (98),28,1991.0
44,17,McDonald Investment Center,308 (94),23,1968.0
45,18,55 Public Square,300 (91),22,1958.0
46,19,Huntington Bank Building,289 (88),21,1924.0
47,20,North Point Tower,285 (87),20,1990.0
48,21=,Diamond Building,282 (86),23,1972.0
49,21=,Standard Building,282 (86),21,1925.0
50,23,1717 East Ninth Building,275 (84),21,1959.0
51,24,Keith Building,272 (83),21,1922.0
52,25=,East Tower,266 (81),25,1973.0
53,25=,Embassy Suites Tower,266 (81),26,1969.0
54,27,Superior Building,265 (81),22,1922.0
55,28,Fenn Tower,265 (81),21,1930.0
56,29,Landmark Office Towers,260 (79),22,1930.0
57,30=,Penton Media Building,253 (77),21,1972.0
58,30=,Ohio Savings Plaza,253 (77),17,1969.0
59,30=,Ameritech Center,253 (77),16,1983.0

6.csv : 203_837.csv		203_84.csv
Missing Values(NANs):  {'rank': '0/51', 'name': '0/51', 'height': '0/51', 'no of floors': '0/51', 'year': '2/51'}
Columns that match with input_schema:
203_837.csv :  {'rank': 'rank', 'name': 'name', 'year': 'year', 'height ft / m': 'height', 'floors': 'no of floors'}
203_84.csv :  {'rank': 'rank', 'name': 'name', 'height ft (m)': 'height', 'floors': 'no of floors'}
Coverage Score :  1.0 	 Completeness Score :  0.9921568627450981

,rank,name,height,no of floors,year
0,1,Rhodes State Office Tower,629 / 192,41,1973.0
1,2,LeVeque Tower,555 / 169,47,1927.0
2,3,William Green Building,530 / 162,33,1990.0
3,4,Huntington Center,512 / 156,37,1984.0
4,5,Vern Riffe State Office Tower,503 / 153,32,1988.0
5,6,One Nationwide Plaza,485 / 148,40,1976.0
6,7,Franklin County Courthouse,464 / 141,27,1991.0
7,8,AEP Building,456 / 139,31,1983.0
8,9,Borden Building,438 / 134,34,1974.0
9,10,Three Nationwide Plaza,408 / 124,27,1989.0
10,11,One Columbus Center,366 / 112,26,1987.0
11,12,Columbus Center,357 / 109,25,1964.0
12,13,Capitol Square,350 / 107,26,1984.0
13,14,Continental Center,348 / 106,26,1973.0
14,15,PNC Bank Building,317 / 97,25,1977.0
15,16,Miranova Condominiums,314 / 96,26,2001.0
16,17,Fifth Third Center,302 / 92,25,1998.0
17,18,Motorists Mutual Building,286 / 87,21,1973.0
18,19,Midland Building,280 / 85,21,1970.0
19,20,The Condominiums at North Bank Park,267 / 81,20,2007.0
20,21=,Lincoln Tower Dormitory,260 / 79,26,1967.0
21,21=,Morrill Tower Dormitory,260 / 79,26,1967.0
22,23,Hyatt Regency Columbus,256 / 78,20,1980.0
23,24,Key Bank Building,253 / 77,20,1963.0
24,25,Adam's Mark Hotel,243 / 74,16,1961.0
25,26,Town Center,226 / 69,17,1974.0
26,27,8 East Broad Street,212 / 64.6,17,1906.0
27,28,Huntington Building,202 / 59.4,13,1926.0
28,29,Ohio Judicial Center,200 / 57.9,14,1933.0
29,30,16 East Broad Street,180 / 64.4,13,1900.0
30,1,Ordway Building,404 (123),28,1970.0
31,2,Kaiser Center,390 (119),28,1960.0
32,3,Lake Merritt Plaza,371 (113),27,1988.0
33,4,1111 Broadway,360 (110),24,1990.0
34,5,Kaiser Engineering Building,336 (102),25,1984.0
35,6,Clorox Building,330 (101),24,1976.0
36,7=,EM Harris State Office Building,328 (100),22,1998.0
37,7=,Ronald V. Dellums Federal Building South,328 (100),18,1994.0
38,7=,Ronald V. Dellums Federal Building North,328 (100),18,1994.0
39,10,Oakland City Hall,320 (98),14,1914.0
40,11,Tribune Tower,310 (94),22,1906.0
41,12,1330 Broadway,297 (91),21,NaN
42,13,Pacific Bell Building,296 (90),20,1985.0
43,14,555 City Center,279 (85),20,2002.0
44,15,Park Bellevue Tower,270 (82),25,1969.0
45,16,St. Paul's Towers,267 (81),22,1966.0
46,17,The Grand Apartments,263 (80),22,2008.0
47,18,Central Building,235 (72),15,1926.0
48,19,Bank of America Building,225 (69),18,1907.0
49,20,Financial Center Building,214 (65),14,1929.0
50,21,SBC Building,203 (62),15,NaN

7.csv : 203_837.csv		204_541.csv
Missing Values(NANs):  {'rank': '7/37', 'name': '0/37', 'height': '0/37', 'no of floors': '0/37', 'year': '0/37'}
Columns that match with input_schema:
203_837.csv :  {'rank': 'rank', 'name': 'name', 'year': 'year', 'height ft / m': 'height', 'floors': 'no of floors'}
204_541.csv :  {'name': 'name', 'height': 'height', 'year': 'year', 'floors': 'no of floors'}
Coverage Score :  1.0 	 Completeness Score :  0.9621621621621621

,rank,name,height,no of floors,year
0,1,Rhodes State Office Tower,629 / 192,41,1973
1,2,LeVeque Tower,555 / 169,47,1927
2,3,William Green Building,530 / 162,33,1990
3,4,Huntington Center,512 / 156,37,1984
4,5,Vern Riffe State Office Tower,503 / 153,32,1988
5,6,One Nationwide Plaza,485 / 148,40,1976
6,7,Franklin County Courthouse,464 / 141,27,1991
7,8,AEP Building,456 / 139,31,1983
8,9,Borden Building,438 / 134,34,1974
9,10,Three Nationwide Plaza,408 / 124,27,1989
10,11,One Columbus Center,366 / 112,26,1987
11,12,Columbus Center,357 / 109,25,1964
12,13,Capitol Square,350 / 107,26,1984
13,14,Continental Center,348 / 106,26,1973
14,15,PNC Bank Building,317 / 97,25,1977
15,16,Miranova Condominiums,314 / 96,26,2001
16,17,Fifth Third Center,302 / 92,25,1998
17,18,Motorists Mutual Building,286 / 87,21,1973
18,19,Midland Building,280 / 85,21,1970
19,20,The Condominiums at North Bank Park,267 / 81,20,2007
20,21=,Lincoln Tower Dormitory,260 / 79,26,1967
21,21=,Morrill Tower Dormitory,260 / 79,26,1967
22,23,Hyatt Regency Columbus,256 / 78,20,1980
23,24,Key Bank Building,253 / 77,20,1963
24,25,Adam's Mark Hotel,243 / 74,16,1961
25,26,Town Center,226 / 69,17,1974
26,27,8 East Broad Street,212 / 64.6,17,1906
27,28,Huntington Building,202 / 59.4,13,1926
28,29,Ohio Judicial Center,200 / 57.9,14,1933
29,30,16 East Broad Street,180 / 64.4,13,1900
30,NaN,Ratan Planet,90 metres (295 ft),16,2013
31,NaN,The Landmark Hotel,80 metres (262 ft),14,2000
32,NaN,Ratan Orbit,70 metres (230 ft),14,2011
33,NaN,BSNL Tower,65 metres (213 ft),15,2001
34,NaN,Som Business Square (EL Mart),80 metres (262 ft),15,2005
35,NaN,Akashganga Heights,60 metres (197 ft),15,1995
36,NaN,Krishna Tower,48 metres (157 ft),10,2003

8.csv : 203_837.csv		204_649.csv
Missing Values(NANs):  {'rank': '0/62', 'name': '0/62', 'height': '0/62', 'no of floors': '0/62', 'year': '0/62'}
Columns that match with input_schema:
203_837.csv :  {'rank': 'rank', 'name': 'name', 'year': 'year', 'height ft / m': 'height', 'floors': 'no of floors'}
204_649.csv :  {'rank': 'rank', 'name': 'name', 'year': 'year', 'height ft (m)': 'height', 'floors': 'no of floors'}
Coverage Score :  1.0 	 Completeness Score :  1.0

,rank,name,height,no of floors,year
0,1,Rhodes State Office Tower,629 / 192,41,1973
1,2,LeVeque Tower,555 / 169,47,1927
2,3,William Green Building,530 / 162,33,1990
3,4,Huntington Center,512 / 156,37,1984
4,5,Vern Riffe State Office Tower,503 / 153,32,1988
5,6,One Nationwide Plaza,485 / 148,40,1976
6,7,Franklin County Courthouse,464 / 141,27,1991
7,8,AEP Building,456 / 139,31,1983
8,9,Borden Building,438 / 134,34,1974
9,10,Three Nationwide Plaza,408 / 124,27,1989
10,11,One Columbus Center,366 / 112,26,1987
11,12,Columbus Center,357 / 109,25,1964
12,13,Capitol Square,350 / 107,26,1984
13,14,Continental Center,348 / 106,26,1973
14,15,PNC Bank Building,317 / 97,25,1977
15,16,Miranova Condominiums,314 / 96,26,2001
16,17,Fifth Third Center,302 / 92,25,1998
17,18,Motorists Mutual Building,286 / 87,21,1973
18,19,Midland Building,280 / 85,21,1970
19,20,The Condominiums at North Bank Park,267 / 81,20,2007
20,21=,Lincoln Tower Dormitory,260 / 79,26,1967
21,21=,Morrill Tower Dormitory,260 / 79,26,1967
22,23,Hyatt Regency Columbus,256 / 78,20,1980
23,24,Key Bank Building,253 / 77,20,1963
24,25,Adam's Mark Hotel,243 / 74,16,1961
25,26,Town Center,226 / 69,17,1974
26,27,8 East Broad Street,212 / 64.6,17,1906
27,28,Huntington Building,202 / 59.4,13,1926
28,29,Ohio Judicial Center,200 / 57.9,14,1933
29,30,16 East Broad Street,180 / 64.4,13,1900
...,...,...,...,...,...
32,3,200 Public Square,658 (201),45,1985
33,4,Tower at Erieview,529 (161),40,1964
34,5,One Cleveland Center,450 (137),31,1983
35,6,Fifth Third Center,446 (136),27,1992
36,7,Federal Court House Tower,430 (131),23,2002
37,8,Justice Center Complex,420 (128),26,1977
38,9,Anthony J. Celebrezze Federal Building,419 (128),31,1967
39,10,PNC Center,410 (125),35,1980
40,11,AT Tower,390 (119),28,1971
41,12,AT&T Huron Road Building,365 (111),24,1927
42,13,Rhodes Tower,363 (111),20,1971
43,14,Eaton Center,356 (109),28,1983
44,15,Ernst & Young Tower,330 (101),21,2013
45,16,Marriott at Key Center,320 (98),28,1991
46,17,McDonald Investment Center,308 (94),23,1968
47,18,55 Public Square,300 (91),22,1958
48,19,Huntington Bank Building,289 (88),21,1924
49,20,North Point Tower,285 (87),20,1990
50,21=,Diamond Building,282 (86),23,1972
51,21=,Standard Building,282 (86),21,1925
52,23,1717 East Ninth Building,275 (84),21,1959
53,24,Keith Building,272 (83),21,1922
54,25=,East Tower,266 (81),25,1973
55,25=,Embassy Suites Tower,266 (81),26,1969
56,27,Superior Building,265 (81),22,1922
57,28,Fenn Tower,265 (81),21,1930
58,29,Landmark Office Towers,260 (79),22,1930
59,30=,Penton Media Building,253 (77),21,1972
60,30=,Ohio Savings Plaza,253 (77),17,1969
61,30=,Ameritech Center,253 (77),16,1983

9.csv : 203_84.csv		204_541.csv
Missing Values(NANs):  {'rank': '7/28', 'name': '0/28', 'height': '0/28', 'no of floors': '0/28', 'year': '2/28', 'coordinates': '7/28'}
Columns that match with input_schema:
203_84.csv :  {'rank': 'rank', 'name': 'name', 'height ft (m)': 'height', 'floors': 'no of floors'}
204_541.csv :  {'name': 'name', 'height': 'height', 'year': 'year', 'floors': 'no of floors'}
Coverage Score :  1.0 	 Completeness Score :  0.9357142857142857

,rank,name,height,no of floors,year,coordinates
0,1,Ordway Building,404 (123),28,1970.0,37°48′36″N 122°15′51″W﻿ / ﻿37.81000°N 122.26417°W
1,2,Kaiser Center,390 (119),28,1960.0,37°48′32″N 122°15′52″W﻿ / ﻿37.80889°N 122.26444°W
2,3,Lake Merritt Plaza,371 (113),27,1988.0,37°48′27″N 122°15′54″W﻿ / ﻿37.80750°N 122.26500°W
3,4,1111 Broadway,360 (110),24,1990.0,37°48′10″N 122°16′22″W﻿ / ﻿37.80278°N 122.27278°W
4,5,Kaiser Engineering Building,336 (102),25,1984.0,37°48′21″N 122°15′54″W﻿ / ﻿37.80583°N 122.26500°W
5,6,Clorox Building,330 (101),24,1976.0,37°48′12″N 122°16′20″W﻿ / ﻿37.80333°N 122.27222°W
6,7=,EM Harris State Office Building,328 (100),22,1998.0,37°48′23″N 122°16′24″W﻿ / ﻿37.80639°N 122.27333°W
7,7=,Ronald V. Dellums Federal Building South,328 (100),18,1994.0,37°48′16″N 122°16′29″W﻿ / ﻿37.80444°N 122.27472°W
8,7=,Ronald V. Dellums Federal Building North,328 (100),18,1994.0,37°48′18″N 122°16′28″W﻿ / ﻿37.80500°N 122.27444°W
9,10,Oakland City Hall,320 (98),14,1914.0,37°48′19″N 122°16′21″W﻿ / ﻿37.80528°N 122.27250°W
10,11,Tribune Tower,310 (94),22,1906.0,37°48′11″N 122°16′14″W﻿ / ﻿37.80306°N 122.27056°W
11,12,1330 Broadway,297 (91),21,NaN,37°48′14″N 122°16′14″W﻿ / ﻿37.80389°N 122.27056°W
12,13,Pacific Bell Building,296 (90),20,1985.0,37°48′37″N 122°15′57″W﻿ / ﻿37.81028°N 122.26583°W
13,14,555 City Center,279 (85),20,2002.0,37°48′13″N 122°16′31″W﻿ / ﻿37.80361°N 122.27528°W
14,15,Park Bellevue Tower,270 (82),25,1969.0,37°48′28″N 122°15′20″W﻿ / ﻿37.80778°N 122.25556°W
15,16,St. Paul's Towers,267 (81),22,1966.0,37°48′42″N 122°15′37″W﻿ / ﻿37.81167°N 122.26028°W
16,17,The Grand Apartments,263 (80),22,2008.0,37°48′41″N 122°15′53″W﻿ / ﻿37.81139°N 122.26472°W
17,18,Central Building,235 (72),15,1926.0,37°48′15″N 122°16′14″W﻿ / ﻿37.80417°N 122.27056°W
18,19,Bank of America Building,225 (69),18,1907.0,37°48′10″N 122°16′17″W﻿ / ﻿37.80278°N 122.27139°W
19,20,Financial Center Building,214 (65),14,1929.0,37°48′13″N 122°16′13″W﻿ / ﻿37.80361°N 122.27028°W
20,21,SBC Building,203 (62),15,NaN,37°48′21″N 122°16′08″W﻿ / ﻿37.80583°N 122.26889°W
21,NaN,Ratan Planet,90 metres (295 ft),16,2013.0,NaN
22,NaN,The Landmark Hotel,80 metres (262 ft),14,2000.0,NaN
23,NaN,Ratan Orbit,70 metres (230 ft),14,2011.0,NaN
24,NaN,BSNL Tower,65 metres (213 ft),15,2001.0,NaN
25,NaN,Som Business Square (EL Mart),80 metres (262 ft),15,2005.0,NaN
26,NaN,Akashganga Heights,60 metres (197 ft),15,1995.0,NaN
27,NaN,Krishna Tower,48 metres (157 ft),10,2003.0,NaN

10.csv : 203_84.csv		204_649.csv
Missing Values(NANs):  {'rank': '0/53', 'name': '0/53', 'height': '0/53', 'no of floors': '0/53', 'year': '2/53'}
Columns that match with input_schema:
203_84.csv :  {'rank': 'rank', 'name': 'name', 'height ft (m)': 'height', 'floors': 'no of floors'}
204_649.csv :  {'rank': 'rank', 'name': 'name', 'year': 'year', 'height ft (m)': 'height', 'floors': 'no of floors'}
Coverage Score :  1.0 	 Completeness Score :  0.9924528301886791

,rank,name,height,no of floors,year
0,1,Ordway Building,404 (123),28,1970.0
1,2,Kaiser Center,390 (119),28,1960.0
2,3,Lake Merritt Plaza,371 (113),27,1988.0
3,4,1111 Broadway,360 (110),24,1990.0
4,5,Kaiser Engineering Building,336 (102),25,1984.0
5,6,Clorox Building,330 (101),24,1976.0
6,7=,EM Harris State Office Building,328 (100),22,1998.0
7,7=,Ronald V. Dellums Federal Building South,328 (100),18,1994.0
8,7=,Ronald V. Dellums Federal Building North,328 (100),18,1994.0
9,10,Oakland City Hall,320 (98),14,1914.0
10,11,Tribune Tower,310 (94),22,1906.0
11,12,1330 Broadway,297 (91),21,NaN
12,13,Pacific Bell Building,296 (90),20,1985.0
13,14,555 City Center,279 (85),20,2002.0
14,15,Park Bellevue Tower,270 (82),25,1969.0
15,16,St. Paul's Towers,267 (81),22,1966.0
16,17,The Grand Apartments,263 (80),22,2008.0
17,18,Central Building,235 (72),15,1926.0
18,19,Bank of America Building,225 (69),18,1907.0
19,20,Financial Center Building,214 (65),14,1929.0
20,21,SBC Building,203 (62),15,NaN
21,1,Key Tower,947 (289),57,1991.0
22,2,Terminal Tower,723 (220),52,1930.0
23,3,200 Public Square,658 (201),45,1985.0
24,4,Tower at Erieview,529 (161),40,1964.0
25,5,One Cleveland Center,450 (137),31,1983.0
26,6,Fifth Third Center,446 (136),27,1992.0
27,7,Federal Court House Tower,430 (131),23,2002.0
28,8,Justice Center Complex,420 (128),26,1977.0
29,9,Anthony J. Celebrezze Federal Building,419 (128),31,1967.0
30,10,PNC Center,410 (125),35,1980.0
31,11,AT Tower,390 (119),28,1971.0
32,12,AT&T Huron Road Building,365 (111),24,1927.0
33,13,Rhodes Tower,363 (111),20,1971.0
34,14,Eaton Center,356 (109),28,1983.0
35,15,Ernst & Young Tower,330 (101),21,2013.0
36,16,Marriott at Key Center,320 (98),28,1991.0
37,17,McDonald Investment Center,308 (94),23,1968.0
38,18,55 Public Square,300 (91),22,1958.0
39,19,Huntington Bank Building,289 (88),21,1924.0
40,20,North Point Tower,285 (87),20,1990.0
41,21=,Diamond Building,282 (86),23,1972.0
42,21=,Standard Building,282 (86),21,1925.0
43,23,1717 East Ninth Building,275 (84),21,1959.0
44,24,Keith Building,272 (83),21,1922.0
45,25=,East Tower,266 (81),25,1973.0
46,25=,Embassy Suites Tower,266 (81),26,1969.0
47,27,Superior Building,265 (81),22,1922.0
48,28,Fenn Tower,265 (81),21,1930.0
49,29,Landmark Office Towers,260 (79),22,1930.0
50,30=,Penton Media Building,253 (77),21,1972.0
51,30=,Ohio Savings Plaza,253 (77),17,1969.0
52,30=,Ameritech Center,253 (77),16,1983.0

11.csv : 204_541.csv		204_649.csv
Missing Values(NANs):  {'name': '0/39', 'height': '0/39', 'no of floors': '0/39', 'year': '0/39', 'rank': '7/39'}
Columns that match with input_schema:
204_541.csv :  {'name': 'name', 'height': 'height', 'year': 'year', 'floors': 'no of floors'}
204_649.csv :  {'rank': 'rank', 'name': 'name', 'year': 'year', 'height ft (m)': 'height', 'floors': 'no of floors'}
Coverage Score :  1.0 	 Completeness Score :  0.964102564102564

,name,height,no of floors,year,rank
0,Ratan Planet,90 metres (295 ft),16,2013,NaN
1,The Landmark Hotel,80 metres (262 ft),14,2000,NaN
2,Ratan Orbit,70 metres (230 ft),14,2011,NaN
3,BSNL Tower,65 metres (213 ft),15,2001,NaN
4,Som Business Square (EL Mart),80 metres (262 ft),15,2005,NaN
5,Akashganga Heights,60 metres (197 ft),15,1995,NaN
6,Krishna Tower,48 metres (157 ft),10,2003,NaN
7,Key Tower,947 (289),57,1991,1
8,Terminal Tower,723 (220),52,1930,2
9,200 Public Square,658 (201),45,1985,3
10,Tower at Erieview,529 (161),40,1964,4
11,One Cleveland Center,450 (137),31,1983,5
12,Fifth Third Center,446 (136),27,1992,6
13,Federal Court House Tower,430 (131),23,2002,7
14,Justice Center Complex,420 (128),26,1977,8
15,Anthony J. Celebrezze Federal Building,419 (128),31,1967,9
16,PNC Center,410 (125),35,1980,10
17,AT Tower,390 (119),28,1971,11
18,AT&T Huron Road Building,365 (111),24,1927,12
19,Rhodes Tower,363 (111),20,1971,13
20,Eaton Center,356 (109),28,1983,14
21,Ernst & Young Tower,330 (101),21,2013,15
22,Marriott at Key Center,320 (98),28,1991,16
23,McDonald Investment Center,308 (94),23,1968,17
24,55 Public Square,300 (91),22,1958,18
25,Huntington Bank Building,289 (88),21,1924,19
26,North Point Tower,285 (87),20,1990,20
27,Diamond Building,282 (86),23,1972,21=
28,Standard Building,282 (86),21,1925,21=
29,1717 East Ninth Building,275 (84),21,1959,23
30,Keith Building,272 (83),21,1922,24
31,East Tower,266 (81),25,1973,25=
32,Embassy Suites Tower,266 (81),26,1969,25=
33,Superior Building,265 (81),22,1922,27
34,Fenn Tower,265 (81),21,1930,28
35,Landmark Office Towers,260 (79),22,1930,29
36,Penton Media Building,253 (77),21,1972,30=
37,Ohio Savings Plaza,253 (77),17,1969,30=
38,Ameritech Center,253 (77),16,1983,30=

Rank  1   :  output_8.csv         completeness score : 1.0000000000000000 		number of rows:  62
Rank  2   :  204_649.csv          completeness score : 1.0000000000000000 		number of rows:  32
Rank  3   :  203_837.csv          completeness score : 1.0000000000000000 		number of rows:  30
Rank  4   :  output_3.csv         completeness score : 0.9951807228915662 		number of rows:  83
Rank  5   :  output_10.csv        completeness score : 0.9924528301886791 		number of rows:  53
Rank  6   :  output_6.csv         completeness score : 0.9921568627450981 		number of rows:  51
Rank  7   :  203_84.csv           completeness score : 0.9809523809523810 		number of rows:  21
Rank  8   :  output_1.csv         completeness score : 0.9800000000000001 		number of rows:  90
Rank  9   :  output_4.csv         completeness score : 0.9797101449275363 		number of rows:  69
Rank  10  :  output_5.csv         completeness score : 0.9700000000000000 		number of rows:  60
Rank  11  :  output_2.csv         completeness score : 0.9689655172413794 		number of rows:  58
Rank  12  :  output_11.csv        completeness score : 0.9641025641025640 		number of rows:  39
Rank  13  :  output_7.csv         completeness score : 0.9621621621621621 		number of rows:  37
Rank  14  :  output_9.csv         completeness score : 0.9357142857142857 		number of rows:  28
Rank  15  :  204_541.csv          completeness score : 0.8000000000000000 		number of rows:  7

Ranking Complete!!

In [80]:
# Query 4 : Results
s='{"schema":{"phase": "object", "date": "object", "terrain": "object", "length": "object", "race winner": "object", "leader": "object"},"categories":["france","cycling","sports","events"]}'
s=s.lower()
s=json.loads(s)
input_schema=s['schema'];input_categories=-1;transformations=-1;stats=-1
if "categories" in s:
    input_categories=s["categories"]
if "transformations" in s:
    transformations=s["transformations"]
if "stats" in s:
    stats=s["stats"]
# display query
print("Input Schema : ",input_schema)
if input_categories==-1:
    print("Input Categories : None")
else:
    print("Input Categories : ",input_categories)
if transformations==-1:
    print("Input Transformations : None")
else:
    print("Input Transformations : ",transformations)
if stats==-1:
    print("Input Condition based conditions : None")
else:
    print("Input Content based Conditions : ",stats)
print()
comp_score={}
no_of_rows={}
no_of_rows={}
get_matches()

Input Schema :  {'phase': 'object', 'date': 'object', 'terrain': 'object', 'length': 'object', 'race winner': 'object', 'leader': 'object'}
Input Categories :  ['france', 'cycling', 'sports', 'events']
Input Transformations : None
Input Condition based conditions : None

category and schema
Matching Tables
203_25.csv  :  1983 Tour de France
203_44.csv  :  1964 Tour de France
203_475.csv  :  1995 Tour de France
204_312.csv  :  1978 Tour de France
204_406.csv  :  1931 Tour de France


203_25.csv(1983 Tour de France)
Missing Values(NANs score):  {'stage': '0/23', 'date': '0/23', 'route': '21/23', 'terrain': '0/23', 'length': '0/23', 'winner': '0/23'}
Columns that match with input_schema:
 203_25.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
Coverage Score :  0.8333333333333334 	 Completeness Score :  0.8333333333333334

,phase,date,route,terrain,length,race winner
0,P,1 July,Fontenay-sous-Bois,Individual time trial,6 km (3.7 mi),Eric Vanderaerden (BEL)
1,1,2 July,NaN,Plain stage,163 km (101 mi),Frits Pirard (NED)
2,2,3 July,NaN,Team time trial,100 km (62 mi),Mercier
3,3,4 July,NaN,Hilly stage,152 km (94 mi),Rudy Matthijs (BEL)
4,4,5 July,NaN,Plain stage,300 km (190 mi),Serge Demierre (SUI)
5,5,6 July,NaN,Plain stage,257 km (160 mi),Dominique Gaigne (FRA)
6,6,7 July,NaN,Individual time trial,58 km (36 mi),Bert Oosterbosch (NED)
7,7,8 July,NaN,Plain stage,216 km (134 mi),Riccardo Magrini (ITA)
8,8,9 July,NaN,Plain stage,222 km (138 mi),Bert Oosterbosch (NED)
9,9,10 July,NaN,Plain stage,207 km (129 mi),Philippe Chevallier (FRA)
10,10,11 July,NaN,Stage with mountain(s),201 km (125 mi),Robert Millar (GBR)
11,11,12 July,NaN,Plain stage,177 km (110 mi),Regis Clere (FRA)
12,12,13 July,NaN,Plain stage,261 km (162 mi),Kim Andersen (DEN)
13,13,14 July,NaN,Hilly stage,210 km (130 mi),Henk Lubberding (NED)
14,14,15 July,NaN,Hilly stage,149 km (93 mi),Pierre Le Bigaut (FRA)
15,15,16 July,NaN,Individual time trial,16 km (9.9 mi),Ángel Arroyo (ESP)
16,16,17 July,NaN,Hilly stage,144 km (89 mi),Michel Laurent (FRA)
17,17,18 July,NaN,Stage with mountain(s),223 km (139 mi),Peter Winnen (NED)
18,18,20 July,NaN,Stage with mountain(s),247 km (153 mi),Jacques Michaud (FRA)
19,19,21 July,NaN,Individual time trial,15 km (9.3 mi),Lucien Van Impe (BEL)
20,20,22 July,NaN,Plain stage,291 km (181 mi),Philippe Leleu (FRA)
21,21,23 July,Dijon,Individual time trial,50 km (31 mi),Laurent Fignon (FRA)
22,22,24 July,NaN,Plain stage,195 km (121 mi),Gilbert Glaus (SUI)

203_44.csv(1964 Tour de France)
Missing Values(NANs score):  {'stage': '0/25', 'date': '0/25', 'terrain': '0/25', 'length': '0/25', 'winner': '0/25'}
Columns that match with input_schema:
 203_44.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
Coverage Score :  0.8333333333333334 	 Completeness Score :  0.8333333333333334

,phase,date,terrain,length,race winner
0,1,22 June,Plain stage,215 km (134 mi),Edward Sels (BEL)
1,2,23 June,Plain stage,208 km (129 mi),Andre Darrigade (FRA)
2,3A,24 June,Plain stage,197 km (122 mi),Bernard Vandekerkhove (BEL)
3,3B,24 June,Team time trial,21 km (13 mi),Kas-Kaskol
4,4,25 June,Plain stage,292 km (181 mi),Rudi Altig (GER)
5,5,26 June,Plain stage,161 km (100 mi),Willy Derboven (BEL)
6,6,27 June,Plain stage,200 km (120 mi),Henk Nijdam (NED)
7,7,28 June,Plain stage,195 km (121 mi),Jan Janssen (NED)
8,8,29 June,Stage with mountain(s),249 km (155 mi),Federico Bahamontes (ESP)
9,9,30 June,Stage with mountain(s),239 km (149 mi),Jacques Anquetil (FRA)
10,10A,1 July,Plain stage,187 km (116 mi),Jan Janssen (NED)
11,10B,1 July,Individual time trial,21 km (13 mi),Jacques Anquetil (FRA)
12,11,2 July,Plain stage,250 km (160 mi),Edward Sels (BEL)
13,12,3 July,Plain stage,174 km (108 mi),Jo de Roo (NED)
14,13,4 July,Stage with mountain(s),170 km (110 mi),Julio Jimenez (ESP)
15,14,6 July,Stage with mountain(s),186 km (116 mi),Edward Sels (BEL)
16,15,7 July,Stage with mountain(s),203 km (126 mi),Raymond Poulidor (FRA)
17,16,8 July,Stage with mountain(s),197 km (122 mi),Federico Bahamontes (ESP)
18,17,9 July,Individual time trial,43 km (27 mi),Jacques Anquetil (FRA)
19,18,10 July,Plain stage,187 km (116 mi),Andre Darrigade (FRA)
20,19,11 July,Plain stage,215 km (134 mi),Edward Sels (BEL)
21,20,12 July,Stage with mountain(s),217 km (135 mi),Julio Jimenez (ESP)
22,21,13 July,Plain stage,311 km (193 mi),Jean Stablinski (FRA)
23,22A,14 July,Plain stage,119 km (74 mi),Benoni Beheyt (BEL)
24,22B,14 July,Individual time trial,27 km (17 mi),Jacques Anquetil (FRA)

203_475.csv(1995 Tour de France)
Missing Values(NANs score):  {'stage': '0/21', 'date': '0/21', 'route': '20/21', 'terrain': '0/21', 'length': '0/21', 'winner': '0/21'}
Columns that match with input_schema:
 203_475.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
Coverage Score :  0.8333333333333334 	 Completeness Score :  0.8333333333333334

,phase,date,route,terrain,length,race winner
0,P,1 July,Saint-Brieuc,Individual time trial,7.3 km (4.5 mi),Jacky Durand (FRA)
1,1,2 July,NaN,Plain stage,233.5 km (145.1 mi),Fabio Baldato (ITA)
2,2,3 July,NaN,Plain stage,235.5 km (146.3 mi),Mario Cipollini (ITA)
3,3,4 July,NaN,Team time trial,67.0 km (41.6 mi),Gewiss-Ballan (ITA)
4,4,5 July,NaN,Plain stage,162.0 km (100.7 mi),Mario Cipollini (ITA)
5,5,6 July,NaN,Plain stage,261.0 km (162.2 mi),Jeroen Blijlevens (NED)
6,6,7 July,NaN,Plain stage,202.0 km (125.5 mi),Erik Zabel (GER)
7,7,8 July,NaN,Hilly stage,203.0 km (126.1 mi),Johan Bruyneel (BEL)
8,8,9 July,NaN,Individual time trial,54.0 km (33.6 mi),Miguel Indurain (ESP)
9,9,11 July,NaN,Stage with mountain(s),160.0 km (99.4 mi),Alex Zulle (SUI)
10,10,12 July,NaN,Stage with mountain(s),162.5 km (101.0 mi),Marco Pantani (ITA)
11,11,13 July,NaN,Hilly stage,199.0 km (123.7 mi),Maximilian Sciandri (GBR)
12,12,14 July,NaN,Hilly stage,222.5 km (138.3 mi),Laurent Jalabert (FRA)
13,13,15 July,NaN,Plain stage,245.0 km (152.2 mi),Serhiy Utchakov (UKR)
14,14,16 July,NaN,Stage with mountain(s),164.0 km (101.9 mi),Marco Pantani (ITA)
15,15,18 July,NaN,Stage with mountain(s),206.0 km (128.0 mi),Richard Virenque (FRA)
16,16,19 July,NaN,Stage with mountain(s),149.0 km (92.6 mi),Cancelled
17,17,20 July,NaN,Plain stage,246.0 km (152.9 mi),Erik Zabel (GER)
18,18,21 July,NaN,Plain stage,166.5 km (103.5 mi),Lance Armstrong (USA)
19,19,22 July,NaN,Individual time trial,46.5 km (28.9 mi),Miguel Indurain (ESP)
20,20,23 July,NaN,Plain stage,155.0 km (96.3 mi),Djamolidine Abduzhaparov (UZB)

204_312.csv(1978 Tour de France)
Missing Values(NANs score):  {'stage': '0/25', 'date': '0/25', 'route': '24/25', 'terrain': '0/25', 'length': '0/25', 'winner': '0/25'}
Columns that match with input_schema:
 204_312.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
Coverage Score :  0.8333333333333334 	 Completeness Score :  0.8333333333333334

,phase,date,route,terrain,length,race winner
0,P,29 June,Leiden,Individual time trial,5 km (3.1 mi),Jan Raas (NED)
1,1A,30 June,NaN,Plain stage,135 km (84 mi),Jan Raas (NED)
2,1B,30 June,NaN,Plain stage,100 km (62 mi),Walter Planckaert (BEL)
3,2,1 July,NaN,Plain stage,199 km (124 mi),Jacques Esclassan (FRA)
4,3,2 July,NaN,Plain stage,244 km (152 mi),Klaus-Peter Thaler (GER)
5,4,3 July,NaN,Team time trial,153 km (95 mi),TI-Raleigh
6,5,4 July,NaN,Plain stage,244 km (152 mi),Freddy Maertens (BEL)
7,6,5 July,NaN,Plain stage,162 km (101 mi),Sean Kelly (IRE)
8,7,6 July,NaN,Plain stage,242 km (150 mi),Freddy Maertens (BEL)
9,8,7 July,NaN,Individual time trial,59 km (37 mi),Bernard Hinault (FRA)
10,9,8 July,NaN,Plain stage,233 km (145 mi),Miguel Maria Lasa (ESP)
11,10,10 July,NaN,Hilly stage,192 km (119 mi),Henk Lubberding (NED)
12,11,11 July,NaN,Stage with mountain(s),161 km (100 mi),Mariano Martinez (FRA)
13,12A,12 July,NaN,Plain stage,158 km (98 mi),Cancelled
14,12B,12 July,NaN,Plain stage,96 km (60 mi),Jacques Esclassan (FRA)
15,13,13 July,NaN,Hilly stage,221 km (137 mi),Paul Wellens (BEL)
16,14,14 July,NaN,Individual time trial,52 km (32 mi),Joop Zoetemelk (NED)
17,15,15 July,NaN,Hilly stage,196 km (122 mi),Bernard Hinault (FRA)
18,16,16 July,NaN,Stage with mountain(s),241 km (150 mi),Hennie Kuiper (NED)
19,17,18 July,NaN,Stage with mountain(s),225 km (140 mi),Christian Seznec (FRA)
20,18,19 July,NaN,Plain stage,137 km (85 mi),Gerrie Knetemann (NED)
21,19,20 July,NaN,Plain stage,182 km (113 mi),Marc Demeyer (BEL)
22,20,21 July,NaN,Individual time trial,72 km (45 mi),Bernard Hinault (FRA)
23,21,22 July,NaN,Plain stage,207 km (129 mi),Jan Raas (NED)
24,22,23 July,NaN,Plain stage,162 km (101 mi),Gerrie Knetemann (NED)

204_406.csv(1931 Tour de France)
Missing Values(NANs score):  {'stage': '0/24', 'date': '0/24', 'terrain': '0/24', 'length': '0/24', 'winner': '0/24', 'race leader': '0/24'}
Columns that match with input_schema:
 204_406.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'winner': 'race winner', 'race leader': 'leader'}
Coverage Score :  0.8333333333333334 	 Completeness Score :  0.8333333333333334

,stage,date,terrain,length,race winner,leader
0,1,30 June,Plain stage,208 km (129 mi),Alfred Haemerlinck (BEL),Alfred Haemerlinck (BEL)
1,2,1 July,Plain stage,212 km (132 mi),Max Bulla (AUT),Max Bulla (AUT)
2,3,2 July,Plain stage,206 km (128 mi),Fabio Battesini (ITA),Leon Le Calvez (FRA)
3,4,3 July,Plain stage,211 km (131 mi),Andre Godinat (FRA),Rafaele di Paco (ITA)
4,5,4 July,Plain stage,202 km (126 mi),Charles Pelissier (FRA),Charles Pelissier (FRA) Rafaele di Paco (ITA)
5,6,5 July,Plain stage,338 km (210 mi),Alfred Haemerlinck (BEL),Rafaele di Paco (ITA)
6,7,6 July,Plain stage,180 km (110 mi),Gerard Loncke (BEL),Rafaele di Paco (ITA)
7,8,7 July,Plain stage,106 km (66 mi),Charles Pelissier (FRA),Charles Pelissier (FRA)
8,9,8 July,Stage with mountain(s),231 km (144 mi),Antonin Magne (FRA),Antonin Magne (FRA)
9,10,10 July,Stage with mountain(s),322 km (200 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
10,11,12 July,Plain stage,164 km (102 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
11,12,13 July,Plain stage,207 km (129 mi),Max Bulla (AUT),Antonin Magne (FRA)
12,13,14 July,Plain stage,181 km (112 mi),Charles Pelissier (FRA),Antonin Magne (FRA)
13,14,15 July,Stage with mountain(s),132 km (82 mi),Eugenio Gestri (ITA),Antonin Magne (FRA)
14,15,17 July,Stage with mountain(s),233 km (145 mi),Jef Demuysere (BEL),Antonin Magne (FRA)
15,16,18 July,Stage with mountain(s),102 km (63 mi),Charles Pelissier (FRA),Antonin Magne (FRA)
16,17,19 July,Stage with mountain(s),230 km (140 mi),Max Bulla (AUT),Antonin Magne (FRA)
17,18,20 July,Stage with mountain(s),204 km (127 mi),Jef Demuysere (BEL),Antonin Magne (FRA)
18,19,21 July,Stage with mountain(s),282 km (175 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
19,20,22 July,Stage with mountain(s),209 km (130 mi),Andre Leducq (FRA),Antonin Magne (FRA)
20,21,23 July,Plain stage,192 km (119 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
21,22,24 July,Plain stage,159 km (99 mi),Raffaele di Paco (ITA),Antonin Magne (FRA)
22,23,25 July,Plain stage,271 km (168 mi),Gaston Rebry (BEL),Antonin Magne (FRA)
23,24,26 July,Plain stage,313 km (194 mi),Charles Pelissier (FRA),Antonin Magne (FRA)

1.csv : 203_25.csv		203_44.csv		203_475.csv		204_312.csv		204_406.csv
Missing Values(NANs):  {'phase': '24/118', 'date': '0/118', 'terrain': '0/118', 'length': '0/118', 'race winner': '0/118', 'leader': '94/118'}
Columns that match with input_schema:
203_25.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
203_44.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
203_475.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
204_312.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
204_406.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'winner': 'race winner', 'race leader': 'leader'}
Coverage Score :  1.0 	 Completeness Score :  0.8333333333333335

,phase,date,terrain,length,race winner,leader
0,P,1 July,Individual time trial,6 km (3.7 mi),Eric Vanderaerden (BEL),NaN
1,1,2 July,Plain stage,163 km (101 mi),Frits Pirard (NED),NaN
2,2,3 July,Team time trial,100 km (62 mi),Mercier,NaN
3,3,4 July,Hilly stage,152 km (94 mi),Rudy Matthijs (BEL),NaN
4,4,5 July,Plain stage,300 km (190 mi),Serge Demierre (SUI),NaN
5,5,6 July,Plain stage,257 km (160 mi),Dominique Gaigne (FRA),NaN
6,6,7 July,Individual time trial,58 km (36 mi),Bert Oosterbosch (NED),NaN
7,7,8 July,Plain stage,216 km (134 mi),Riccardo Magrini (ITA),NaN
8,8,9 July,Plain stage,222 km (138 mi),Bert Oosterbosch (NED),NaN
9,9,10 July,Plain stage,207 km (129 mi),Philippe Chevallier (FRA),NaN
10,10,11 July,Stage with mountain(s),201 km (125 mi),Robert Millar (GBR),NaN
11,11,12 July,Plain stage,177 km (110 mi),Regis Clere (FRA),NaN
12,12,13 July,Plain stage,261 km (162 mi),Kim Andersen (DEN),NaN
13,13,14 July,Hilly stage,210 km (130 mi),Henk Lubberding (NED),NaN
14,14,15 July,Hilly stage,149 km (93 mi),Pierre Le Bigaut (FRA),NaN
15,15,16 July,Individual time trial,16 km (9.9 mi),Ángel Arroyo (ESP),NaN
16,16,17 July,Hilly stage,144 km (89 mi),Michel Laurent (FRA),NaN
17,17,18 July,Stage with mountain(s),223 km (139 mi),Peter Winnen (NED),NaN
18,18,20 July,Stage with mountain(s),247 km (153 mi),Jacques Michaud (FRA),NaN
19,19,21 July,Individual time trial,15 km (9.3 mi),Lucien Van Impe (BEL),NaN
20,20,22 July,Plain stage,291 km (181 mi),Philippe Leleu (FRA),NaN
21,21,23 July,Individual time trial,50 km (31 mi),Laurent Fignon (FRA),NaN
22,22,24 July,Plain stage,195 km (121 mi),Gilbert Glaus (SUI),NaN
23,1,22 June,Plain stage,215 km (134 mi),Edward Sels (BEL),NaN
24,2,23 June,Plain stage,208 km (129 mi),Andre Darrigade (FRA),NaN
25,3A,24 June,Plain stage,197 km (122 mi),Bernard Vandekerkhove (BEL),NaN
26,3B,24 June,Team time trial,21 km (13 mi),Kas-Kaskol,NaN
27,4,25 June,Plain stage,292 km (181 mi),Rudi Altig (GER),NaN
28,5,26 June,Plain stage,161 km (100 mi),Willy Derboven (BEL),NaN
29,6,27 June,Plain stage,200 km (120 mi),Henk Nijdam (NED),NaN
...,...,...,...,...,...,...
88,17,18 July,Stage with mountain(s),225 km (140 mi),Christian Seznec (FRA),NaN
89,18,19 July,Plain stage,137 km (85 mi),Gerrie Knetemann (NED),NaN
90,19,20 July,Plain stage,182 km (113 mi),Marc Demeyer (BEL),NaN
91,20,21 July,Individual time trial,72 km (45 mi),Bernard Hinault (FRA),NaN
92,21,22 July,Plain stage,207 km (129 mi),Jan Raas (NED),NaN
93,22,23 July,Plain stage,162 km (101 mi),Gerrie Knetemann (NED),NaN
94,NaN,30 June,Plain stage,208 km (129 mi),Alfred Haemerlinck (BEL),Alfred Haemerlinck (BEL)
95,NaN,1 July,Plain stage,212 km (132 mi),Max Bulla (AUT),Max Bulla (AUT)
96,NaN,2 July,Plain stage,206 km (128 mi),Fabio Battesini (ITA),Leon Le Calvez (FRA)
97,NaN,3 July,Plain stage,211 km (131 mi),Andre Godinat (FRA),Rafaele di Paco (ITA)
98,NaN,4 July,Plain stage,202 km (126 mi),Charles Pelissier (FRA),Charles Pelissier (FRA) Rafaele di Paco (ITA)
99,NaN,5 July,Plain stage,338 km (210 mi),Alfred Haemerlinck (BEL),Rafaele di Paco (ITA)
100,NaN,6 July,Plain stage,180 km (110 mi),Gerard Loncke (BEL),Rafaele di Paco (ITA)
101,NaN,7 July,Plain stage,106 km (66 mi),Charles Pelissier (FRA),Charles Pelissier (FRA)
102,NaN,8 July,Stage with mountain(s),231 km (144 mi),Antonin Magne (FRA),Antonin Magne (FRA)
103,NaN,10 July,Stage with mountain(s),322 km (200 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
104,NaN,12 July,Plain stage,164 km (102 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
105,NaN,13 July,Plain stage,207 km (129 mi),Max Bulla (AUT),Antonin Magne (FRA)
106,NaN,14 July,Plain stage,181 km (112 mi),Charles Pelissier (FRA),Antonin Magne (FRA)
107,NaN,15 July,Stage with mountain(s),132 km (82 mi),Eugenio Gestri (ITA),Antonin Magne (FRA)
108,NaN,17 July,Stage with mountain(s),233 km (145 mi),Jef Demuysere (BEL),Antonin Magne (FRA)
109,NaN,18 July,Stage with mountain(s),102 km (63 mi),Charles Pelissier (FRA),Antonin Magne (FRA)
110,NaN,19 July,Stage with mountain(s),230 km (140 mi),Max Bulla (AUT),Antonin Magne (FRA)
111,NaN,20 July,Stage with mountain(s),204 km (127 mi),Jef Demuysere (BEL),Antonin Magne (FRA)
112,NaN,21 July,Stage with mountain(s),282 km (175 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
113,NaN,22 July,Stage with mountain(s),209 km (130 mi),Andre Leducq (FRA),Antonin Magne (FRA)
114,NaN,23 July,Plain stage,192 km (119 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
115,NaN,24 July,Plain stage,159 km (99 mi),Raffaele di Paco (ITA),Antonin Magne (FRA)
116,NaN,25 July,Plain stage,271 km (168 mi),Gaston Rebry (BEL),Antonin Magne (FRA)
117,NaN,26 July,Plain stage,313 km (194 mi),Charles Pelissier (FRA),Antonin Magne (FRA)

2.csv : 203_25.csv		203_44.csv		203_475.csv		204_312.csv
Missing Values(NANs):  {'phase': '0/94', 'date': '0/94', 'terrain': '0/94', 'length': '0/94', 'race winner': '0/94'}
Columns that match with input_schema:
203_25.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
203_44.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
203_475.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
204_312.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
Coverage Score :  0.8333333333333334 	 Completeness Score :  0.8333333333333334

,phase,date,terrain,length,race winner
0,P,1 July,Individual time trial,6 km (3.7 mi),Eric Vanderaerden (BEL)
1,1,2 July,Plain stage,163 km (101 mi),Frits Pirard (NED)
2,2,3 July,Team time trial,100 km (62 mi),Mercier
3,3,4 July,Hilly stage,152 km (94 mi),Rudy Matthijs (BEL)
4,4,5 July,Plain stage,300 km (190 mi),Serge Demierre (SUI)
5,5,6 July,Plain stage,257 km (160 mi),Dominique Gaigne (FRA)
6,6,7 July,Individual time trial,58 km (36 mi),Bert Oosterbosch (NED)
7,7,8 July,Plain stage,216 km (134 mi),Riccardo Magrini (ITA)
8,8,9 July,Plain stage,222 km (138 mi),Bert Oosterbosch (NED)
9,9,10 July,Plain stage,207 km (129 mi),Philippe Chevallier (FRA)
10,10,11 July,Stage with mountain(s),201 km (125 mi),Robert Millar (GBR)
11,11,12 July,Plain stage,177 km (110 mi),Regis Clere (FRA)
12,12,13 July,Plain stage,261 km (162 mi),Kim Andersen (DEN)
13,13,14 July,Hilly stage,210 km (130 mi),Henk Lubberding (NED)
14,14,15 July,Hilly stage,149 km (93 mi),Pierre Le Bigaut (FRA)
15,15,16 July,Individual time trial,16 km (9.9 mi),Ángel Arroyo (ESP)
16,16,17 July,Hilly stage,144 km (89 mi),Michel Laurent (FRA)
17,17,18 July,Stage with mountain(s),223 km (139 mi),Peter Winnen (NED)
18,18,20 July,Stage with mountain(s),247 km (153 mi),Jacques Michaud (FRA)
19,19,21 July,Individual time trial,15 km (9.3 mi),Lucien Van Impe (BEL)
20,20,22 July,Plain stage,291 km (181 mi),Philippe Leleu (FRA)
21,21,23 July,Individual time trial,50 km (31 mi),Laurent Fignon (FRA)
22,22,24 July,Plain stage,195 km (121 mi),Gilbert Glaus (SUI)
23,1,22 June,Plain stage,215 km (134 mi),Edward Sels (BEL)
24,2,23 June,Plain stage,208 km (129 mi),Andre Darrigade (FRA)
25,3A,24 June,Plain stage,197 km (122 mi),Bernard Vandekerkhove (BEL)
26,3B,24 June,Team time trial,21 km (13 mi),Kas-Kaskol
27,4,25 June,Plain stage,292 km (181 mi),Rudi Altig (GER)
28,5,26 June,Plain stage,161 km (100 mi),Willy Derboven (BEL)
29,6,27 June,Plain stage,200 km (120 mi),Henk Nijdam (NED)
...,...,...,...,...,...
64,16,19 July,Stage with mountain(s),149.0 km (92.6 mi),Cancelled
65,17,20 July,Plain stage,246.0 km (152.9 mi),Erik Zabel (GER)
66,18,21 July,Plain stage,166.5 km (103.5 mi),Lance Armstrong (USA)
67,19,22 July,Individual time trial,46.5 km (28.9 mi),Miguel Indurain (ESP)
68,20,23 July,Plain stage,155.0 km (96.3 mi),Djamolidine Abduzhaparov (UZB)
69,P,29 June,Individual time trial,5 km (3.1 mi),Jan Raas (NED)
70,1A,30 June,Plain stage,135 km (84 mi),Jan Raas (NED)
71,1B,30 June,Plain stage,100 km (62 mi),Walter Planckaert (BEL)
72,2,1 July,Plain stage,199 km (124 mi),Jacques Esclassan (FRA)
73,3,2 July,Plain stage,244 km (152 mi),Klaus-Peter Thaler (GER)
74,4,3 July,Team time trial,153 km (95 mi),TI-Raleigh
75,5,4 July,Plain stage,244 km (152 mi),Freddy Maertens (BEL)
76,6,5 July,Plain stage,162 km (101 mi),Sean Kelly (IRE)
77,7,6 July,Plain stage,242 km (150 mi),Freddy Maertens (BEL)
78,8,7 July,Individual time trial,59 km (37 mi),Bernard Hinault (FRA)
79,9,8 July,Plain stage,233 km (145 mi),Miguel Maria Lasa (ESP)
80,10,10 July,Hilly stage,192 km (119 mi),Henk Lubberding (NED)
81,11,11 July,Stage with mountain(s),161 km (100 mi),Mariano Martinez (FRA)
82,12A,12 July,Plain stage,158 km (98 mi),Cancelled
83,12B,12 July,Plain stage,96 km (60 mi),Jacques Esclassan (FRA)
84,13,13 July,Hilly stage,221 km (137 mi),Paul Wellens (BEL)
85,14,14 July,Individual time trial,52 km (32 mi),Joop Zoetemelk (NED)
86,15,15 July,Hilly stage,196 km (122 mi),Bernard Hinault (FRA)
87,16,16 July,Stage with mountain(s),241 km (150 mi),Hennie Kuiper (NED)
88,17,18 July,Stage with mountain(s),225 km (140 mi),Christian Seznec (FRA)
89,18,19 July,Plain stage,137 km (85 mi),Gerrie Knetemann (NED)
90,19,20 July,Plain stage,182 km (113 mi),Marc Demeyer (BEL)
91,20,21 July,Individual time trial,72 km (45 mi),Bernard Hinault (FRA)
92,21,22 July,Plain stage,207 km (129 mi),Jan Raas (NED)
93,22,23 July,Plain stage,162 km (101 mi),Gerrie Knetemann (NED)

3.csv : 203_25.csv		203_44.csv		203_475.csv		204_406.csv
Missing Values(NANs):  {'phase': '24/93', 'date': '0/93', 'terrain': '0/93', 'length': '0/93', 'race winner': '0/93', 'leader': '69/93'}
Columns that match with input_schema:
203_25.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
203_44.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
203_475.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
204_406.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'winner': 'race winner', 'race leader': 'leader'}
Coverage Score :  1.0 	 Completeness Score :  0.8333333333333334

,phase,date,terrain,length,race winner,leader
0,P,1 July,Individual time trial,6 km (3.7 mi),Eric Vanderaerden (BEL),NaN
1,1,2 July,Plain stage,163 km (101 mi),Frits Pirard (NED),NaN
2,2,3 July,Team time trial,100 km (62 mi),Mercier,NaN
3,3,4 July,Hilly stage,152 km (94 mi),Rudy Matthijs (BEL),NaN
4,4,5 July,Plain stage,300 km (190 mi),Serge Demierre (SUI),NaN
5,5,6 July,Plain stage,257 km (160 mi),Dominique Gaigne (FRA),NaN
6,6,7 July,Individual time trial,58 km (36 mi),Bert Oosterbosch (NED),NaN
7,7,8 July,Plain stage,216 km (134 mi),Riccardo Magrini (ITA),NaN
8,8,9 July,Plain stage,222 km (138 mi),Bert Oosterbosch (NED),NaN
9,9,10 July,Plain stage,207 km (129 mi),Philippe Chevallier (FRA),NaN
10,10,11 July,Stage with mountain(s),201 km (125 mi),Robert Millar (GBR),NaN
11,11,12 July,Plain stage,177 km (110 mi),Regis Clere (FRA),NaN
12,12,13 July,Plain stage,261 km (162 mi),Kim Andersen (DEN),NaN
13,13,14 July,Hilly stage,210 km (130 mi),Henk Lubberding (NED),NaN
14,14,15 July,Hilly stage,149 km (93 mi),Pierre Le Bigaut (FRA),NaN
15,15,16 July,Individual time trial,16 km (9.9 mi),Ángel Arroyo (ESP),NaN
16,16,17 July,Hilly stage,144 km (89 mi),Michel Laurent (FRA),NaN
17,17,18 July,Stage with mountain(s),223 km (139 mi),Peter Winnen (NED),NaN
18,18,20 July,Stage with mountain(s),247 km (153 mi),Jacques Michaud (FRA),NaN
19,19,21 July,Individual time trial,15 km (9.3 mi),Lucien Van Impe (BEL),NaN
20,20,22 July,Plain stage,291 km (181 mi),Philippe Leleu (FRA),NaN
21,21,23 July,Individual time trial,50 km (31 mi),Laurent Fignon (FRA),NaN
22,22,24 July,Plain stage,195 km (121 mi),Gilbert Glaus (SUI),NaN
23,1,22 June,Plain stage,215 km (134 mi),Edward Sels (BEL),NaN
24,2,23 June,Plain stage,208 km (129 mi),Andre Darrigade (FRA),NaN
25,3A,24 June,Plain stage,197 km (122 mi),Bernard Vandekerkhove (BEL),NaN
26,3B,24 June,Team time trial,21 km (13 mi),Kas-Kaskol,NaN
27,4,25 June,Plain stage,292 km (181 mi),Rudi Altig (GER),NaN
28,5,26 June,Plain stage,161 km (100 mi),Willy Derboven (BEL),NaN
29,6,27 June,Plain stage,200 km (120 mi),Henk Nijdam (NED),NaN
...,...,...,...,...,...,...
63,15,18 July,Stage with mountain(s),206.0 km (128.0 mi),Richard Virenque (FRA),NaN
64,16,19 July,Stage with mountain(s),149.0 km (92.6 mi),Cancelled,NaN
65,17,20 July,Plain stage,246.0 km (152.9 mi),Erik Zabel (GER),NaN
66,18,21 July,Plain stage,166.5 km (103.5 mi),Lance Armstrong (USA),NaN
67,19,22 July,Individual time trial,46.5 km (28.9 mi),Miguel Indurain (ESP),NaN
68,20,23 July,Plain stage,155.0 km (96.3 mi),Djamolidine Abduzhaparov (UZB),NaN
69,NaN,30 June,Plain stage,208 km (129 mi),Alfred Haemerlinck (BEL),Alfred Haemerlinck (BEL)
70,NaN,1 July,Plain stage,212 km (132 mi),Max Bulla (AUT),Max Bulla (AUT)
71,NaN,2 July,Plain stage,206 km (128 mi),Fabio Battesini (ITA),Leon Le Calvez (FRA)
72,NaN,3 July,Plain stage,211 km (131 mi),Andre Godinat (FRA),Rafaele di Paco (ITA)
73,NaN,4 July,Plain stage,202 km (126 mi),Charles Pelissier (FRA),Charles Pelissier (FRA) Rafaele di Paco (ITA)
74,NaN,5 July,Plain stage,338 km (210 mi),Alfred Haemerlinck (BEL),Rafaele di Paco (ITA)
75,NaN,6 July,Plain stage,180 km (110 mi),Gerard Loncke (BEL),Rafaele di Paco (ITA)
76,NaN,7 July,Plain stage,106 km (66 mi),Charles Pelissier (FRA),Charles Pelissier (FRA)
77,NaN,8 July,Stage with mountain(s),231 km (144 mi),Antonin Magne (FRA),Antonin Magne (FRA)
78,NaN,10 July,Stage with mountain(s),322 km (200 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
79,NaN,12 July,Plain stage,164 km (102 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
80,NaN,13 July,Plain stage,207 km (129 mi),Max Bulla (AUT),Antonin Magne (FRA)
81,NaN,14 July,Plain stage,181 km (112 mi),Charles Pelissier (FRA),Antonin Magne (FRA)
82,NaN,15 July,Stage with mountain(s),132 km (82 mi),Eugenio Gestri (ITA),Antonin Magne (FRA)
83,NaN,17 July,Stage with mountain(s),233 km (145 mi),Jef Demuysere (BEL),Antonin Magne (FRA)
84,NaN,18 July,Stage with mountain(s),102 km (63 mi),Charles Pelissier (FRA),Antonin Magne (FRA)
85,NaN,19 July,Stage with mountain(s),230 km (140 mi),Max Bulla (AUT),Antonin Magne (FRA)
86,NaN,20 July,Stage with mountain(s),204 km (127 mi),Jef Demuysere (BEL),Antonin Magne (FRA)
87,NaN,21 July,Stage with mountain(s),282 km (175 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
88,NaN,22 July,Stage with mountain(s),209 km (130 mi),Andre Leducq (FRA),Antonin Magne (FRA)
89,NaN,23 July,Plain stage,192 km (119 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
90,NaN,24 July,Plain stage,159 km (99 mi),Raffaele di Paco (ITA),Antonin Magne (FRA)
91,NaN,25 July,Plain stage,271 km (168 mi),Gaston Rebry (BEL),Antonin Magne (FRA)
92,NaN,26 July,Plain stage,313 km (194 mi),Charles Pelissier (FRA),Antonin Magne (FRA)

4.csv : 203_25.csv		203_44.csv		204_312.csv		204_406.csv
Missing Values(NANs):  {'phase': '24/97', 'date': '0/97', 'terrain': '0/97', 'length': '0/97', 'race winner': '0/97', 'leader': '73/97'}
Columns that match with input_schema:
203_25.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
203_44.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
204_312.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
204_406.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'winner': 'race winner', 'race leader': 'leader'}
Coverage Score :  1.0 	 Completeness Score :  0.8333333333333334

,phase,date,terrain,length,race winner,leader
0,P,1 July,Individual time trial,6 km (3.7 mi),Eric Vanderaerden (BEL),NaN
1,1,2 July,Plain stage,163 km (101 mi),Frits Pirard (NED),NaN
2,2,3 July,Team time trial,100 km (62 mi),Mercier,NaN
3,3,4 July,Hilly stage,152 km (94 mi),Rudy Matthijs (BEL),NaN
4,4,5 July,Plain stage,300 km (190 mi),Serge Demierre (SUI),NaN
5,5,6 July,Plain stage,257 km (160 mi),Dominique Gaigne (FRA),NaN
6,6,7 July,Individual time trial,58 km (36 mi),Bert Oosterbosch (NED),NaN
7,7,8 July,Plain stage,216 km (134 mi),Riccardo Magrini (ITA),NaN
8,8,9 July,Plain stage,222 km (138 mi),Bert Oosterbosch (NED),NaN
9,9,10 July,Plain stage,207 km (129 mi),Philippe Chevallier (FRA),NaN
10,10,11 July,Stage with mountain(s),201 km (125 mi),Robert Millar (GBR),NaN
11,11,12 July,Plain stage,177 km (110 mi),Regis Clere (FRA),NaN
12,12,13 July,Plain stage,261 km (162 mi),Kim Andersen (DEN),NaN
13,13,14 July,Hilly stage,210 km (130 mi),Henk Lubberding (NED),NaN
14,14,15 July,Hilly stage,149 km (93 mi),Pierre Le Bigaut (FRA),NaN
15,15,16 July,Individual time trial,16 km (9.9 mi),Ángel Arroyo (ESP),NaN
16,16,17 July,Hilly stage,144 km (89 mi),Michel Laurent (FRA),NaN
17,17,18 July,Stage with mountain(s),223 km (139 mi),Peter Winnen (NED),NaN
18,18,20 July,Stage with mountain(s),247 km (153 mi),Jacques Michaud (FRA),NaN
19,19,21 July,Individual time trial,15 km (9.3 mi),Lucien Van Impe (BEL),NaN
20,20,22 July,Plain stage,291 km (181 mi),Philippe Leleu (FRA),NaN
21,21,23 July,Individual time trial,50 km (31 mi),Laurent Fignon (FRA),NaN
22,22,24 July,Plain stage,195 km (121 mi),Gilbert Glaus (SUI),NaN
23,1,22 June,Plain stage,215 km (134 mi),Edward Sels (BEL),NaN
24,2,23 June,Plain stage,208 km (129 mi),Andre Darrigade (FRA),NaN
25,3A,24 June,Plain stage,197 km (122 mi),Bernard Vandekerkhove (BEL),NaN
26,3B,24 June,Team time trial,21 km (13 mi),Kas-Kaskol,NaN
27,4,25 June,Plain stage,292 km (181 mi),Rudi Altig (GER),NaN
28,5,26 June,Plain stage,161 km (100 mi),Willy Derboven (BEL),NaN
29,6,27 June,Plain stage,200 km (120 mi),Henk Nijdam (NED),NaN
...,...,...,...,...,...,...
67,17,18 July,Stage with mountain(s),225 km (140 mi),Christian Seznec (FRA),NaN
68,18,19 July,Plain stage,137 km (85 mi),Gerrie Knetemann (NED),NaN
69,19,20 July,Plain stage,182 km (113 mi),Marc Demeyer (BEL),NaN
70,20,21 July,Individual time trial,72 km (45 mi),Bernard Hinault (FRA),NaN
71,21,22 July,Plain stage,207 km (129 mi),Jan Raas (NED),NaN
72,22,23 July,Plain stage,162 km (101 mi),Gerrie Knetemann (NED),NaN
73,NaN,30 June,Plain stage,208 km (129 mi),Alfred Haemerlinck (BEL),Alfred Haemerlinck (BEL)
74,NaN,1 July,Plain stage,212 km (132 mi),Max Bulla (AUT),Max Bulla (AUT)
75,NaN,2 July,Plain stage,206 km (128 mi),Fabio Battesini (ITA),Leon Le Calvez (FRA)
76,NaN,3 July,Plain stage,211 km (131 mi),Andre Godinat (FRA),Rafaele di Paco (ITA)
77,NaN,4 July,Plain stage,202 km (126 mi),Charles Pelissier (FRA),Charles Pelissier (FRA) Rafaele di Paco (ITA)
78,NaN,5 July,Plain stage,338 km (210 mi),Alfred Haemerlinck (BEL),Rafaele di Paco (ITA)
79,NaN,6 July,Plain stage,180 km (110 mi),Gerard Loncke (BEL),Rafaele di Paco (ITA)
80,NaN,7 July,Plain stage,106 km (66 mi),Charles Pelissier (FRA),Charles Pelissier (FRA)
81,NaN,8 July,Stage with mountain(s),231 km (144 mi),Antonin Magne (FRA),Antonin Magne (FRA)
82,NaN,10 July,Stage with mountain(s),322 km (200 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
83,NaN,12 July,Plain stage,164 km (102 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
84,NaN,13 July,Plain stage,207 km (129 mi),Max Bulla (AUT),Antonin Magne (FRA)
85,NaN,14 July,Plain stage,181 km (112 mi),Charles Pelissier (FRA),Antonin Magne (FRA)
86,NaN,15 July,Stage with mountain(s),132 km (82 mi),Eugenio Gestri (ITA),Antonin Magne (FRA)
87,NaN,17 July,Stage with mountain(s),233 km (145 mi),Jef Demuysere (BEL),Antonin Magne (FRA)
88,NaN,18 July,Stage with mountain(s),102 km (63 mi),Charles Pelissier (FRA),Antonin Magne (FRA)
89,NaN,19 July,Stage with mountain(s),230 km (140 mi),Max Bulla (AUT),Antonin Magne (FRA)
90,NaN,20 July,Stage with mountain(s),204 km (127 mi),Jef Demuysere (BEL),Antonin Magne (FRA)
91,NaN,21 July,Stage with mountain(s),282 km (175 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
92,NaN,22 July,Stage with mountain(s),209 km (130 mi),Andre Leducq (FRA),Antonin Magne (FRA)
93,NaN,23 July,Plain stage,192 km (119 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
94,NaN,24 July,Plain stage,159 km (99 mi),Raffaele di Paco (ITA),Antonin Magne (FRA)
95,NaN,25 July,Plain stage,271 km (168 mi),Gaston Rebry (BEL),Antonin Magne (FRA)
96,NaN,26 July,Plain stage,313 km (194 mi),Charles Pelissier (FRA),Antonin Magne (FRA)

5.csv : 203_25.csv		203_475.csv		204_312.csv		204_406.csv
Missing Values(NANs):  {'phase': '24/93', 'date': '0/93', 'terrain': '0/93', 'length': '0/93', 'race winner': '0/93', 'leader': '69/93'}
Columns that match with input_schema:
203_25.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
203_475.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
204_312.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
204_406.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'winner': 'race winner', 'race leader': 'leader'}
Coverage Score :  1.0 	 Completeness Score :  0.8333333333333334

,phase,date,terrain,length,race winner,leader
0,P,1 July,Individual time trial,6 km (3.7 mi),Eric Vanderaerden (BEL),NaN
1,1,2 July,Plain stage,163 km (101 mi),Frits Pirard (NED),NaN
2,2,3 July,Team time trial,100 km (62 mi),Mercier,NaN
3,3,4 July,Hilly stage,152 km (94 mi),Rudy Matthijs (BEL),NaN
4,4,5 July,Plain stage,300 km (190 mi),Serge Demierre (SUI),NaN
5,5,6 July,Plain stage,257 km (160 mi),Dominique Gaigne (FRA),NaN
6,6,7 July,Individual time trial,58 km (36 mi),Bert Oosterbosch (NED),NaN
7,7,8 July,Plain stage,216 km (134 mi),Riccardo Magrini (ITA),NaN
8,8,9 July,Plain stage,222 km (138 mi),Bert Oosterbosch (NED),NaN
9,9,10 July,Plain stage,207 km (129 mi),Philippe Chevallier (FRA),NaN
10,10,11 July,Stage with mountain(s),201 km (125 mi),Robert Millar (GBR),NaN
11,11,12 July,Plain stage,177 km (110 mi),Regis Clere (FRA),NaN
12,12,13 July,Plain stage,261 km (162 mi),Kim Andersen (DEN),NaN
13,13,14 July,Hilly stage,210 km (130 mi),Henk Lubberding (NED),NaN
14,14,15 July,Hilly stage,149 km (93 mi),Pierre Le Bigaut (FRA),NaN
15,15,16 July,Individual time trial,16 km (9.9 mi),Ángel Arroyo (ESP),NaN
16,16,17 July,Hilly stage,144 km (89 mi),Michel Laurent (FRA),NaN
17,17,18 July,Stage with mountain(s),223 km (139 mi),Peter Winnen (NED),NaN
18,18,20 July,Stage with mountain(s),247 km (153 mi),Jacques Michaud (FRA),NaN
19,19,21 July,Individual time trial,15 km (9.3 mi),Lucien Van Impe (BEL),NaN
20,20,22 July,Plain stage,291 km (181 mi),Philippe Leleu (FRA),NaN
21,21,23 July,Individual time trial,50 km (31 mi),Laurent Fignon (FRA),NaN
22,22,24 July,Plain stage,195 km (121 mi),Gilbert Glaus (SUI),NaN
23,P,1 July,Individual time trial,7.3 km (4.5 mi),Jacky Durand (FRA),NaN
24,1,2 July,Plain stage,233.5 km (145.1 mi),Fabio Baldato (ITA),NaN
25,2,3 July,Plain stage,235.5 km (146.3 mi),Mario Cipollini (ITA),NaN
26,3,4 July,Team time trial,67.0 km (41.6 mi),Gewiss-Ballan (ITA),NaN
27,4,5 July,Plain stage,162.0 km (100.7 mi),Mario Cipollini (ITA),NaN
28,5,6 July,Plain stage,261.0 km (162.2 mi),Jeroen Blijlevens (NED),NaN
29,6,7 July,Plain stage,202.0 km (125.5 mi),Erik Zabel (GER),NaN
...,...,...,...,...,...,...
63,17,18 July,Stage with mountain(s),225 km (140 mi),Christian Seznec (FRA),NaN
64,18,19 July,Plain stage,137 km (85 mi),Gerrie Knetemann (NED),NaN
65,19,20 July,Plain stage,182 km (113 mi),Marc Demeyer (BEL),NaN
66,20,21 July,Individual time trial,72 km (45 mi),Bernard Hinault (FRA),NaN
67,21,22 July,Plain stage,207 km (129 mi),Jan Raas (NED),NaN
68,22,23 July,Plain stage,162 km (101 mi),Gerrie Knetemann (NED),NaN
69,NaN,30 June,Plain stage,208 km (129 mi),Alfred Haemerlinck (BEL),Alfred Haemerlinck (BEL)
70,NaN,1 July,Plain stage,212 km (132 mi),Max Bulla (AUT),Max Bulla (AUT)
71,NaN,2 July,Plain stage,206 km (128 mi),Fabio Battesini (ITA),Leon Le Calvez (FRA)
72,NaN,3 July,Plain stage,211 km (131 mi),Andre Godinat (FRA),Rafaele di Paco (ITA)
73,NaN,4 July,Plain stage,202 km (126 mi),Charles Pelissier (FRA),Charles Pelissier (FRA) Rafaele di Paco (ITA)
74,NaN,5 July,Plain stage,338 km (210 mi),Alfred Haemerlinck (BEL),Rafaele di Paco (ITA)
75,NaN,6 July,Plain stage,180 km (110 mi),Gerard Loncke (BEL),Rafaele di Paco (ITA)
76,NaN,7 July,Plain stage,106 km (66 mi),Charles Pelissier (FRA),Charles Pelissier (FRA)
77,NaN,8 July,Stage with mountain(s),231 km (144 mi),Antonin Magne (FRA),Antonin Magne (FRA)
78,NaN,10 July,Stage with mountain(s),322 km (200 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
79,NaN,12 July,Plain stage,164 km (102 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
80,NaN,13 July,Plain stage,207 km (129 mi),Max Bulla (AUT),Antonin Magne (FRA)
81,NaN,14 July,Plain stage,181 km (112 mi),Charles Pelissier (FRA),Antonin Magne (FRA)
82,NaN,15 July,Stage with mountain(s),132 km (82 mi),Eugenio Gestri (ITA),Antonin Magne (FRA)
83,NaN,17 July,Stage with mountain(s),233 km (145 mi),Jef Demuysere (BEL),Antonin Magne (FRA)
84,NaN,18 July,Stage with mountain(s),102 km (63 mi),Charles Pelissier (FRA),Antonin Magne (FRA)
85,NaN,19 July,Stage with mountain(s),230 km (140 mi),Max Bulla (AUT),Antonin Magne (FRA)
86,NaN,20 July,Stage with mountain(s),204 km (127 mi),Jef Demuysere (BEL),Antonin Magne (FRA)
87,NaN,21 July,Stage with mountain(s),282 km (175 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
88,NaN,22 July,Stage with mountain(s),209 km (130 mi),Andre Leducq (FRA),Antonin Magne (FRA)
89,NaN,23 July,Plain stage,192 km (119 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
90,NaN,24 July,Plain stage,159 km (99 mi),Raffaele di Paco (ITA),Antonin Magne (FRA)
91,NaN,25 July,Plain stage,271 km (168 mi),Gaston Rebry (BEL),Antonin Magne (FRA)
92,NaN,26 July,Plain stage,313 km (194 mi),Charles Pelissier (FRA),Antonin Magne (FRA)

6.csv : 203_44.csv		203_475.csv		204_312.csv		204_406.csv
Missing Values(NANs):  {'phase': '24/95', 'date': '0/95', 'terrain': '0/95', 'length': '0/95', 'race winner': '0/95', 'leader': '71/95'}
Columns that match with input_schema:
203_44.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
203_475.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
204_312.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
204_406.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'winner': 'race winner', 'race leader': 'leader'}
Coverage Score :  1.0 	 Completeness Score :  0.8333333333333334

,phase,date,terrain,length,race winner,leader
0,1,22 June,Plain stage,215 km (134 mi),Edward Sels (BEL),NaN
1,2,23 June,Plain stage,208 km (129 mi),Andre Darrigade (FRA),NaN
2,3A,24 June,Plain stage,197 km (122 mi),Bernard Vandekerkhove (BEL),NaN
3,3B,24 June,Team time trial,21 km (13 mi),Kas-Kaskol,NaN
4,4,25 June,Plain stage,292 km (181 mi),Rudi Altig (GER),NaN
5,5,26 June,Plain stage,161 km (100 mi),Willy Derboven (BEL),NaN
6,6,27 June,Plain stage,200 km (120 mi),Henk Nijdam (NED),NaN
7,7,28 June,Plain stage,195 km (121 mi),Jan Janssen (NED),NaN
8,8,29 June,Stage with mountain(s),249 km (155 mi),Federico Bahamontes (ESP),NaN
9,9,30 June,Stage with mountain(s),239 km (149 mi),Jacques Anquetil (FRA),NaN
10,10A,1 July,Plain stage,187 km (116 mi),Jan Janssen (NED),NaN
11,10B,1 July,Individual time trial,21 km (13 mi),Jacques Anquetil (FRA),NaN
12,11,2 July,Plain stage,250 km (160 mi),Edward Sels (BEL),NaN
13,12,3 July,Plain stage,174 km (108 mi),Jo de Roo (NED),NaN
14,13,4 July,Stage with mountain(s),170 km (110 mi),Julio Jimenez (ESP),NaN
15,14,6 July,Stage with mountain(s),186 km (116 mi),Edward Sels (BEL),NaN
16,15,7 July,Stage with mountain(s),203 km (126 mi),Raymond Poulidor (FRA),NaN
17,16,8 July,Stage with mountain(s),197 km (122 mi),Federico Bahamontes (ESP),NaN
18,17,9 July,Individual time trial,43 km (27 mi),Jacques Anquetil (FRA),NaN
19,18,10 July,Plain stage,187 km (116 mi),Andre Darrigade (FRA),NaN
20,19,11 July,Plain stage,215 km (134 mi),Edward Sels (BEL),NaN
21,20,12 July,Stage with mountain(s),217 km (135 mi),Julio Jimenez (ESP),NaN
22,21,13 July,Plain stage,311 km (193 mi),Jean Stablinski (FRA),NaN
23,22A,14 July,Plain stage,119 km (74 mi),Benoni Beheyt (BEL),NaN
24,22B,14 July,Individual time trial,27 km (17 mi),Jacques Anquetil (FRA),NaN
25,P,1 July,Individual time trial,7.3 km (4.5 mi),Jacky Durand (FRA),NaN
26,1,2 July,Plain stage,233.5 km (145.1 mi),Fabio Baldato (ITA),NaN
27,2,3 July,Plain stage,235.5 km (146.3 mi),Mario Cipollini (ITA),NaN
28,3,4 July,Team time trial,67.0 km (41.6 mi),Gewiss-Ballan (ITA),NaN
29,4,5 July,Plain stage,162.0 km (100.7 mi),Mario Cipollini (ITA),NaN
...,...,...,...,...,...,...
65,17,18 July,Stage with mountain(s),225 km (140 mi),Christian Seznec (FRA),NaN
66,18,19 July,Plain stage,137 km (85 mi),Gerrie Knetemann (NED),NaN
67,19,20 July,Plain stage,182 km (113 mi),Marc Demeyer (BEL),NaN
68,20,21 July,Individual time trial,72 km (45 mi),Bernard Hinault (FRA),NaN
69,21,22 July,Plain stage,207 km (129 mi),Jan Raas (NED),NaN
70,22,23 July,Plain stage,162 km (101 mi),Gerrie Knetemann (NED),NaN
71,NaN,30 June,Plain stage,208 km (129 mi),Alfred Haemerlinck (BEL),Alfred Haemerlinck (BEL)
72,NaN,1 July,Plain stage,212 km (132 mi),Max Bulla (AUT),Max Bulla (AUT)
73,NaN,2 July,Plain stage,206 km (128 mi),Fabio Battesini (ITA),Leon Le Calvez (FRA)
74,NaN,3 July,Plain stage,211 km (131 mi),Andre Godinat (FRA),Rafaele di Paco (ITA)
75,NaN,4 July,Plain stage,202 km (126 mi),Charles Pelissier (FRA),Charles Pelissier (FRA) Rafaele di Paco (ITA)
76,NaN,5 July,Plain stage,338 km (210 mi),Alfred Haemerlinck (BEL),Rafaele di Paco (ITA)
77,NaN,6 July,Plain stage,180 km (110 mi),Gerard Loncke (BEL),Rafaele di Paco (ITA)
78,NaN,7 July,Plain stage,106 km (66 mi),Charles Pelissier (FRA),Charles Pelissier (FRA)
79,NaN,8 July,Stage with mountain(s),231 km (144 mi),Antonin Magne (FRA),Antonin Magne (FRA)
80,NaN,10 July,Stage with mountain(s),322 km (200 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
81,NaN,12 July,Plain stage,164 km (102 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
82,NaN,13 July,Plain stage,207 km (129 mi),Max Bulla (AUT),Antonin Magne (FRA)
83,NaN,14 July,Plain stage,181 km (112 mi),Charles Pelissier (FRA),Antonin Magne (FRA)
84,NaN,15 July,Stage with mountain(s),132 km (82 mi),Eugenio Gestri (ITA),Antonin Magne (FRA)
85,NaN,17 July,Stage with mountain(s),233 km (145 mi),Jef Demuysere (BEL),Antonin Magne (FRA)
86,NaN,18 July,Stage with mountain(s),102 km (63 mi),Charles Pelissier (FRA),Antonin Magne (FRA)
87,NaN,19 July,Stage with mountain(s),230 km (140 mi),Max Bulla (AUT),Antonin Magne (FRA)
88,NaN,20 July,Stage with mountain(s),204 km (127 mi),Jef Demuysere (BEL),Antonin Magne (FRA)
89,NaN,21 July,Stage with mountain(s),282 km (175 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
90,NaN,22 July,Stage with mountain(s),209 km (130 mi),Andre Leducq (FRA),Antonin Magne (FRA)
91,NaN,23 July,Plain stage,192 km (119 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
92,NaN,24 July,Plain stage,159 km (99 mi),Raffaele di Paco (ITA),Antonin Magne (FRA)
93,NaN,25 July,Plain stage,271 km (168 mi),Gaston Rebry (BEL),Antonin Magne (FRA)
94,NaN,26 July,Plain stage,313 km (194 mi),Charles Pelissier (FRA),Antonin Magne (FRA)

7.csv : 203_25.csv		203_44.csv		203_475.csv
Missing Values(NANs):  {'phase': '0/69', 'date': '0/69', 'terrain': '0/69', 'length': '0/69', 'race winner': '0/69'}
Columns that match with input_schema:
203_25.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
203_44.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
203_475.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
Coverage Score :  0.8333333333333334 	 Completeness Score :  0.8333333333333334

,phase,date,terrain,length,race winner
0,P,1 July,Individual time trial,6 km (3.7 mi),Eric Vanderaerden (BEL)
1,1,2 July,Plain stage,163 km (101 mi),Frits Pirard (NED)
2,2,3 July,Team time trial,100 km (62 mi),Mercier
3,3,4 July,Hilly stage,152 km (94 mi),Rudy Matthijs (BEL)
4,4,5 July,Plain stage,300 km (190 mi),Serge Demierre (SUI)
5,5,6 July,Plain stage,257 km (160 mi),Dominique Gaigne (FRA)
6,6,7 July,Individual time trial,58 km (36 mi),Bert Oosterbosch (NED)
7,7,8 July,Plain stage,216 km (134 mi),Riccardo Magrini (ITA)
8,8,9 July,Plain stage,222 km (138 mi),Bert Oosterbosch (NED)
9,9,10 July,Plain stage,207 km (129 mi),Philippe Chevallier (FRA)
10,10,11 July,Stage with mountain(s),201 km (125 mi),Robert Millar (GBR)
11,11,12 July,Plain stage,177 km (110 mi),Regis Clere (FRA)
12,12,13 July,Plain stage,261 km (162 mi),Kim Andersen (DEN)
13,13,14 July,Hilly stage,210 km (130 mi),Henk Lubberding (NED)
14,14,15 July,Hilly stage,149 km (93 mi),Pierre Le Bigaut (FRA)
15,15,16 July,Individual time trial,16 km (9.9 mi),Ángel Arroyo (ESP)
16,16,17 July,Hilly stage,144 km (89 mi),Michel Laurent (FRA)
17,17,18 July,Stage with mountain(s),223 km (139 mi),Peter Winnen (NED)
18,18,20 July,Stage with mountain(s),247 km (153 mi),Jacques Michaud (FRA)
19,19,21 July,Individual time trial,15 km (9.3 mi),Lucien Van Impe (BEL)
20,20,22 July,Plain stage,291 km (181 mi),Philippe Leleu (FRA)
21,21,23 July,Individual time trial,50 km (31 mi),Laurent Fignon (FRA)
22,22,24 July,Plain stage,195 km (121 mi),Gilbert Glaus (SUI)
23,1,22 June,Plain stage,215 km (134 mi),Edward Sels (BEL)
24,2,23 June,Plain stage,208 km (129 mi),Andre Darrigade (FRA)
25,3A,24 June,Plain stage,197 km (122 mi),Bernard Vandekerkhove (BEL)
26,3B,24 June,Team time trial,21 km (13 mi),Kas-Kaskol
27,4,25 June,Plain stage,292 km (181 mi),Rudi Altig (GER)
28,5,26 June,Plain stage,161 km (100 mi),Willy Derboven (BEL)
29,6,27 June,Plain stage,200 km (120 mi),Henk Nijdam (NED)
...,...,...,...,...,...
39,15,7 July,Stage with mountain(s),203 km (126 mi),Raymond Poulidor (FRA)
40,16,8 July,Stage with mountain(s),197 km (122 mi),Federico Bahamontes (ESP)
41,17,9 July,Individual time trial,43 km (27 mi),Jacques Anquetil (FRA)
42,18,10 July,Plain stage,187 km (116 mi),Andre Darrigade (FRA)
43,19,11 July,Plain stage,215 km (134 mi),Edward Sels (BEL)
44,20,12 July,Stage with mountain(s),217 km (135 mi),Julio Jimenez (ESP)
45,21,13 July,Plain stage,311 km (193 mi),Jean Stablinski (FRA)
46,22A,14 July,Plain stage,119 km (74 mi),Benoni Beheyt (BEL)
47,22B,14 July,Individual time trial,27 km (17 mi),Jacques Anquetil (FRA)
48,P,1 July,Individual time trial,7.3 km (4.5 mi),Jacky Durand (FRA)
49,1,2 July,Plain stage,233.5 km (145.1 mi),Fabio Baldato (ITA)
50,2,3 July,Plain stage,235.5 km (146.3 mi),Mario Cipollini (ITA)
51,3,4 July,Team time trial,67.0 km (41.6 mi),Gewiss-Ballan (ITA)
52,4,5 July,Plain stage,162.0 km (100.7 mi),Mario Cipollini (ITA)
53,5,6 July,Plain stage,261.0 km (162.2 mi),Jeroen Blijlevens (NED)
54,6,7 July,Plain stage,202.0 km (125.5 mi),Erik Zabel (GER)
55,7,8 July,Hilly stage,203.0 km (126.1 mi),Johan Bruyneel (BEL)
56,8,9 July,Individual time trial,54.0 km (33.6 mi),Miguel Indurain (ESP)
57,9,11 July,Stage with mountain(s),160.0 km (99.4 mi),Alex Zulle (SUI)
58,10,12 July,Stage with mountain(s),162.5 km (101.0 mi),Marco Pantani (ITA)
59,11,13 July,Hilly stage,199.0 km (123.7 mi),Maximilian Sciandri (GBR)
60,12,14 July,Hilly stage,222.5 km (138.3 mi),Laurent Jalabert (FRA)
61,13,15 July,Plain stage,245.0 km (152.2 mi),Serhiy Utchakov (UKR)
62,14,16 July,Stage with mountain(s),164.0 km (101.9 mi),Marco Pantani (ITA)
63,15,18 July,Stage with mountain(s),206.0 km (128.0 mi),Richard Virenque (FRA)
64,16,19 July,Stage with mountain(s),149.0 km (92.6 mi),Cancelled
65,17,20 July,Plain stage,246.0 km (152.9 mi),Erik Zabel (GER)
66,18,21 July,Plain stage,166.5 km (103.5 mi),Lance Armstrong (USA)
67,19,22 July,Individual time trial,46.5 km (28.9 mi),Miguel Indurain (ESP)
68,20,23 July,Plain stage,155.0 km (96.3 mi),Djamolidine Abduzhaparov (UZB)

8.csv : 203_25.csv		203_44.csv		204_312.csv
Missing Values(NANs):  {'phase': '0/73', 'date': '0/73', 'terrain': '0/73', 'length': '0/73', 'race winner': '0/73'}
Columns that match with input_schema:
203_25.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
203_44.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
204_312.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
Coverage Score :  0.8333333333333334 	 Completeness Score :  0.8333333333333334

,phase,date,terrain,length,race winner
0,P,1 July,Individual time trial,6 km (3.7 mi),Eric Vanderaerden (BEL)
1,1,2 July,Plain stage,163 km (101 mi),Frits Pirard (NED)
2,2,3 July,Team time trial,100 km (62 mi),Mercier
3,3,4 July,Hilly stage,152 km (94 mi),Rudy Matthijs (BEL)
4,4,5 July,Plain stage,300 km (190 mi),Serge Demierre (SUI)
5,5,6 July,Plain stage,257 km (160 mi),Dominique Gaigne (FRA)
6,6,7 July,Individual time trial,58 km (36 mi),Bert Oosterbosch (NED)
7,7,8 July,Plain stage,216 km (134 mi),Riccardo Magrini (ITA)
8,8,9 July,Plain stage,222 km (138 mi),Bert Oosterbosch (NED)
9,9,10 July,Plain stage,207 km (129 mi),Philippe Chevallier (FRA)
10,10,11 July,Stage with mountain(s),201 km (125 mi),Robert Millar (GBR)
11,11,12 July,Plain stage,177 km (110 mi),Regis Clere (FRA)
12,12,13 July,Plain stage,261 km (162 mi),Kim Andersen (DEN)
13,13,14 July,Hilly stage,210 km (130 mi),Henk Lubberding (NED)
14,14,15 July,Hilly stage,149 km (93 mi),Pierre Le Bigaut (FRA)
15,15,16 July,Individual time trial,16 km (9.9 mi),Ángel Arroyo (ESP)
16,16,17 July,Hilly stage,144 km (89 mi),Michel Laurent (FRA)
17,17,18 July,Stage with mountain(s),223 km (139 mi),Peter Winnen (NED)
18,18,20 July,Stage with mountain(s),247 km (153 mi),Jacques Michaud (FRA)
19,19,21 July,Individual time trial,15 km (9.3 mi),Lucien Van Impe (BEL)
20,20,22 July,Plain stage,291 km (181 mi),Philippe Leleu (FRA)
21,21,23 July,Individual time trial,50 km (31 mi),Laurent Fignon (FRA)
22,22,24 July,Plain stage,195 km (121 mi),Gilbert Glaus (SUI)
23,1,22 June,Plain stage,215 km (134 mi),Edward Sels (BEL)
24,2,23 June,Plain stage,208 km (129 mi),Andre Darrigade (FRA)
25,3A,24 June,Plain stage,197 km (122 mi),Bernard Vandekerkhove (BEL)
26,3B,24 June,Team time trial,21 km (13 mi),Kas-Kaskol
27,4,25 June,Plain stage,292 km (181 mi),Rudi Altig (GER)
28,5,26 June,Plain stage,161 km (100 mi),Willy Derboven (BEL)
29,6,27 June,Plain stage,200 km (120 mi),Henk Nijdam (NED)
...,...,...,...,...,...
43,19,11 July,Plain stage,215 km (134 mi),Edward Sels (BEL)
44,20,12 July,Stage with mountain(s),217 km (135 mi),Julio Jimenez (ESP)
45,21,13 July,Plain stage,311 km (193 mi),Jean Stablinski (FRA)
46,22A,14 July,Plain stage,119 km (74 mi),Benoni Beheyt (BEL)
47,22B,14 July,Individual time trial,27 km (17 mi),Jacques Anquetil (FRA)
48,P,29 June,Individual time trial,5 km (3.1 mi),Jan Raas (NED)
49,1A,30 June,Plain stage,135 km (84 mi),Jan Raas (NED)
50,1B,30 June,Plain stage,100 km (62 mi),Walter Planckaert (BEL)
51,2,1 July,Plain stage,199 km (124 mi),Jacques Esclassan (FRA)
52,3,2 July,Plain stage,244 km (152 mi),Klaus-Peter Thaler (GER)
53,4,3 July,Team time trial,153 km (95 mi),TI-Raleigh
54,5,4 July,Plain stage,244 km (152 mi),Freddy Maertens (BEL)
55,6,5 July,Plain stage,162 km (101 mi),Sean Kelly (IRE)
56,7,6 July,Plain stage,242 km (150 mi),Freddy Maertens (BEL)
57,8,7 July,Individual time trial,59 km (37 mi),Bernard Hinault (FRA)
58,9,8 July,Plain stage,233 km (145 mi),Miguel Maria Lasa (ESP)
59,10,10 July,Hilly stage,192 km (119 mi),Henk Lubberding (NED)
60,11,11 July,Stage with mountain(s),161 km (100 mi),Mariano Martinez (FRA)
61,12A,12 July,Plain stage,158 km (98 mi),Cancelled
62,12B,12 July,Plain stage,96 km (60 mi),Jacques Esclassan (FRA)
63,13,13 July,Hilly stage,221 km (137 mi),Paul Wellens (BEL)
64,14,14 July,Individual time trial,52 km (32 mi),Joop Zoetemelk (NED)
65,15,15 July,Hilly stage,196 km (122 mi),Bernard Hinault (FRA)
66,16,16 July,Stage with mountain(s),241 km (150 mi),Hennie Kuiper (NED)
67,17,18 July,Stage with mountain(s),225 km (140 mi),Christian Seznec (FRA)
68,18,19 July,Plain stage,137 km (85 mi),Gerrie Knetemann (NED)
69,19,20 July,Plain stage,182 km (113 mi),Marc Demeyer (BEL)
70,20,21 July,Individual time trial,72 km (45 mi),Bernard Hinault (FRA)
71,21,22 July,Plain stage,207 km (129 mi),Jan Raas (NED)
72,22,23 July,Plain stage,162 km (101 mi),Gerrie Knetemann (NED)

9.csv : 203_25.csv		203_44.csv		204_406.csv
Missing Values(NANs):  {'phase': '24/72', 'date': '0/72', 'terrain': '0/72', 'length': '0/72', 'race winner': '0/72', 'leader': '48/72'}
Columns that match with input_schema:
203_25.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
203_44.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
204_406.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'winner': 'race winner', 'race leader': 'leader'}
Coverage Score :  1.0 	 Completeness Score :  0.8333333333333331

,phase,date,terrain,length,race winner,leader
0,P,1 July,Individual time trial,6 km (3.7 mi),Eric Vanderaerden (BEL),NaN
1,1,2 July,Plain stage,163 km (101 mi),Frits Pirard (NED),NaN
2,2,3 July,Team time trial,100 km (62 mi),Mercier,NaN
3,3,4 July,Hilly stage,152 km (94 mi),Rudy Matthijs (BEL),NaN
4,4,5 July,Plain stage,300 km (190 mi),Serge Demierre (SUI),NaN
5,5,6 July,Plain stage,257 km (160 mi),Dominique Gaigne (FRA),NaN
6,6,7 July,Individual time trial,58 km (36 mi),Bert Oosterbosch (NED),NaN
7,7,8 July,Plain stage,216 km (134 mi),Riccardo Magrini (ITA),NaN
8,8,9 July,Plain stage,222 km (138 mi),Bert Oosterbosch (NED),NaN
9,9,10 July,Plain stage,207 km (129 mi),Philippe Chevallier (FRA),NaN
10,10,11 July,Stage with mountain(s),201 km (125 mi),Robert Millar (GBR),NaN
11,11,12 July,Plain stage,177 km (110 mi),Regis Clere (FRA),NaN
12,12,13 July,Plain stage,261 km (162 mi),Kim Andersen (DEN),NaN
13,13,14 July,Hilly stage,210 km (130 mi),Henk Lubberding (NED),NaN
14,14,15 July,Hilly stage,149 km (93 mi),Pierre Le Bigaut (FRA),NaN
15,15,16 July,Individual time trial,16 km (9.9 mi),Ángel Arroyo (ESP),NaN
16,16,17 July,Hilly stage,144 km (89 mi),Michel Laurent (FRA),NaN
17,17,18 July,Stage with mountain(s),223 km (139 mi),Peter Winnen (NED),NaN
18,18,20 July,Stage with mountain(s),247 km (153 mi),Jacques Michaud (FRA),NaN
19,19,21 July,Individual time trial,15 km (9.3 mi),Lucien Van Impe (BEL),NaN
20,20,22 July,Plain stage,291 km (181 mi),Philippe Leleu (FRA),NaN
21,21,23 July,Individual time trial,50 km (31 mi),Laurent Fignon (FRA),NaN
22,22,24 July,Plain stage,195 km (121 mi),Gilbert Glaus (SUI),NaN
23,1,22 June,Plain stage,215 km (134 mi),Edward Sels (BEL),NaN
24,2,23 June,Plain stage,208 km (129 mi),Andre Darrigade (FRA),NaN
25,3A,24 June,Plain stage,197 km (122 mi),Bernard Vandekerkhove (BEL),NaN
26,3B,24 June,Team time trial,21 km (13 mi),Kas-Kaskol,NaN
27,4,25 June,Plain stage,292 km (181 mi),Rudi Altig (GER),NaN
28,5,26 June,Plain stage,161 km (100 mi),Willy Derboven (BEL),NaN
29,6,27 June,Plain stage,200 km (120 mi),Henk Nijdam (NED),NaN
...,...,...,...,...,...,...
42,18,10 July,Plain stage,187 km (116 mi),Andre Darrigade (FRA),NaN
43,19,11 July,Plain stage,215 km (134 mi),Edward Sels (BEL),NaN
44,20,12 July,Stage with mountain(s),217 km (135 mi),Julio Jimenez (ESP),NaN
45,21,13 July,Plain stage,311 km (193 mi),Jean Stablinski (FRA),NaN
46,22A,14 July,Plain stage,119 km (74 mi),Benoni Beheyt (BEL),NaN
47,22B,14 July,Individual time trial,27 km (17 mi),Jacques Anquetil (FRA),NaN
48,NaN,30 June,Plain stage,208 km (129 mi),Alfred Haemerlinck (BEL),Alfred Haemerlinck (BEL)
49,NaN,1 July,Plain stage,212 km (132 mi),Max Bulla (AUT),Max Bulla (AUT)
50,NaN,2 July,Plain stage,206 km (128 mi),Fabio Battesini (ITA),Leon Le Calvez (FRA)
51,NaN,3 July,Plain stage,211 km (131 mi),Andre Godinat (FRA),Rafaele di Paco (ITA)
52,NaN,4 July,Plain stage,202 km (126 mi),Charles Pelissier (FRA),Charles Pelissier (FRA) Rafaele di Paco (ITA)
53,NaN,5 July,Plain stage,338 km (210 mi),Alfred Haemerlinck (BEL),Rafaele di Paco (ITA)
54,NaN,6 July,Plain stage,180 km (110 mi),Gerard Loncke (BEL),Rafaele di Paco (ITA)
55,NaN,7 July,Plain stage,106 km (66 mi),Charles Pelissier (FRA),Charles Pelissier (FRA)
56,NaN,8 July,Stage with mountain(s),231 km (144 mi),Antonin Magne (FRA),Antonin Magne (FRA)
57,NaN,10 July,Stage with mountain(s),322 km (200 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
58,NaN,12 July,Plain stage,164 km (102 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
59,NaN,13 July,Plain stage,207 km (129 mi),Max Bulla (AUT),Antonin Magne (FRA)
60,NaN,14 July,Plain stage,181 km (112 mi),Charles Pelissier (FRA),Antonin Magne (FRA)
61,NaN,15 July,Stage with mountain(s),132 km (82 mi),Eugenio Gestri (ITA),Antonin Magne (FRA)
62,NaN,17 July,Stage with mountain(s),233 km (145 mi),Jef Demuysere (BEL),Antonin Magne (FRA)
63,NaN,18 July,Stage with mountain(s),102 km (63 mi),Charles Pelissier (FRA),Antonin Magne (FRA)
64,NaN,19 July,Stage with mountain(s),230 km (140 mi),Max Bulla (AUT),Antonin Magne (FRA)
65,NaN,20 July,Stage with mountain(s),204 km (127 mi),Jef Demuysere (BEL),Antonin Magne (FRA)
66,NaN,21 July,Stage with mountain(s),282 km (175 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
67,NaN,22 July,Stage with mountain(s),209 km (130 mi),Andre Leducq (FRA),Antonin Magne (FRA)
68,NaN,23 July,Plain stage,192 km (119 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
69,NaN,24 July,Plain stage,159 km (99 mi),Raffaele di Paco (ITA),Antonin Magne (FRA)
70,NaN,25 July,Plain stage,271 km (168 mi),Gaston Rebry (BEL),Antonin Magne (FRA)
71,NaN,26 July,Plain stage,313 km (194 mi),Charles Pelissier (FRA),Antonin Magne (FRA)

10.csv : 203_25.csv		203_475.csv		204_312.csv
Missing Values(NANs):  {'phase': '0/69', 'date': '0/69', 'terrain': '0/69', 'length': '0/69', 'race winner': '0/69'}
Columns that match with input_schema:
203_25.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
203_475.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
204_312.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
Coverage Score :  0.8333333333333334 	 Completeness Score :  0.8333333333333334

,phase,date,terrain,length,race winner
0,P,1 July,Individual time trial,6 km (3.7 mi),Eric Vanderaerden (BEL)
1,1,2 July,Plain stage,163 km (101 mi),Frits Pirard (NED)
2,2,3 July,Team time trial,100 km (62 mi),Mercier
3,3,4 July,Hilly stage,152 km (94 mi),Rudy Matthijs (BEL)
4,4,5 July,Plain stage,300 km (190 mi),Serge Demierre (SUI)
5,5,6 July,Plain stage,257 km (160 mi),Dominique Gaigne (FRA)
6,6,7 July,Individual time trial,58 km (36 mi),Bert Oosterbosch (NED)
7,7,8 July,Plain stage,216 km (134 mi),Riccardo Magrini (ITA)
8,8,9 July,Plain stage,222 km (138 mi),Bert Oosterbosch (NED)
9,9,10 July,Plain stage,207 km (129 mi),Philippe Chevallier (FRA)
10,10,11 July,Stage with mountain(s),201 km (125 mi),Robert Millar (GBR)
11,11,12 July,Plain stage,177 km (110 mi),Regis Clere (FRA)
12,12,13 July,Plain stage,261 km (162 mi),Kim Andersen (DEN)
13,13,14 July,Hilly stage,210 km (130 mi),Henk Lubberding (NED)
14,14,15 July,Hilly stage,149 km (93 mi),Pierre Le Bigaut (FRA)
15,15,16 July,Individual time trial,16 km (9.9 mi),Ángel Arroyo (ESP)
16,16,17 July,Hilly stage,144 km (89 mi),Michel Laurent (FRA)
17,17,18 July,Stage with mountain(s),223 km (139 mi),Peter Winnen (NED)
18,18,20 July,Stage with mountain(s),247 km (153 mi),Jacques Michaud (FRA)
19,19,21 July,Individual time trial,15 km (9.3 mi),Lucien Van Impe (BEL)
20,20,22 July,Plain stage,291 km (181 mi),Philippe Leleu (FRA)
21,21,23 July,Individual time trial,50 km (31 mi),Laurent Fignon (FRA)
22,22,24 July,Plain stage,195 km (121 mi),Gilbert Glaus (SUI)
23,P,1 July,Individual time trial,7.3 km (4.5 mi),Jacky Durand (FRA)
24,1,2 July,Plain stage,233.5 km (145.1 mi),Fabio Baldato (ITA)
25,2,3 July,Plain stage,235.5 km (146.3 mi),Mario Cipollini (ITA)
26,3,4 July,Team time trial,67.0 km (41.6 mi),Gewiss-Ballan (ITA)
27,4,5 July,Plain stage,162.0 km (100.7 mi),Mario Cipollini (ITA)
28,5,6 July,Plain stage,261.0 km (162.2 mi),Jeroen Blijlevens (NED)
29,6,7 July,Plain stage,202.0 km (125.5 mi),Erik Zabel (GER)
...,...,...,...,...,...
39,16,19 July,Stage with mountain(s),149.0 km (92.6 mi),Cancelled
40,17,20 July,Plain stage,246.0 km (152.9 mi),Erik Zabel (GER)
41,18,21 July,Plain stage,166.5 km (103.5 mi),Lance Armstrong (USA)
42,19,22 July,Individual time trial,46.5 km (28.9 mi),Miguel Indurain (ESP)
43,20,23 July,Plain stage,155.0 km (96.3 mi),Djamolidine Abduzhaparov (UZB)
44,P,29 June,Individual time trial,5 km (3.1 mi),Jan Raas (NED)
45,1A,30 June,Plain stage,135 km (84 mi),Jan Raas (NED)
46,1B,30 June,Plain stage,100 km (62 mi),Walter Planckaert (BEL)
47,2,1 July,Plain stage,199 km (124 mi),Jacques Esclassan (FRA)
48,3,2 July,Plain stage,244 km (152 mi),Klaus-Peter Thaler (GER)
49,4,3 July,Team time trial,153 km (95 mi),TI-Raleigh
50,5,4 July,Plain stage,244 km (152 mi),Freddy Maertens (BEL)
51,6,5 July,Plain stage,162 km (101 mi),Sean Kelly (IRE)
52,7,6 July,Plain stage,242 km (150 mi),Freddy Maertens (BEL)
53,8,7 July,Individual time trial,59 km (37 mi),Bernard Hinault (FRA)
54,9,8 July,Plain stage,233 km (145 mi),Miguel Maria Lasa (ESP)
55,10,10 July,Hilly stage,192 km (119 mi),Henk Lubberding (NED)
56,11,11 July,Stage with mountain(s),161 km (100 mi),Mariano Martinez (FRA)
57,12A,12 July,Plain stage,158 km (98 mi),Cancelled
58,12B,12 July,Plain stage,96 km (60 mi),Jacques Esclassan (FRA)
59,13,13 July,Hilly stage,221 km (137 mi),Paul Wellens (BEL)
60,14,14 July,Individual time trial,52 km (32 mi),Joop Zoetemelk (NED)
61,15,15 July,Hilly stage,196 km (122 mi),Bernard Hinault (FRA)
62,16,16 July,Stage with mountain(s),241 km (150 mi),Hennie Kuiper (NED)
63,17,18 July,Stage with mountain(s),225 km (140 mi),Christian Seznec (FRA)
64,18,19 July,Plain stage,137 km (85 mi),Gerrie Knetemann (NED)
65,19,20 July,Plain stage,182 km (113 mi),Marc Demeyer (BEL)
66,20,21 July,Individual time trial,72 km (45 mi),Bernard Hinault (FRA)
67,21,22 July,Plain stage,207 km (129 mi),Jan Raas (NED)
68,22,23 July,Plain stage,162 km (101 mi),Gerrie Knetemann (NED)

11.csv : 203_25.csv		203_475.csv		204_406.csv
Missing Values(NANs):  {'phase': '24/68', 'date': '0/68', 'terrain': '0/68', 'length': '0/68', 'race winner': '0/68', 'leader': '44/68'}
Columns that match with input_schema:
203_25.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
203_475.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
204_406.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'winner': 'race winner', 'race leader': 'leader'}
Coverage Score :  1.0 	 Completeness Score :  0.8333333333333331

,phase,date,terrain,length,race winner,leader
0,P,1 July,Individual time trial,6 km (3.7 mi),Eric Vanderaerden (BEL),NaN
1,1,2 July,Plain stage,163 km (101 mi),Frits Pirard (NED),NaN
2,2,3 July,Team time trial,100 km (62 mi),Mercier,NaN
3,3,4 July,Hilly stage,152 km (94 mi),Rudy Matthijs (BEL),NaN
4,4,5 July,Plain stage,300 km (190 mi),Serge Demierre (SUI),NaN
5,5,6 July,Plain stage,257 km (160 mi),Dominique Gaigne (FRA),NaN
6,6,7 July,Individual time trial,58 km (36 mi),Bert Oosterbosch (NED),NaN
7,7,8 July,Plain stage,216 km (134 mi),Riccardo Magrini (ITA),NaN
8,8,9 July,Plain stage,222 km (138 mi),Bert Oosterbosch (NED),NaN
9,9,10 July,Plain stage,207 km (129 mi),Philippe Chevallier (FRA),NaN
10,10,11 July,Stage with mountain(s),201 km (125 mi),Robert Millar (GBR),NaN
11,11,12 July,Plain stage,177 km (110 mi),Regis Clere (FRA),NaN
12,12,13 July,Plain stage,261 km (162 mi),Kim Andersen (DEN),NaN
13,13,14 July,Hilly stage,210 km (130 mi),Henk Lubberding (NED),NaN
14,14,15 July,Hilly stage,149 km (93 mi),Pierre Le Bigaut (FRA),NaN
15,15,16 July,Individual time trial,16 km (9.9 mi),Ángel Arroyo (ESP),NaN
16,16,17 July,Hilly stage,144 km (89 mi),Michel Laurent (FRA),NaN
17,17,18 July,Stage with mountain(s),223 km (139 mi),Peter Winnen (NED),NaN
18,18,20 July,Stage with mountain(s),247 km (153 mi),Jacques Michaud (FRA),NaN
19,19,21 July,Individual time trial,15 km (9.3 mi),Lucien Van Impe (BEL),NaN
20,20,22 July,Plain stage,291 km (181 mi),Philippe Leleu (FRA),NaN
21,21,23 July,Individual time trial,50 km (31 mi),Laurent Fignon (FRA),NaN
22,22,24 July,Plain stage,195 km (121 mi),Gilbert Glaus (SUI),NaN
23,P,1 July,Individual time trial,7.3 km (4.5 mi),Jacky Durand (FRA),NaN
24,1,2 July,Plain stage,233.5 km (145.1 mi),Fabio Baldato (ITA),NaN
25,2,3 July,Plain stage,235.5 km (146.3 mi),Mario Cipollini (ITA),NaN
26,3,4 July,Team time trial,67.0 km (41.6 mi),Gewiss-Ballan (ITA),NaN
27,4,5 July,Plain stage,162.0 km (100.7 mi),Mario Cipollini (ITA),NaN
28,5,6 July,Plain stage,261.0 km (162.2 mi),Jeroen Blijlevens (NED),NaN
29,6,7 July,Plain stage,202.0 km (125.5 mi),Erik Zabel (GER),NaN
...,...,...,...,...,...,...
38,15,18 July,Stage with mountain(s),206.0 km (128.0 mi),Richard Virenque (FRA),NaN
39,16,19 July,Stage with mountain(s),149.0 km (92.6 mi),Cancelled,NaN
40,17,20 July,Plain stage,246.0 km (152.9 mi),Erik Zabel (GER),NaN
41,18,21 July,Plain stage,166.5 km (103.5 mi),Lance Armstrong (USA),NaN
42,19,22 July,Individual time trial,46.5 km (28.9 mi),Miguel Indurain (ESP),NaN
43,20,23 July,Plain stage,155.0 km (96.3 mi),Djamolidine Abduzhaparov (UZB),NaN
44,NaN,30 June,Plain stage,208 km (129 mi),Alfred Haemerlinck (BEL),Alfred Haemerlinck (BEL)
45,NaN,1 July,Plain stage,212 km (132 mi),Max Bulla (AUT),Max Bulla (AUT)
46,NaN,2 July,Plain stage,206 km (128 mi),Fabio Battesini (ITA),Leon Le Calvez (FRA)
47,NaN,3 July,Plain stage,211 km (131 mi),Andre Godinat (FRA),Rafaele di Paco (ITA)
48,NaN,4 July,Plain stage,202 km (126 mi),Charles Pelissier (FRA),Charles Pelissier (FRA) Rafaele di Paco (ITA)
49,NaN,5 July,Plain stage,338 km (210 mi),Alfred Haemerlinck (BEL),Rafaele di Paco (ITA)
50,NaN,6 July,Plain stage,180 km (110 mi),Gerard Loncke (BEL),Rafaele di Paco (ITA)
51,NaN,7 July,Plain stage,106 km (66 mi),Charles Pelissier (FRA),Charles Pelissier (FRA)
52,NaN,8 July,Stage with mountain(s),231 km (144 mi),Antonin Magne (FRA),Antonin Magne (FRA)
53,NaN,10 July,Stage with mountain(s),322 km (200 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
54,NaN,12 July,Plain stage,164 km (102 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
55,NaN,13 July,Plain stage,207 km (129 mi),Max Bulla (AUT),Antonin Magne (FRA)
56,NaN,14 July,Plain stage,181 km (112 mi),Charles Pelissier (FRA),Antonin Magne (FRA)
57,NaN,15 July,Stage with mountain(s),132 km (82 mi),Eugenio Gestri (ITA),Antonin Magne (FRA)
58,NaN,17 July,Stage with mountain(s),233 km (145 mi),Jef Demuysere (BEL),Antonin Magne (FRA)
59,NaN,18 July,Stage with mountain(s),102 km (63 mi),Charles Pelissier (FRA),Antonin Magne (FRA)
60,NaN,19 July,Stage with mountain(s),230 km (140 mi),Max Bulla (AUT),Antonin Magne (FRA)
61,NaN,20 July,Stage with mountain(s),204 km (127 mi),Jef Demuysere (BEL),Antonin Magne (FRA)
62,NaN,21 July,Stage with mountain(s),282 km (175 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
63,NaN,22 July,Stage with mountain(s),209 km (130 mi),Andre Leducq (FRA),Antonin Magne (FRA)
64,NaN,23 July,Plain stage,192 km (119 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
65,NaN,24 July,Plain stage,159 km (99 mi),Raffaele di Paco (ITA),Antonin Magne (FRA)
66,NaN,25 July,Plain stage,271 km (168 mi),Gaston Rebry (BEL),Antonin Magne (FRA)
67,NaN,26 July,Plain stage,313 km (194 mi),Charles Pelissier (FRA),Antonin Magne (FRA)

12.csv : 203_25.csv		204_312.csv		204_406.csv
Missing Values(NANs):  {'phase': '24/72', 'date': '0/72', 'terrain': '0/72', 'length': '0/72', 'race winner': '0/72', 'leader': '48/72'}
Columns that match with input_schema:
203_25.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
204_312.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
204_406.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'winner': 'race winner', 'race leader': 'leader'}
Coverage Score :  1.0 	 Completeness Score :  0.8333333333333331

,phase,date,terrain,length,race winner,leader
0,P,1 July,Individual time trial,6 km (3.7 mi),Eric Vanderaerden (BEL),NaN
1,1,2 July,Plain stage,163 km (101 mi),Frits Pirard (NED),NaN
2,2,3 July,Team time trial,100 km (62 mi),Mercier,NaN
3,3,4 July,Hilly stage,152 km (94 mi),Rudy Matthijs (BEL),NaN
4,4,5 July,Plain stage,300 km (190 mi),Serge Demierre (SUI),NaN
5,5,6 July,Plain stage,257 km (160 mi),Dominique Gaigne (FRA),NaN
6,6,7 July,Individual time trial,58 km (36 mi),Bert Oosterbosch (NED),NaN
7,7,8 July,Plain stage,216 km (134 mi),Riccardo Magrini (ITA),NaN
8,8,9 July,Plain stage,222 km (138 mi),Bert Oosterbosch (NED),NaN
9,9,10 July,Plain stage,207 km (129 mi),Philippe Chevallier (FRA),NaN
10,10,11 July,Stage with mountain(s),201 km (125 mi),Robert Millar (GBR),NaN
11,11,12 July,Plain stage,177 km (110 mi),Regis Clere (FRA),NaN
12,12,13 July,Plain stage,261 km (162 mi),Kim Andersen (DEN),NaN
13,13,14 July,Hilly stage,210 km (130 mi),Henk Lubberding (NED),NaN
14,14,15 July,Hilly stage,149 km (93 mi),Pierre Le Bigaut (FRA),NaN
15,15,16 July,Individual time trial,16 km (9.9 mi),Ángel Arroyo (ESP),NaN
16,16,17 July,Hilly stage,144 km (89 mi),Michel Laurent (FRA),NaN
17,17,18 July,Stage with mountain(s),223 km (139 mi),Peter Winnen (NED),NaN
18,18,20 July,Stage with mountain(s),247 km (153 mi),Jacques Michaud (FRA),NaN
19,19,21 July,Individual time trial,15 km (9.3 mi),Lucien Van Impe (BEL),NaN
20,20,22 July,Plain stage,291 km (181 mi),Philippe Leleu (FRA),NaN
21,21,23 July,Individual time trial,50 km (31 mi),Laurent Fignon (FRA),NaN
22,22,24 July,Plain stage,195 km (121 mi),Gilbert Glaus (SUI),NaN
23,P,29 June,Individual time trial,5 km (3.1 mi),Jan Raas (NED),NaN
24,1A,30 June,Plain stage,135 km (84 mi),Jan Raas (NED),NaN
25,1B,30 June,Plain stage,100 km (62 mi),Walter Planckaert (BEL),NaN
26,2,1 July,Plain stage,199 km (124 mi),Jacques Esclassan (FRA),NaN
27,3,2 July,Plain stage,244 km (152 mi),Klaus-Peter Thaler (GER),NaN
28,4,3 July,Team time trial,153 km (95 mi),TI-Raleigh,NaN
29,5,4 July,Plain stage,244 km (152 mi),Freddy Maertens (BEL),NaN
...,...,...,...,...,...,...
42,17,18 July,Stage with mountain(s),225 km (140 mi),Christian Seznec (FRA),NaN
43,18,19 July,Plain stage,137 km (85 mi),Gerrie Knetemann (NED),NaN
44,19,20 July,Plain stage,182 km (113 mi),Marc Demeyer (BEL),NaN
45,20,21 July,Individual time trial,72 km (45 mi),Bernard Hinault (FRA),NaN
46,21,22 July,Plain stage,207 km (129 mi),Jan Raas (NED),NaN
47,22,23 July,Plain stage,162 km (101 mi),Gerrie Knetemann (NED),NaN
48,NaN,30 June,Plain stage,208 km (129 mi),Alfred Haemerlinck (BEL),Alfred Haemerlinck (BEL)
49,NaN,1 July,Plain stage,212 km (132 mi),Max Bulla (AUT),Max Bulla (AUT)
50,NaN,2 July,Plain stage,206 km (128 mi),Fabio Battesini (ITA),Leon Le Calvez (FRA)
51,NaN,3 July,Plain stage,211 km (131 mi),Andre Godinat (FRA),Rafaele di Paco (ITA)
52,NaN,4 July,Plain stage,202 km (126 mi),Charles Pelissier (FRA),Charles Pelissier (FRA) Rafaele di Paco (ITA)
53,NaN,5 July,Plain stage,338 km (210 mi),Alfred Haemerlinck (BEL),Rafaele di Paco (ITA)
54,NaN,6 July,Plain stage,180 km (110 mi),Gerard Loncke (BEL),Rafaele di Paco (ITA)
55,NaN,7 July,Plain stage,106 km (66 mi),Charles Pelissier (FRA),Charles Pelissier (FRA)
56,NaN,8 July,Stage with mountain(s),231 km (144 mi),Antonin Magne (FRA),Antonin Magne (FRA)
57,NaN,10 July,Stage with mountain(s),322 km (200 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
58,NaN,12 July,Plain stage,164 km (102 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
59,NaN,13 July,Plain stage,207 km (129 mi),Max Bulla (AUT),Antonin Magne (FRA)
60,NaN,14 July,Plain stage,181 km (112 mi),Charles Pelissier (FRA),Antonin Magne (FRA)
61,NaN,15 July,Stage with mountain(s),132 km (82 mi),Eugenio Gestri (ITA),Antonin Magne (FRA)
62,NaN,17 July,Stage with mountain(s),233 km (145 mi),Jef Demuysere (BEL),Antonin Magne (FRA)
63,NaN,18 July,Stage with mountain(s),102 km (63 mi),Charles Pelissier (FRA),Antonin Magne (FRA)
64,NaN,19 July,Stage with mountain(s),230 km (140 mi),Max Bulla (AUT),Antonin Magne (FRA)
65,NaN,20 July,Stage with mountain(s),204 km (127 mi),Jef Demuysere (BEL),Antonin Magne (FRA)
66,NaN,21 July,Stage with mountain(s),282 km (175 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
67,NaN,22 July,Stage with mountain(s),209 km (130 mi),Andre Leducq (FRA),Antonin Magne (FRA)
68,NaN,23 July,Plain stage,192 km (119 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
69,NaN,24 July,Plain stage,159 km (99 mi),Raffaele di Paco (ITA),Antonin Magne (FRA)
70,NaN,25 July,Plain stage,271 km (168 mi),Gaston Rebry (BEL),Antonin Magne (FRA)
71,NaN,26 July,Plain stage,313 km (194 mi),Charles Pelissier (FRA),Antonin Magne (FRA)

13.csv : 203_44.csv		203_475.csv		204_312.csv
Missing Values(NANs):  {'phase': '0/71', 'date': '0/71', 'terrain': '0/71', 'length': '0/71', 'race winner': '0/71'}
Columns that match with input_schema:
203_44.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
203_475.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
204_312.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
Coverage Score :  0.8333333333333334 	 Completeness Score :  0.8333333333333334

,phase,date,terrain,length,race winner
0,1,22 June,Plain stage,215 km (134 mi),Edward Sels (BEL)
1,2,23 June,Plain stage,208 km (129 mi),Andre Darrigade (FRA)
2,3A,24 June,Plain stage,197 km (122 mi),Bernard Vandekerkhove (BEL)
3,3B,24 June,Team time trial,21 km (13 mi),Kas-Kaskol
4,4,25 June,Plain stage,292 km (181 mi),Rudi Altig (GER)
5,5,26 June,Plain stage,161 km (100 mi),Willy Derboven (BEL)
6,6,27 June,Plain stage,200 km (120 mi),Henk Nijdam (NED)
7,7,28 June,Plain stage,195 km (121 mi),Jan Janssen (NED)
8,8,29 June,Stage with mountain(s),249 km (155 mi),Federico Bahamontes (ESP)
9,9,30 June,Stage with mountain(s),239 km (149 mi),Jacques Anquetil (FRA)
10,10A,1 July,Plain stage,187 km (116 mi),Jan Janssen (NED)
11,10B,1 July,Individual time trial,21 km (13 mi),Jacques Anquetil (FRA)
12,11,2 July,Plain stage,250 km (160 mi),Edward Sels (BEL)
13,12,3 July,Plain stage,174 km (108 mi),Jo de Roo (NED)
14,13,4 July,Stage with mountain(s),170 km (110 mi),Julio Jimenez (ESP)
15,14,6 July,Stage with mountain(s),186 km (116 mi),Edward Sels (BEL)
16,15,7 July,Stage with mountain(s),203 km (126 mi),Raymond Poulidor (FRA)
17,16,8 July,Stage with mountain(s),197 km (122 mi),Federico Bahamontes (ESP)
18,17,9 July,Individual time trial,43 km (27 mi),Jacques Anquetil (FRA)
19,18,10 July,Plain stage,187 km (116 mi),Andre Darrigade (FRA)
20,19,11 July,Plain stage,215 km (134 mi),Edward Sels (BEL)
21,20,12 July,Stage with mountain(s),217 km (135 mi),Julio Jimenez (ESP)
22,21,13 July,Plain stage,311 km (193 mi),Jean Stablinski (FRA)
23,22A,14 July,Plain stage,119 km (74 mi),Benoni Beheyt (BEL)
24,22B,14 July,Individual time trial,27 km (17 mi),Jacques Anquetil (FRA)
25,P,1 July,Individual time trial,7.3 km (4.5 mi),Jacky Durand (FRA)
26,1,2 July,Plain stage,233.5 km (145.1 mi),Fabio Baldato (ITA)
27,2,3 July,Plain stage,235.5 km (146.3 mi),Mario Cipollini (ITA)
28,3,4 July,Team time trial,67.0 km (41.6 mi),Gewiss-Ballan (ITA)
29,4,5 July,Plain stage,162.0 km (100.7 mi),Mario Cipollini (ITA)
...,...,...,...,...,...
41,16,19 July,Stage with mountain(s),149.0 km (92.6 mi),Cancelled
42,17,20 July,Plain stage,246.0 km (152.9 mi),Erik Zabel (GER)
43,18,21 July,Plain stage,166.5 km (103.5 mi),Lance Armstrong (USA)
44,19,22 July,Individual time trial,46.5 km (28.9 mi),Miguel Indurain (ESP)
45,20,23 July,Plain stage,155.0 km (96.3 mi),Djamolidine Abduzhaparov (UZB)
46,P,29 June,Individual time trial,5 km (3.1 mi),Jan Raas (NED)
47,1A,30 June,Plain stage,135 km (84 mi),Jan Raas (NED)
48,1B,30 June,Plain stage,100 km (62 mi),Walter Planckaert (BEL)
49,2,1 July,Plain stage,199 km (124 mi),Jacques Esclassan (FRA)
50,3,2 July,Plain stage,244 km (152 mi),Klaus-Peter Thaler (GER)
51,4,3 July,Team time trial,153 km (95 mi),TI-Raleigh
52,5,4 July,Plain stage,244 km (152 mi),Freddy Maertens (BEL)
53,6,5 July,Plain stage,162 km (101 mi),Sean Kelly (IRE)
54,7,6 July,Plain stage,242 km (150 mi),Freddy Maertens (BEL)
55,8,7 July,Individual time trial,59 km (37 mi),Bernard Hinault (FRA)
56,9,8 July,Plain stage,233 km (145 mi),Miguel Maria Lasa (ESP)
57,10,10 July,Hilly stage,192 km (119 mi),Henk Lubberding (NED)
58,11,11 July,Stage with mountain(s),161 km (100 mi),Mariano Martinez (FRA)
59,12A,12 July,Plain stage,158 km (98 mi),Cancelled
60,12B,12 July,Plain stage,96 km (60 mi),Jacques Esclassan (FRA)
61,13,13 July,Hilly stage,221 km (137 mi),Paul Wellens (BEL)
62,14,14 July,Individual time trial,52 km (32 mi),Joop Zoetemelk (NED)
63,15,15 July,Hilly stage,196 km (122 mi),Bernard Hinault (FRA)
64,16,16 July,Stage with mountain(s),241 km (150 mi),Hennie Kuiper (NED)
65,17,18 July,Stage with mountain(s),225 km (140 mi),Christian Seznec (FRA)
66,18,19 July,Plain stage,137 km (85 mi),Gerrie Knetemann (NED)
67,19,20 July,Plain stage,182 km (113 mi),Marc Demeyer (BEL)
68,20,21 July,Individual time trial,72 km (45 mi),Bernard Hinault (FRA)
69,21,22 July,Plain stage,207 km (129 mi),Jan Raas (NED)
70,22,23 July,Plain stage,162 km (101 mi),Gerrie Knetemann (NED)

14.csv : 203_44.csv		203_475.csv		204_406.csv
Missing Values(NANs):  {'phase': '24/70', 'date': '0/70', 'terrain': '0/70', 'length': '0/70', 'race winner': '0/70', 'leader': '46/70'}
Columns that match with input_schema:
203_44.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
203_475.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
204_406.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'winner': 'race winner', 'race leader': 'leader'}
Coverage Score :  1.0 	 Completeness Score :  0.8333333333333331

,phase,date,terrain,length,race winner,leader
0,1,22 June,Plain stage,215 km (134 mi),Edward Sels (BEL),NaN
1,2,23 June,Plain stage,208 km (129 mi),Andre Darrigade (FRA),NaN
2,3A,24 June,Plain stage,197 km (122 mi),Bernard Vandekerkhove (BEL),NaN
3,3B,24 June,Team time trial,21 km (13 mi),Kas-Kaskol,NaN
4,4,25 June,Plain stage,292 km (181 mi),Rudi Altig (GER),NaN
5,5,26 June,Plain stage,161 km (100 mi),Willy Derboven (BEL),NaN
6,6,27 June,Plain stage,200 km (120 mi),Henk Nijdam (NED),NaN
7,7,28 June,Plain stage,195 km (121 mi),Jan Janssen (NED),NaN
8,8,29 June,Stage with mountain(s),249 km (155 mi),Federico Bahamontes (ESP),NaN
9,9,30 June,Stage with mountain(s),239 km (149 mi),Jacques Anquetil (FRA),NaN
10,10A,1 July,Plain stage,187 km (116 mi),Jan Janssen (NED),NaN
11,10B,1 July,Individual time trial,21 km (13 mi),Jacques Anquetil (FRA),NaN
12,11,2 July,Plain stage,250 km (160 mi),Edward Sels (BEL),NaN
13,12,3 July,Plain stage,174 km (108 mi),Jo de Roo (NED),NaN
14,13,4 July,Stage with mountain(s),170 km (110 mi),Julio Jimenez (ESP),NaN
15,14,6 July,Stage with mountain(s),186 km (116 mi),Edward Sels (BEL),NaN
16,15,7 July,Stage with mountain(s),203 km (126 mi),Raymond Poulidor (FRA),NaN
17,16,8 July,Stage with mountain(s),197 km (122 mi),Federico Bahamontes (ESP),NaN
18,17,9 July,Individual time trial,43 km (27 mi),Jacques Anquetil (FRA),NaN
19,18,10 July,Plain stage,187 km (116 mi),Andre Darrigade (FRA),NaN
20,19,11 July,Plain stage,215 km (134 mi),Edward Sels (BEL),NaN
21,20,12 July,Stage with mountain(s),217 km (135 mi),Julio Jimenez (ESP),NaN
22,21,13 July,Plain stage,311 km (193 mi),Jean Stablinski (FRA),NaN
23,22A,14 July,Plain stage,119 km (74 mi),Benoni Beheyt (BEL),NaN
24,22B,14 July,Individual time trial,27 km (17 mi),Jacques Anquetil (FRA),NaN
25,P,1 July,Individual time trial,7.3 km (4.5 mi),Jacky Durand (FRA),NaN
26,1,2 July,Plain stage,233.5 km (145.1 mi),Fabio Baldato (ITA),NaN
27,2,3 July,Plain stage,235.5 km (146.3 mi),Mario Cipollini (ITA),NaN
28,3,4 July,Team time trial,67.0 km (41.6 mi),Gewiss-Ballan (ITA),NaN
29,4,5 July,Plain stage,162.0 km (100.7 mi),Mario Cipollini (ITA),NaN
...,...,...,...,...,...,...
40,15,18 July,Stage with mountain(s),206.0 km (128.0 mi),Richard Virenque (FRA),NaN
41,16,19 July,Stage with mountain(s),149.0 km (92.6 mi),Cancelled,NaN
42,17,20 July,Plain stage,246.0 km (152.9 mi),Erik Zabel (GER),NaN
43,18,21 July,Plain stage,166.5 km (103.5 mi),Lance Armstrong (USA),NaN
44,19,22 July,Individual time trial,46.5 km (28.9 mi),Miguel Indurain (ESP),NaN
45,20,23 July,Plain stage,155.0 km (96.3 mi),Djamolidine Abduzhaparov (UZB),NaN
46,NaN,30 June,Plain stage,208 km (129 mi),Alfred Haemerlinck (BEL),Alfred Haemerlinck (BEL)
47,NaN,1 July,Plain stage,212 km (132 mi),Max Bulla (AUT),Max Bulla (AUT)
48,NaN,2 July,Plain stage,206 km (128 mi),Fabio Battesini (ITA),Leon Le Calvez (FRA)
49,NaN,3 July,Plain stage,211 km (131 mi),Andre Godinat (FRA),Rafaele di Paco (ITA)
50,NaN,4 July,Plain stage,202 km (126 mi),Charles Pelissier (FRA),Charles Pelissier (FRA) Rafaele di Paco (ITA)
51,NaN,5 July,Plain stage,338 km (210 mi),Alfred Haemerlinck (BEL),Rafaele di Paco (ITA)
52,NaN,6 July,Plain stage,180 km (110 mi),Gerard Loncke (BEL),Rafaele di Paco (ITA)
53,NaN,7 July,Plain stage,106 km (66 mi),Charles Pelissier (FRA),Charles Pelissier (FRA)
54,NaN,8 July,Stage with mountain(s),231 km (144 mi),Antonin Magne (FRA),Antonin Magne (FRA)
55,NaN,10 July,Stage with mountain(s),322 km (200 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
56,NaN,12 July,Plain stage,164 km (102 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
57,NaN,13 July,Plain stage,207 km (129 mi),Max Bulla (AUT),Antonin Magne (FRA)
58,NaN,14 July,Plain stage,181 km (112 mi),Charles Pelissier (FRA),Antonin Magne (FRA)
59,NaN,15 July,Stage with mountain(s),132 km (82 mi),Eugenio Gestri (ITA),Antonin Magne (FRA)
60,NaN,17 July,Stage with mountain(s),233 km (145 mi),Jef Demuysere (BEL),Antonin Magne (FRA)
61,NaN,18 July,Stage with mountain(s),102 km (63 mi),Charles Pelissier (FRA),Antonin Magne (FRA)
62,NaN,19 July,Stage with mountain(s),230 km (140 mi),Max Bulla (AUT),Antonin Magne (FRA)
63,NaN,20 July,Stage with mountain(s),204 km (127 mi),Jef Demuysere (BEL),Antonin Magne (FRA)
64,NaN,21 July,Stage with mountain(s),282 km (175 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
65,NaN,22 July,Stage with mountain(s),209 km (130 mi),Andre Leducq (FRA),Antonin Magne (FRA)
66,NaN,23 July,Plain stage,192 km (119 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
67,NaN,24 July,Plain stage,159 km (99 mi),Raffaele di Paco (ITA),Antonin Magne (FRA)
68,NaN,25 July,Plain stage,271 km (168 mi),Gaston Rebry (BEL),Antonin Magne (FRA)
69,NaN,26 July,Plain stage,313 km (194 mi),Charles Pelissier (FRA),Antonin Magne (FRA)

15.csv : 203_44.csv		204_312.csv		204_406.csv
Missing Values(NANs):  {'phase': '24/74', 'date': '0/74', 'terrain': '0/74', 'length': '0/74', 'race winner': '0/74', 'leader': '50/74'}
Columns that match with input_schema:
203_44.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
204_312.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
204_406.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'winner': 'race winner', 'race leader': 'leader'}
Coverage Score :  1.0 	 Completeness Score :  0.8333333333333334

,phase,date,terrain,length,race winner,leader
0,1,22 June,Plain stage,215 km (134 mi),Edward Sels (BEL),NaN
1,2,23 June,Plain stage,208 km (129 mi),Andre Darrigade (FRA),NaN
2,3A,24 June,Plain stage,197 km (122 mi),Bernard Vandekerkhove (BEL),NaN
3,3B,24 June,Team time trial,21 km (13 mi),Kas-Kaskol,NaN
4,4,25 June,Plain stage,292 km (181 mi),Rudi Altig (GER),NaN
5,5,26 June,Plain stage,161 km (100 mi),Willy Derboven (BEL),NaN
6,6,27 June,Plain stage,200 km (120 mi),Henk Nijdam (NED),NaN
7,7,28 June,Plain stage,195 km (121 mi),Jan Janssen (NED),NaN
8,8,29 June,Stage with mountain(s),249 km (155 mi),Federico Bahamontes (ESP),NaN
9,9,30 June,Stage with mountain(s),239 km (149 mi),Jacques Anquetil (FRA),NaN
10,10A,1 July,Plain stage,187 km (116 mi),Jan Janssen (NED),NaN
11,10B,1 July,Individual time trial,21 km (13 mi),Jacques Anquetil (FRA),NaN
12,11,2 July,Plain stage,250 km (160 mi),Edward Sels (BEL),NaN
13,12,3 July,Plain stage,174 km (108 mi),Jo de Roo (NED),NaN
14,13,4 July,Stage with mountain(s),170 km (110 mi),Julio Jimenez (ESP),NaN
15,14,6 July,Stage with mountain(s),186 km (116 mi),Edward Sels (BEL),NaN
16,15,7 July,Stage with mountain(s),203 km (126 mi),Raymond Poulidor (FRA),NaN
17,16,8 July,Stage with mountain(s),197 km (122 mi),Federico Bahamontes (ESP),NaN
18,17,9 July,Individual time trial,43 km (27 mi),Jacques Anquetil (FRA),NaN
19,18,10 July,Plain stage,187 km (116 mi),Andre Darrigade (FRA),NaN
20,19,11 July,Plain stage,215 km (134 mi),Edward Sels (BEL),NaN
21,20,12 July,Stage with mountain(s),217 km (135 mi),Julio Jimenez (ESP),NaN
22,21,13 July,Plain stage,311 km (193 mi),Jean Stablinski (FRA),NaN
23,22A,14 July,Plain stage,119 km (74 mi),Benoni Beheyt (BEL),NaN
24,22B,14 July,Individual time trial,27 km (17 mi),Jacques Anquetil (FRA),NaN
25,P,29 June,Individual time trial,5 km (3.1 mi),Jan Raas (NED),NaN
26,1A,30 June,Plain stage,135 km (84 mi),Jan Raas (NED),NaN
27,1B,30 June,Plain stage,100 km (62 mi),Walter Planckaert (BEL),NaN
28,2,1 July,Plain stage,199 km (124 mi),Jacques Esclassan (FRA),NaN
29,3,2 July,Plain stage,244 km (152 mi),Klaus-Peter Thaler (GER),NaN
...,...,...,...,...,...,...
44,17,18 July,Stage with mountain(s),225 km (140 mi),Christian Seznec (FRA),NaN
45,18,19 July,Plain stage,137 km (85 mi),Gerrie Knetemann (NED),NaN
46,19,20 July,Plain stage,182 km (113 mi),Marc Demeyer (BEL),NaN
47,20,21 July,Individual time trial,72 km (45 mi),Bernard Hinault (FRA),NaN
48,21,22 July,Plain stage,207 km (129 mi),Jan Raas (NED),NaN
49,22,23 July,Plain stage,162 km (101 mi),Gerrie Knetemann (NED),NaN
50,NaN,30 June,Plain stage,208 km (129 mi),Alfred Haemerlinck (BEL),Alfred Haemerlinck (BEL)
51,NaN,1 July,Plain stage,212 km (132 mi),Max Bulla (AUT),Max Bulla (AUT)
52,NaN,2 July,Plain stage,206 km (128 mi),Fabio Battesini (ITA),Leon Le Calvez (FRA)
53,NaN,3 July,Plain stage,211 km (131 mi),Andre Godinat (FRA),Rafaele di Paco (ITA)
54,NaN,4 July,Plain stage,202 km (126 mi),Charles Pelissier (FRA),Charles Pelissier (FRA) Rafaele di Paco (ITA)
55,NaN,5 July,Plain stage,338 km (210 mi),Alfred Haemerlinck (BEL),Rafaele di Paco (ITA)
56,NaN,6 July,Plain stage,180 km (110 mi),Gerard Loncke (BEL),Rafaele di Paco (ITA)
57,NaN,7 July,Plain stage,106 km (66 mi),Charles Pelissier (FRA),Charles Pelissier (FRA)
58,NaN,8 July,Stage with mountain(s),231 km (144 mi),Antonin Magne (FRA),Antonin Magne (FRA)
59,NaN,10 July,Stage with mountain(s),322 km (200 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
60,NaN,12 July,Plain stage,164 km (102 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
61,NaN,13 July,Plain stage,207 km (129 mi),Max Bulla (AUT),Antonin Magne (FRA)
62,NaN,14 July,Plain stage,181 km (112 mi),Charles Pelissier (FRA),Antonin Magne (FRA)
63,NaN,15 July,Stage with mountain(s),132 km (82 mi),Eugenio Gestri (ITA),Antonin Magne (FRA)
64,NaN,17 July,Stage with mountain(s),233 km (145 mi),Jef Demuysere (BEL),Antonin Magne (FRA)
65,NaN,18 July,Stage with mountain(s),102 km (63 mi),Charles Pelissier (FRA),Antonin Magne (FRA)
66,NaN,19 July,Stage with mountain(s),230 km (140 mi),Max Bulla (AUT),Antonin Magne (FRA)
67,NaN,20 July,Stage with mountain(s),204 km (127 mi),Jef Demuysere (BEL),Antonin Magne (FRA)
68,NaN,21 July,Stage with mountain(s),282 km (175 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
69,NaN,22 July,Stage with mountain(s),209 km (130 mi),Andre Leducq (FRA),Antonin Magne (FRA)
70,NaN,23 July,Plain stage,192 km (119 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
71,NaN,24 July,Plain stage,159 km (99 mi),Raffaele di Paco (ITA),Antonin Magne (FRA)
72,NaN,25 July,Plain stage,271 km (168 mi),Gaston Rebry (BEL),Antonin Magne (FRA)
73,NaN,26 July,Plain stage,313 km (194 mi),Charles Pelissier (FRA),Antonin Magne (FRA)

16.csv : 203_475.csv		204_312.csv		204_406.csv
Missing Values(NANs):  {'phase': '24/70', 'date': '0/70', 'terrain': '0/70', 'length': '0/70', 'race winner': '0/70', 'leader': '46/70'}
Columns that match with input_schema:
203_475.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
204_312.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
204_406.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'winner': 'race winner', 'race leader': 'leader'}
Coverage Score :  1.0 	 Completeness Score :  0.8333333333333331

,phase,date,terrain,length,race winner,leader
0,P,1 July,Individual time trial,7.3 km (4.5 mi),Jacky Durand (FRA),NaN
1,1,2 July,Plain stage,233.5 km (145.1 mi),Fabio Baldato (ITA),NaN
2,2,3 July,Plain stage,235.5 km (146.3 mi),Mario Cipollini (ITA),NaN
3,3,4 July,Team time trial,67.0 km (41.6 mi),Gewiss-Ballan (ITA),NaN
4,4,5 July,Plain stage,162.0 km (100.7 mi),Mario Cipollini (ITA),NaN
5,5,6 July,Plain stage,261.0 km (162.2 mi),Jeroen Blijlevens (NED),NaN
6,6,7 July,Plain stage,202.0 km (125.5 mi),Erik Zabel (GER),NaN
7,7,8 July,Hilly stage,203.0 km (126.1 mi),Johan Bruyneel (BEL),NaN
8,8,9 July,Individual time trial,54.0 km (33.6 mi),Miguel Indurain (ESP),NaN
9,9,11 July,Stage with mountain(s),160.0 km (99.4 mi),Alex Zulle (SUI),NaN
10,10,12 July,Stage with mountain(s),162.5 km (101.0 mi),Marco Pantani (ITA),NaN
11,11,13 July,Hilly stage,199.0 km (123.7 mi),Maximilian Sciandri (GBR),NaN
12,12,14 July,Hilly stage,222.5 km (138.3 mi),Laurent Jalabert (FRA),NaN
13,13,15 July,Plain stage,245.0 km (152.2 mi),Serhiy Utchakov (UKR),NaN
14,14,16 July,Stage with mountain(s),164.0 km (101.9 mi),Marco Pantani (ITA),NaN
15,15,18 July,Stage with mountain(s),206.0 km (128.0 mi),Richard Virenque (FRA),NaN
16,16,19 July,Stage with mountain(s),149.0 km (92.6 mi),Cancelled,NaN
17,17,20 July,Plain stage,246.0 km (152.9 mi),Erik Zabel (GER),NaN
18,18,21 July,Plain stage,166.5 km (103.5 mi),Lance Armstrong (USA),NaN
19,19,22 July,Individual time trial,46.5 km (28.9 mi),Miguel Indurain (ESP),NaN
20,20,23 July,Plain stage,155.0 km (96.3 mi),Djamolidine Abduzhaparov (UZB),NaN
21,P,29 June,Individual time trial,5 km (3.1 mi),Jan Raas (NED),NaN
22,1A,30 June,Plain stage,135 km (84 mi),Jan Raas (NED),NaN
23,1B,30 June,Plain stage,100 km (62 mi),Walter Planckaert (BEL),NaN
24,2,1 July,Plain stage,199 km (124 mi),Jacques Esclassan (FRA),NaN
25,3,2 July,Plain stage,244 km (152 mi),Klaus-Peter Thaler (GER),NaN
26,4,3 July,Team time trial,153 km (95 mi),TI-Raleigh,NaN
27,5,4 July,Plain stage,244 km (152 mi),Freddy Maertens (BEL),NaN
28,6,5 July,Plain stage,162 km (101 mi),Sean Kelly (IRE),NaN
29,7,6 July,Plain stage,242 km (150 mi),Freddy Maertens (BEL),NaN
...,...,...,...,...,...,...
40,17,18 July,Stage with mountain(s),225 km (140 mi),Christian Seznec (FRA),NaN
41,18,19 July,Plain stage,137 km (85 mi),Gerrie Knetemann (NED),NaN
42,19,20 July,Plain stage,182 km (113 mi),Marc Demeyer (BEL),NaN
43,20,21 July,Individual time trial,72 km (45 mi),Bernard Hinault (FRA),NaN
44,21,22 July,Plain stage,207 km (129 mi),Jan Raas (NED),NaN
45,22,23 July,Plain stage,162 km (101 mi),Gerrie Knetemann (NED),NaN
46,NaN,30 June,Plain stage,208 km (129 mi),Alfred Haemerlinck (BEL),Alfred Haemerlinck (BEL)
47,NaN,1 July,Plain stage,212 km (132 mi),Max Bulla (AUT),Max Bulla (AUT)
48,NaN,2 July,Plain stage,206 km (128 mi),Fabio Battesini (ITA),Leon Le Calvez (FRA)
49,NaN,3 July,Plain stage,211 km (131 mi),Andre Godinat (FRA),Rafaele di Paco (ITA)
50,NaN,4 July,Plain stage,202 km (126 mi),Charles Pelissier (FRA),Charles Pelissier (FRA) Rafaele di Paco (ITA)
51,NaN,5 July,Plain stage,338 km (210 mi),Alfred Haemerlinck (BEL),Rafaele di Paco (ITA)
52,NaN,6 July,Plain stage,180 km (110 mi),Gerard Loncke (BEL),Rafaele di Paco (ITA)
53,NaN,7 July,Plain stage,106 km (66 mi),Charles Pelissier (FRA),Charles Pelissier (FRA)
54,NaN,8 July,Stage with mountain(s),231 km (144 mi),Antonin Magne (FRA),Antonin Magne (FRA)
55,NaN,10 July,Stage with mountain(s),322 km (200 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
56,NaN,12 July,Plain stage,164 km (102 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
57,NaN,13 July,Plain stage,207 km (129 mi),Max Bulla (AUT),Antonin Magne (FRA)
58,NaN,14 July,Plain stage,181 km (112 mi),Charles Pelissier (FRA),Antonin Magne (FRA)
59,NaN,15 July,Stage with mountain(s),132 km (82 mi),Eugenio Gestri (ITA),Antonin Magne (FRA)
60,NaN,17 July,Stage with mountain(s),233 km (145 mi),Jef Demuysere (BEL),Antonin Magne (FRA)
61,NaN,18 July,Stage with mountain(s),102 km (63 mi),Charles Pelissier (FRA),Antonin Magne (FRA)
62,NaN,19 July,Stage with mountain(s),230 km (140 mi),Max Bulla (AUT),Antonin Magne (FRA)
63,NaN,20 July,Stage with mountain(s),204 km (127 mi),Jef Demuysere (BEL),Antonin Magne (FRA)
64,NaN,21 July,Stage with mountain(s),282 km (175 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
65,NaN,22 July,Stage with mountain(s),209 km (130 mi),Andre Leducq (FRA),Antonin Magne (FRA)
66,NaN,23 July,Plain stage,192 km (119 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
67,NaN,24 July,Plain stage,159 km (99 mi),Raffaele di Paco (ITA),Antonin Magne (FRA)
68,NaN,25 July,Plain stage,271 km (168 mi),Gaston Rebry (BEL),Antonin Magne (FRA)
69,NaN,26 July,Plain stage,313 km (194 mi),Charles Pelissier (FRA),Antonin Magne (FRA)

17.csv : 203_25.csv		203_44.csv
Missing Values(NANs):  {'phase': '0/48', 'date': '0/48', 'terrain': '0/48', 'length': '0/48', 'race winner': '0/48'}
Columns that match with input_schema:
203_25.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
203_44.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
Coverage Score :  0.8333333333333334 	 Completeness Score :  0.8333333333333334

,phase,date,terrain,length,race winner
0,P,1 July,Individual time trial,6 km (3.7 mi),Eric Vanderaerden (BEL)
1,1,2 July,Plain stage,163 km (101 mi),Frits Pirard (NED)
2,2,3 July,Team time trial,100 km (62 mi),Mercier
3,3,4 July,Hilly stage,152 km (94 mi),Rudy Matthijs (BEL)
4,4,5 July,Plain stage,300 km (190 mi),Serge Demierre (SUI)
5,5,6 July,Plain stage,257 km (160 mi),Dominique Gaigne (FRA)
6,6,7 July,Individual time trial,58 km (36 mi),Bert Oosterbosch (NED)
7,7,8 July,Plain stage,216 km (134 mi),Riccardo Magrini (ITA)
8,8,9 July,Plain stage,222 km (138 mi),Bert Oosterbosch (NED)
9,9,10 July,Plain stage,207 km (129 mi),Philippe Chevallier (FRA)
10,10,11 July,Stage with mountain(s),201 km (125 mi),Robert Millar (GBR)
11,11,12 July,Plain stage,177 km (110 mi),Regis Clere (FRA)
12,12,13 July,Plain stage,261 km (162 mi),Kim Andersen (DEN)
13,13,14 July,Hilly stage,210 km (130 mi),Henk Lubberding (NED)
14,14,15 July,Hilly stage,149 km (93 mi),Pierre Le Bigaut (FRA)
15,15,16 July,Individual time trial,16 km (9.9 mi),Ángel Arroyo (ESP)
16,16,17 July,Hilly stage,144 km (89 mi),Michel Laurent (FRA)
17,17,18 July,Stage with mountain(s),223 km (139 mi),Peter Winnen (NED)
18,18,20 July,Stage with mountain(s),247 km (153 mi),Jacques Michaud (FRA)
19,19,21 July,Individual time trial,15 km (9.3 mi),Lucien Van Impe (BEL)
20,20,22 July,Plain stage,291 km (181 mi),Philippe Leleu (FRA)
21,21,23 July,Individual time trial,50 km (31 mi),Laurent Fignon (FRA)
22,22,24 July,Plain stage,195 km (121 mi),Gilbert Glaus (SUI)
23,1,22 June,Plain stage,215 km (134 mi),Edward Sels (BEL)
24,2,23 June,Plain stage,208 km (129 mi),Andre Darrigade (FRA)
25,3A,24 June,Plain stage,197 km (122 mi),Bernard Vandekerkhove (BEL)
26,3B,24 June,Team time trial,21 km (13 mi),Kas-Kaskol
27,4,25 June,Plain stage,292 km (181 mi),Rudi Altig (GER)
28,5,26 June,Plain stage,161 km (100 mi),Willy Derboven (BEL)
29,6,27 June,Plain stage,200 km (120 mi),Henk Nijdam (NED)
30,7,28 June,Plain stage,195 km (121 mi),Jan Janssen (NED)
31,8,29 June,Stage with mountain(s),249 km (155 mi),Federico Bahamontes (ESP)
32,9,30 June,Stage with mountain(s),239 km (149 mi),Jacques Anquetil (FRA)
33,10A,1 July,Plain stage,187 km (116 mi),Jan Janssen (NED)
34,10B,1 July,Individual time trial,21 km (13 mi),Jacques Anquetil (FRA)
35,11,2 July,Plain stage,250 km (160 mi),Edward Sels (BEL)
36,12,3 July,Plain stage,174 km (108 mi),Jo de Roo (NED)
37,13,4 July,Stage with mountain(s),170 km (110 mi),Julio Jimenez (ESP)
38,14,6 July,Stage with mountain(s),186 km (116 mi),Edward Sels (BEL)
39,15,7 July,Stage with mountain(s),203 km (126 mi),Raymond Poulidor (FRA)
40,16,8 July,Stage with mountain(s),197 km (122 mi),Federico Bahamontes (ESP)
41,17,9 July,Individual time trial,43 km (27 mi),Jacques Anquetil (FRA)
42,18,10 July,Plain stage,187 km (116 mi),Andre Darrigade (FRA)
43,19,11 July,Plain stage,215 km (134 mi),Edward Sels (BEL)
44,20,12 July,Stage with mountain(s),217 km (135 mi),Julio Jimenez (ESP)
45,21,13 July,Plain stage,311 km (193 mi),Jean Stablinski (FRA)
46,22A,14 July,Plain stage,119 km (74 mi),Benoni Beheyt (BEL)
47,22B,14 July,Individual time trial,27 km (17 mi),Jacques Anquetil (FRA)

18.csv : 203_25.csv		203_475.csv
Missing Values(NANs):  {'phase': '0/44', 'date': '0/44', 'terrain': '0/44', 'length': '0/44', 'race winner': '0/44'}
Columns that match with input_schema:
203_25.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
203_475.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
Coverage Score :  0.8333333333333334 	 Completeness Score :  0.8333333333333334

,phase,date,terrain,length,race winner
0,P,1 July,Individual time trial,6 km (3.7 mi),Eric Vanderaerden (BEL)
1,1,2 July,Plain stage,163 km (101 mi),Frits Pirard (NED)
2,2,3 July,Team time trial,100 km (62 mi),Mercier
3,3,4 July,Hilly stage,152 km (94 mi),Rudy Matthijs (BEL)
4,4,5 July,Plain stage,300 km (190 mi),Serge Demierre (SUI)
5,5,6 July,Plain stage,257 km (160 mi),Dominique Gaigne (FRA)
6,6,7 July,Individual time trial,58 km (36 mi),Bert Oosterbosch (NED)
7,7,8 July,Plain stage,216 km (134 mi),Riccardo Magrini (ITA)
8,8,9 July,Plain stage,222 km (138 mi),Bert Oosterbosch (NED)
9,9,10 July,Plain stage,207 km (129 mi),Philippe Chevallier (FRA)
10,10,11 July,Stage with mountain(s),201 km (125 mi),Robert Millar (GBR)
11,11,12 July,Plain stage,177 km (110 mi),Regis Clere (FRA)
12,12,13 July,Plain stage,261 km (162 mi),Kim Andersen (DEN)
13,13,14 July,Hilly stage,210 km (130 mi),Henk Lubberding (NED)
14,14,15 July,Hilly stage,149 km (93 mi),Pierre Le Bigaut (FRA)
15,15,16 July,Individual time trial,16 km (9.9 mi),Ángel Arroyo (ESP)
16,16,17 July,Hilly stage,144 km (89 mi),Michel Laurent (FRA)
17,17,18 July,Stage with mountain(s),223 km (139 mi),Peter Winnen (NED)
18,18,20 July,Stage with mountain(s),247 km (153 mi),Jacques Michaud (FRA)
19,19,21 July,Individual time trial,15 km (9.3 mi),Lucien Van Impe (BEL)
20,20,22 July,Plain stage,291 km (181 mi),Philippe Leleu (FRA)
21,21,23 July,Individual time trial,50 km (31 mi),Laurent Fignon (FRA)
22,22,24 July,Plain stage,195 km (121 mi),Gilbert Glaus (SUI)
23,P,1 July,Individual time trial,7.3 km (4.5 mi),Jacky Durand (FRA)
24,1,2 July,Plain stage,233.5 km (145.1 mi),Fabio Baldato (ITA)
25,2,3 July,Plain stage,235.5 km (146.3 mi),Mario Cipollini (ITA)
26,3,4 July,Team time trial,67.0 km (41.6 mi),Gewiss-Ballan (ITA)
27,4,5 July,Plain stage,162.0 km (100.7 mi),Mario Cipollini (ITA)
28,5,6 July,Plain stage,261.0 km (162.2 mi),Jeroen Blijlevens (NED)
29,6,7 July,Plain stage,202.0 km (125.5 mi),Erik Zabel (GER)
30,7,8 July,Hilly stage,203.0 km (126.1 mi),Johan Bruyneel (BEL)
31,8,9 July,Individual time trial,54.0 km (33.6 mi),Miguel Indurain (ESP)
32,9,11 July,Stage with mountain(s),160.0 km (99.4 mi),Alex Zulle (SUI)
33,10,12 July,Stage with mountain(s),162.5 km (101.0 mi),Marco Pantani (ITA)
34,11,13 July,Hilly stage,199.0 km (123.7 mi),Maximilian Sciandri (GBR)
35,12,14 July,Hilly stage,222.5 km (138.3 mi),Laurent Jalabert (FRA)
36,13,15 July,Plain stage,245.0 km (152.2 mi),Serhiy Utchakov (UKR)
37,14,16 July,Stage with mountain(s),164.0 km (101.9 mi),Marco Pantani (ITA)
38,15,18 July,Stage with mountain(s),206.0 km (128.0 mi),Richard Virenque (FRA)
39,16,19 July,Stage with mountain(s),149.0 km (92.6 mi),Cancelled
40,17,20 July,Plain stage,246.0 km (152.9 mi),Erik Zabel (GER)
41,18,21 July,Plain stage,166.5 km (103.5 mi),Lance Armstrong (USA)
42,19,22 July,Individual time trial,46.5 km (28.9 mi),Miguel Indurain (ESP)
43,20,23 July,Plain stage,155.0 km (96.3 mi),Djamolidine Abduzhaparov (UZB)

19.csv : 203_25.csv		204_312.csv
Missing Values(NANs):  {'phase': '0/48', 'date': '0/48', 'terrain': '0/48', 'length': '0/48', 'race winner': '0/48'}
Columns that match with input_schema:
203_25.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
204_312.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
Coverage Score :  0.8333333333333334 	 Completeness Score :  0.8333333333333334

,phase,date,terrain,length,race winner
0,P,1 July,Individual time trial,6 km (3.7 mi),Eric Vanderaerden (BEL)
1,1,2 July,Plain stage,163 km (101 mi),Frits Pirard (NED)
2,2,3 July,Team time trial,100 km (62 mi),Mercier
3,3,4 July,Hilly stage,152 km (94 mi),Rudy Matthijs (BEL)
4,4,5 July,Plain stage,300 km (190 mi),Serge Demierre (SUI)
5,5,6 July,Plain stage,257 km (160 mi),Dominique Gaigne (FRA)
6,6,7 July,Individual time trial,58 km (36 mi),Bert Oosterbosch (NED)
7,7,8 July,Plain stage,216 km (134 mi),Riccardo Magrini (ITA)
8,8,9 July,Plain stage,222 km (138 mi),Bert Oosterbosch (NED)
9,9,10 July,Plain stage,207 km (129 mi),Philippe Chevallier (FRA)
10,10,11 July,Stage with mountain(s),201 km (125 mi),Robert Millar (GBR)
11,11,12 July,Plain stage,177 km (110 mi),Regis Clere (FRA)
12,12,13 July,Plain stage,261 km (162 mi),Kim Andersen (DEN)
13,13,14 July,Hilly stage,210 km (130 mi),Henk Lubberding (NED)
14,14,15 July,Hilly stage,149 km (93 mi),Pierre Le Bigaut (FRA)
15,15,16 July,Individual time trial,16 km (9.9 mi),Ángel Arroyo (ESP)
16,16,17 July,Hilly stage,144 km (89 mi),Michel Laurent (FRA)
17,17,18 July,Stage with mountain(s),223 km (139 mi),Peter Winnen (NED)
18,18,20 July,Stage with mountain(s),247 km (153 mi),Jacques Michaud (FRA)
19,19,21 July,Individual time trial,15 km (9.3 mi),Lucien Van Impe (BEL)
20,20,22 July,Plain stage,291 km (181 mi),Philippe Leleu (FRA)
21,21,23 July,Individual time trial,50 km (31 mi),Laurent Fignon (FRA)
22,22,24 July,Plain stage,195 km (121 mi),Gilbert Glaus (SUI)
23,P,29 June,Individual time trial,5 km (3.1 mi),Jan Raas (NED)
24,1A,30 June,Plain stage,135 km (84 mi),Jan Raas (NED)
25,1B,30 June,Plain stage,100 km (62 mi),Walter Planckaert (BEL)
26,2,1 July,Plain stage,199 km (124 mi),Jacques Esclassan (FRA)
27,3,2 July,Plain stage,244 km (152 mi),Klaus-Peter Thaler (GER)
28,4,3 July,Team time trial,153 km (95 mi),TI-Raleigh
29,5,4 July,Plain stage,244 km (152 mi),Freddy Maertens (BEL)
30,6,5 July,Plain stage,162 km (101 mi),Sean Kelly (IRE)
31,7,6 July,Plain stage,242 km (150 mi),Freddy Maertens (BEL)
32,8,7 July,Individual time trial,59 km (37 mi),Bernard Hinault (FRA)
33,9,8 July,Plain stage,233 km (145 mi),Miguel Maria Lasa (ESP)
34,10,10 July,Hilly stage,192 km (119 mi),Henk Lubberding (NED)
35,11,11 July,Stage with mountain(s),161 km (100 mi),Mariano Martinez (FRA)
36,12A,12 July,Plain stage,158 km (98 mi),Cancelled
37,12B,12 July,Plain stage,96 km (60 mi),Jacques Esclassan (FRA)
38,13,13 July,Hilly stage,221 km (137 mi),Paul Wellens (BEL)
39,14,14 July,Individual time trial,52 km (32 mi),Joop Zoetemelk (NED)
40,15,15 July,Hilly stage,196 km (122 mi),Bernard Hinault (FRA)
41,16,16 July,Stage with mountain(s),241 km (150 mi),Hennie Kuiper (NED)
42,17,18 July,Stage with mountain(s),225 km (140 mi),Christian Seznec (FRA)
43,18,19 July,Plain stage,137 km (85 mi),Gerrie Knetemann (NED)
44,19,20 July,Plain stage,182 km (113 mi),Marc Demeyer (BEL)
45,20,21 July,Individual time trial,72 km (45 mi),Bernard Hinault (FRA)
46,21,22 July,Plain stage,207 km (129 mi),Jan Raas (NED)
47,22,23 July,Plain stage,162 km (101 mi),Gerrie Knetemann (NED)

20.csv : 203_25.csv		204_406.csv
Missing Values(NANs):  {'phase': '24/47', 'date': '0/47', 'terrain': '0/47', 'length': '0/47', 'race winner': '0/47', 'leader': '23/47'}
Columns that match with input_schema:
203_25.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
204_406.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'winner': 'race winner', 'race leader': 'leader'}
Coverage Score :  1.0 	 Completeness Score :  0.8333333333333334

,phase,date,terrain,length,race winner,leader
0,P,1 July,Individual time trial,6 km (3.7 mi),Eric Vanderaerden (BEL),NaN
1,1,2 July,Plain stage,163 km (101 mi),Frits Pirard (NED),NaN
2,2,3 July,Team time trial,100 km (62 mi),Mercier,NaN
3,3,4 July,Hilly stage,152 km (94 mi),Rudy Matthijs (BEL),NaN
4,4,5 July,Plain stage,300 km (190 mi),Serge Demierre (SUI),NaN
5,5,6 July,Plain stage,257 km (160 mi),Dominique Gaigne (FRA),NaN
6,6,7 July,Individual time trial,58 km (36 mi),Bert Oosterbosch (NED),NaN
7,7,8 July,Plain stage,216 km (134 mi),Riccardo Magrini (ITA),NaN
8,8,9 July,Plain stage,222 km (138 mi),Bert Oosterbosch (NED),NaN
9,9,10 July,Plain stage,207 km (129 mi),Philippe Chevallier (FRA),NaN
10,10,11 July,Stage with mountain(s),201 km (125 mi),Robert Millar (GBR),NaN
11,11,12 July,Plain stage,177 km (110 mi),Regis Clere (FRA),NaN
12,12,13 July,Plain stage,261 km (162 mi),Kim Andersen (DEN),NaN
13,13,14 July,Hilly stage,210 km (130 mi),Henk Lubberding (NED),NaN
14,14,15 July,Hilly stage,149 km (93 mi),Pierre Le Bigaut (FRA),NaN
15,15,16 July,Individual time trial,16 km (9.9 mi),Ángel Arroyo (ESP),NaN
16,16,17 July,Hilly stage,144 km (89 mi),Michel Laurent (FRA),NaN
17,17,18 July,Stage with mountain(s),223 km (139 mi),Peter Winnen (NED),NaN
18,18,20 July,Stage with mountain(s),247 km (153 mi),Jacques Michaud (FRA),NaN
19,19,21 July,Individual time trial,15 km (9.3 mi),Lucien Van Impe (BEL),NaN
20,20,22 July,Plain stage,291 km (181 mi),Philippe Leleu (FRA),NaN
21,21,23 July,Individual time trial,50 km (31 mi),Laurent Fignon (FRA),NaN
22,22,24 July,Plain stage,195 km (121 mi),Gilbert Glaus (SUI),NaN
23,NaN,30 June,Plain stage,208 km (129 mi),Alfred Haemerlinck (BEL),Alfred Haemerlinck (BEL)
24,NaN,1 July,Plain stage,212 km (132 mi),Max Bulla (AUT),Max Bulla (AUT)
25,NaN,2 July,Plain stage,206 km (128 mi),Fabio Battesini (ITA),Leon Le Calvez (FRA)
26,NaN,3 July,Plain stage,211 km (131 mi),Andre Godinat (FRA),Rafaele di Paco (ITA)
27,NaN,4 July,Plain stage,202 km (126 mi),Charles Pelissier (FRA),Charles Pelissier (FRA) Rafaele di Paco (ITA)
28,NaN,5 July,Plain stage,338 km (210 mi),Alfred Haemerlinck (BEL),Rafaele di Paco (ITA)
29,NaN,6 July,Plain stage,180 km (110 mi),Gerard Loncke (BEL),Rafaele di Paco (ITA)
30,NaN,7 July,Plain stage,106 km (66 mi),Charles Pelissier (FRA),Charles Pelissier (FRA)
31,NaN,8 July,Stage with mountain(s),231 km (144 mi),Antonin Magne (FRA),Antonin Magne (FRA)
32,NaN,10 July,Stage with mountain(s),322 km (200 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
33,NaN,12 July,Plain stage,164 km (102 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
34,NaN,13 July,Plain stage,207 km (129 mi),Max Bulla (AUT),Antonin Magne (FRA)
35,NaN,14 July,Plain stage,181 km (112 mi),Charles Pelissier (FRA),Antonin Magne (FRA)
36,NaN,15 July,Stage with mountain(s),132 km (82 mi),Eugenio Gestri (ITA),Antonin Magne (FRA)
37,NaN,17 July,Stage with mountain(s),233 km (145 mi),Jef Demuysere (BEL),Antonin Magne (FRA)
38,NaN,18 July,Stage with mountain(s),102 km (63 mi),Charles Pelissier (FRA),Antonin Magne (FRA)
39,NaN,19 July,Stage with mountain(s),230 km (140 mi),Max Bulla (AUT),Antonin Magne (FRA)
40,NaN,20 July,Stage with mountain(s),204 km (127 mi),Jef Demuysere (BEL),Antonin Magne (FRA)
41,NaN,21 July,Stage with mountain(s),282 km (175 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
42,NaN,22 July,Stage with mountain(s),209 km (130 mi),Andre Leducq (FRA),Antonin Magne (FRA)
43,NaN,23 July,Plain stage,192 km (119 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
44,NaN,24 July,Plain stage,159 km (99 mi),Raffaele di Paco (ITA),Antonin Magne (FRA)
45,NaN,25 July,Plain stage,271 km (168 mi),Gaston Rebry (BEL),Antonin Magne (FRA)
46,NaN,26 July,Plain stage,313 km (194 mi),Charles Pelissier (FRA),Antonin Magne (FRA)

21.csv : 203_44.csv		203_475.csv
Missing Values(NANs):  {'phase': '0/46', 'date': '0/46', 'terrain': '0/46', 'length': '0/46', 'race winner': '0/46'}
Columns that match with input_schema:
203_44.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
203_475.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
Coverage Score :  0.8333333333333334 	 Completeness Score :  0.8333333333333334

,phase,date,terrain,length,race winner
0,1,22 June,Plain stage,215 km (134 mi),Edward Sels (BEL)
1,2,23 June,Plain stage,208 km (129 mi),Andre Darrigade (FRA)
2,3A,24 June,Plain stage,197 km (122 mi),Bernard Vandekerkhove (BEL)
3,3B,24 June,Team time trial,21 km (13 mi),Kas-Kaskol
4,4,25 June,Plain stage,292 km (181 mi),Rudi Altig (GER)
5,5,26 June,Plain stage,161 km (100 mi),Willy Derboven (BEL)
6,6,27 June,Plain stage,200 km (120 mi),Henk Nijdam (NED)
7,7,28 June,Plain stage,195 km (121 mi),Jan Janssen (NED)
8,8,29 June,Stage with mountain(s),249 km (155 mi),Federico Bahamontes (ESP)
9,9,30 June,Stage with mountain(s),239 km (149 mi),Jacques Anquetil (FRA)
10,10A,1 July,Plain stage,187 km (116 mi),Jan Janssen (NED)
11,10B,1 July,Individual time trial,21 km (13 mi),Jacques Anquetil (FRA)
12,11,2 July,Plain stage,250 km (160 mi),Edward Sels (BEL)
13,12,3 July,Plain stage,174 km (108 mi),Jo de Roo (NED)
14,13,4 July,Stage with mountain(s),170 km (110 mi),Julio Jimenez (ESP)
15,14,6 July,Stage with mountain(s),186 km (116 mi),Edward Sels (BEL)
16,15,7 July,Stage with mountain(s),203 km (126 mi),Raymond Poulidor (FRA)
17,16,8 July,Stage with mountain(s),197 km (122 mi),Federico Bahamontes (ESP)
18,17,9 July,Individual time trial,43 km (27 mi),Jacques Anquetil (FRA)
19,18,10 July,Plain stage,187 km (116 mi),Andre Darrigade (FRA)
20,19,11 July,Plain stage,215 km (134 mi),Edward Sels (BEL)
21,20,12 July,Stage with mountain(s),217 km (135 mi),Julio Jimenez (ESP)
22,21,13 July,Plain stage,311 km (193 mi),Jean Stablinski (FRA)
23,22A,14 July,Plain stage,119 km (74 mi),Benoni Beheyt (BEL)
24,22B,14 July,Individual time trial,27 km (17 mi),Jacques Anquetil (FRA)
25,P,1 July,Individual time trial,7.3 km (4.5 mi),Jacky Durand (FRA)
26,1,2 July,Plain stage,233.5 km (145.1 mi),Fabio Baldato (ITA)
27,2,3 July,Plain stage,235.5 km (146.3 mi),Mario Cipollini (ITA)
28,3,4 July,Team time trial,67.0 km (41.6 mi),Gewiss-Ballan (ITA)
29,4,5 July,Plain stage,162.0 km (100.7 mi),Mario Cipollini (ITA)
30,5,6 July,Plain stage,261.0 km (162.2 mi),Jeroen Blijlevens (NED)
31,6,7 July,Plain stage,202.0 km (125.5 mi),Erik Zabel (GER)
32,7,8 July,Hilly stage,203.0 km (126.1 mi),Johan Bruyneel (BEL)
33,8,9 July,Individual time trial,54.0 km (33.6 mi),Miguel Indurain (ESP)
34,9,11 July,Stage with mountain(s),160.0 km (99.4 mi),Alex Zulle (SUI)
35,10,12 July,Stage with mountain(s),162.5 km (101.0 mi),Marco Pantani (ITA)
36,11,13 July,Hilly stage,199.0 km (123.7 mi),Maximilian Sciandri (GBR)
37,12,14 July,Hilly stage,222.5 km (138.3 mi),Laurent Jalabert (FRA)
38,13,15 July,Plain stage,245.0 km (152.2 mi),Serhiy Utchakov (UKR)
39,14,16 July,Stage with mountain(s),164.0 km (101.9 mi),Marco Pantani (ITA)
40,15,18 July,Stage with mountain(s),206.0 km (128.0 mi),Richard Virenque (FRA)
41,16,19 July,Stage with mountain(s),149.0 km (92.6 mi),Cancelled
42,17,20 July,Plain stage,246.0 km (152.9 mi),Erik Zabel (GER)
43,18,21 July,Plain stage,166.5 km (103.5 mi),Lance Armstrong (USA)
44,19,22 July,Individual time trial,46.5 km (28.9 mi),Miguel Indurain (ESP)
45,20,23 July,Plain stage,155.0 km (96.3 mi),Djamolidine Abduzhaparov (UZB)

22.csv : 203_44.csv		204_312.csv
Missing Values(NANs):  {'phase': '0/50', 'date': '0/50', 'terrain': '0/50', 'length': '0/50', 'race winner': '0/50'}
Columns that match with input_schema:
203_44.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
204_312.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
Coverage Score :  0.8333333333333334 	 Completeness Score :  0.8333333333333334

,phase,date,terrain,length,race winner
0,1,22 June,Plain stage,215 km (134 mi),Edward Sels (BEL)
1,2,23 June,Plain stage,208 km (129 mi),Andre Darrigade (FRA)
2,3A,24 June,Plain stage,197 km (122 mi),Bernard Vandekerkhove (BEL)
3,3B,24 June,Team time trial,21 km (13 mi),Kas-Kaskol
4,4,25 June,Plain stage,292 km (181 mi),Rudi Altig (GER)
5,5,26 June,Plain stage,161 km (100 mi),Willy Derboven (BEL)
6,6,27 June,Plain stage,200 km (120 mi),Henk Nijdam (NED)
7,7,28 June,Plain stage,195 km (121 mi),Jan Janssen (NED)
8,8,29 June,Stage with mountain(s),249 km (155 mi),Federico Bahamontes (ESP)
9,9,30 June,Stage with mountain(s),239 km (149 mi),Jacques Anquetil (FRA)
10,10A,1 July,Plain stage,187 km (116 mi),Jan Janssen (NED)
11,10B,1 July,Individual time trial,21 km (13 mi),Jacques Anquetil (FRA)
12,11,2 July,Plain stage,250 km (160 mi),Edward Sels (BEL)
13,12,3 July,Plain stage,174 km (108 mi),Jo de Roo (NED)
14,13,4 July,Stage with mountain(s),170 km (110 mi),Julio Jimenez (ESP)
15,14,6 July,Stage with mountain(s),186 km (116 mi),Edward Sels (BEL)
16,15,7 July,Stage with mountain(s),203 km (126 mi),Raymond Poulidor (FRA)
17,16,8 July,Stage with mountain(s),197 km (122 mi),Federico Bahamontes (ESP)
18,17,9 July,Individual time trial,43 km (27 mi),Jacques Anquetil (FRA)
19,18,10 July,Plain stage,187 km (116 mi),Andre Darrigade (FRA)
20,19,11 July,Plain stage,215 km (134 mi),Edward Sels (BEL)
21,20,12 July,Stage with mountain(s),217 km (135 mi),Julio Jimenez (ESP)
22,21,13 July,Plain stage,311 km (193 mi),Jean Stablinski (FRA)
23,22A,14 July,Plain stage,119 km (74 mi),Benoni Beheyt (BEL)
24,22B,14 July,Individual time trial,27 km (17 mi),Jacques Anquetil (FRA)
25,P,29 June,Individual time trial,5 km (3.1 mi),Jan Raas (NED)
26,1A,30 June,Plain stage,135 km (84 mi),Jan Raas (NED)
27,1B,30 June,Plain stage,100 km (62 mi),Walter Planckaert (BEL)
28,2,1 July,Plain stage,199 km (124 mi),Jacques Esclassan (FRA)
29,3,2 July,Plain stage,244 km (152 mi),Klaus-Peter Thaler (GER)
30,4,3 July,Team time trial,153 km (95 mi),TI-Raleigh
31,5,4 July,Plain stage,244 km (152 mi),Freddy Maertens (BEL)
32,6,5 July,Plain stage,162 km (101 mi),Sean Kelly (IRE)
33,7,6 July,Plain stage,242 km (150 mi),Freddy Maertens (BEL)
34,8,7 July,Individual time trial,59 km (37 mi),Bernard Hinault (FRA)
35,9,8 July,Plain stage,233 km (145 mi),Miguel Maria Lasa (ESP)
36,10,10 July,Hilly stage,192 km (119 mi),Henk Lubberding (NED)
37,11,11 July,Stage with mountain(s),161 km (100 mi),Mariano Martinez (FRA)
38,12A,12 July,Plain stage,158 km (98 mi),Cancelled
39,12B,12 July,Plain stage,96 km (60 mi),Jacques Esclassan (FRA)
40,13,13 July,Hilly stage,221 km (137 mi),Paul Wellens (BEL)
41,14,14 July,Individual time trial,52 km (32 mi),Joop Zoetemelk (NED)
42,15,15 July,Hilly stage,196 km (122 mi),Bernard Hinault (FRA)
43,16,16 July,Stage with mountain(s),241 km (150 mi),Hennie Kuiper (NED)
44,17,18 July,Stage with mountain(s),225 km (140 mi),Christian Seznec (FRA)
45,18,19 July,Plain stage,137 km (85 mi),Gerrie Knetemann (NED)
46,19,20 July,Plain stage,182 km (113 mi),Marc Demeyer (BEL)
47,20,21 July,Individual time trial,72 km (45 mi),Bernard Hinault (FRA)
48,21,22 July,Plain stage,207 km (129 mi),Jan Raas (NED)
49,22,23 July,Plain stage,162 km (101 mi),Gerrie Knetemann (NED)

23.csv : 203_44.csv		204_406.csv
Missing Values(NANs):  {'phase': '24/49', 'date': '0/49', 'terrain': '0/49', 'length': '0/49', 'race winner': '0/49', 'leader': '25/49'}
Columns that match with input_schema:
203_44.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
204_406.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'winner': 'race winner', 'race leader': 'leader'}
Coverage Score :  1.0 	 Completeness Score :  0.8333333333333331

,phase,date,terrain,length,race winner,leader
0,1,22 June,Plain stage,215 km (134 mi),Edward Sels (BEL),NaN
1,2,23 June,Plain stage,208 km (129 mi),Andre Darrigade (FRA),NaN
2,3A,24 June,Plain stage,197 km (122 mi),Bernard Vandekerkhove (BEL),NaN
3,3B,24 June,Team time trial,21 km (13 mi),Kas-Kaskol,NaN
4,4,25 June,Plain stage,292 km (181 mi),Rudi Altig (GER),NaN
5,5,26 June,Plain stage,161 km (100 mi),Willy Derboven (BEL),NaN
6,6,27 June,Plain stage,200 km (120 mi),Henk Nijdam (NED),NaN
7,7,28 June,Plain stage,195 km (121 mi),Jan Janssen (NED),NaN
8,8,29 June,Stage with mountain(s),249 km (155 mi),Federico Bahamontes (ESP),NaN
9,9,30 June,Stage with mountain(s),239 km (149 mi),Jacques Anquetil (FRA),NaN
10,10A,1 July,Plain stage,187 km (116 mi),Jan Janssen (NED),NaN
11,10B,1 July,Individual time trial,21 km (13 mi),Jacques Anquetil (FRA),NaN
12,11,2 July,Plain stage,250 km (160 mi),Edward Sels (BEL),NaN
13,12,3 July,Plain stage,174 km (108 mi),Jo de Roo (NED),NaN
14,13,4 July,Stage with mountain(s),170 km (110 mi),Julio Jimenez (ESP),NaN
15,14,6 July,Stage with mountain(s),186 km (116 mi),Edward Sels (BEL),NaN
16,15,7 July,Stage with mountain(s),203 km (126 mi),Raymond Poulidor (FRA),NaN
17,16,8 July,Stage with mountain(s),197 km (122 mi),Federico Bahamontes (ESP),NaN
18,17,9 July,Individual time trial,43 km (27 mi),Jacques Anquetil (FRA),NaN
19,18,10 July,Plain stage,187 km (116 mi),Andre Darrigade (FRA),NaN
20,19,11 July,Plain stage,215 km (134 mi),Edward Sels (BEL),NaN
21,20,12 July,Stage with mountain(s),217 km (135 mi),Julio Jimenez (ESP),NaN
22,21,13 July,Plain stage,311 km (193 mi),Jean Stablinski (FRA),NaN
23,22A,14 July,Plain stage,119 km (74 mi),Benoni Beheyt (BEL),NaN
24,22B,14 July,Individual time trial,27 km (17 mi),Jacques Anquetil (FRA),NaN
25,NaN,30 June,Plain stage,208 km (129 mi),Alfred Haemerlinck (BEL),Alfred Haemerlinck (BEL)
26,NaN,1 July,Plain stage,212 km (132 mi),Max Bulla (AUT),Max Bulla (AUT)
27,NaN,2 July,Plain stage,206 km (128 mi),Fabio Battesini (ITA),Leon Le Calvez (FRA)
28,NaN,3 July,Plain stage,211 km (131 mi),Andre Godinat (FRA),Rafaele di Paco (ITA)
29,NaN,4 July,Plain stage,202 km (126 mi),Charles Pelissier (FRA),Charles Pelissier (FRA) Rafaele di Paco (ITA)
30,NaN,5 July,Plain stage,338 km (210 mi),Alfred Haemerlinck (BEL),Rafaele di Paco (ITA)
31,NaN,6 July,Plain stage,180 km (110 mi),Gerard Loncke (BEL),Rafaele di Paco (ITA)
32,NaN,7 July,Plain stage,106 km (66 mi),Charles Pelissier (FRA),Charles Pelissier (FRA)
33,NaN,8 July,Stage with mountain(s),231 km (144 mi),Antonin Magne (FRA),Antonin Magne (FRA)
34,NaN,10 July,Stage with mountain(s),322 km (200 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
35,NaN,12 July,Plain stage,164 km (102 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
36,NaN,13 July,Plain stage,207 km (129 mi),Max Bulla (AUT),Antonin Magne (FRA)
37,NaN,14 July,Plain stage,181 km (112 mi),Charles Pelissier (FRA),Antonin Magne (FRA)
38,NaN,15 July,Stage with mountain(s),132 km (82 mi),Eugenio Gestri (ITA),Antonin Magne (FRA)
39,NaN,17 July,Stage with mountain(s),233 km (145 mi),Jef Demuysere (BEL),Antonin Magne (FRA)
40,NaN,18 July,Stage with mountain(s),102 km (63 mi),Charles Pelissier (FRA),Antonin Magne (FRA)
41,NaN,19 July,Stage with mountain(s),230 km (140 mi),Max Bulla (AUT),Antonin Magne (FRA)
42,NaN,20 July,Stage with mountain(s),204 km (127 mi),Jef Demuysere (BEL),Antonin Magne (FRA)
43,NaN,21 July,Stage with mountain(s),282 km (175 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
44,NaN,22 July,Stage with mountain(s),209 km (130 mi),Andre Leducq (FRA),Antonin Magne (FRA)
45,NaN,23 July,Plain stage,192 km (119 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
46,NaN,24 July,Plain stage,159 km (99 mi),Raffaele di Paco (ITA),Antonin Magne (FRA)
47,NaN,25 July,Plain stage,271 km (168 mi),Gaston Rebry (BEL),Antonin Magne (FRA)
48,NaN,26 July,Plain stage,313 km (194 mi),Charles Pelissier (FRA),Antonin Magne (FRA)

24.csv : 203_475.csv		204_312.csv
Missing Values(NANs):  {'phase': '0/46', 'date': '0/46', 'terrain': '0/46', 'length': '0/46', 'race winner': '0/46'}
Columns that match with input_schema:
203_475.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
204_312.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
Coverage Score :  0.8333333333333334 	 Completeness Score :  0.8333333333333334

,phase,date,terrain,length,race winner
0,P,1 July,Individual time trial,7.3 km (4.5 mi),Jacky Durand (FRA)
1,1,2 July,Plain stage,233.5 km (145.1 mi),Fabio Baldato (ITA)
2,2,3 July,Plain stage,235.5 km (146.3 mi),Mario Cipollini (ITA)
3,3,4 July,Team time trial,67.0 km (41.6 mi),Gewiss-Ballan (ITA)
4,4,5 July,Plain stage,162.0 km (100.7 mi),Mario Cipollini (ITA)
5,5,6 July,Plain stage,261.0 km (162.2 mi),Jeroen Blijlevens (NED)
6,6,7 July,Plain stage,202.0 km (125.5 mi),Erik Zabel (GER)
7,7,8 July,Hilly stage,203.0 km (126.1 mi),Johan Bruyneel (BEL)
8,8,9 July,Individual time trial,54.0 km (33.6 mi),Miguel Indurain (ESP)
9,9,11 July,Stage with mountain(s),160.0 km (99.4 mi),Alex Zulle (SUI)
10,10,12 July,Stage with mountain(s),162.5 km (101.0 mi),Marco Pantani (ITA)
11,11,13 July,Hilly stage,199.0 km (123.7 mi),Maximilian Sciandri (GBR)
12,12,14 July,Hilly stage,222.5 km (138.3 mi),Laurent Jalabert (FRA)
13,13,15 July,Plain stage,245.0 km (152.2 mi),Serhiy Utchakov (UKR)
14,14,16 July,Stage with mountain(s),164.0 km (101.9 mi),Marco Pantani (ITA)
15,15,18 July,Stage with mountain(s),206.0 km (128.0 mi),Richard Virenque (FRA)
16,16,19 July,Stage with mountain(s),149.0 km (92.6 mi),Cancelled
17,17,20 July,Plain stage,246.0 km (152.9 mi),Erik Zabel (GER)
18,18,21 July,Plain stage,166.5 km (103.5 mi),Lance Armstrong (USA)
19,19,22 July,Individual time trial,46.5 km (28.9 mi),Miguel Indurain (ESP)
20,20,23 July,Plain stage,155.0 km (96.3 mi),Djamolidine Abduzhaparov (UZB)
21,P,29 June,Individual time trial,5 km (3.1 mi),Jan Raas (NED)
22,1A,30 June,Plain stage,135 km (84 mi),Jan Raas (NED)
23,1B,30 June,Plain stage,100 km (62 mi),Walter Planckaert (BEL)
24,2,1 July,Plain stage,199 km (124 mi),Jacques Esclassan (FRA)
25,3,2 July,Plain stage,244 km (152 mi),Klaus-Peter Thaler (GER)
26,4,3 July,Team time trial,153 km (95 mi),TI-Raleigh
27,5,4 July,Plain stage,244 km (152 mi),Freddy Maertens (BEL)
28,6,5 July,Plain stage,162 km (101 mi),Sean Kelly (IRE)
29,7,6 July,Plain stage,242 km (150 mi),Freddy Maertens (BEL)
30,8,7 July,Individual time trial,59 km (37 mi),Bernard Hinault (FRA)
31,9,8 July,Plain stage,233 km (145 mi),Miguel Maria Lasa (ESP)
32,10,10 July,Hilly stage,192 km (119 mi),Henk Lubberding (NED)
33,11,11 July,Stage with mountain(s),161 km (100 mi),Mariano Martinez (FRA)
34,12A,12 July,Plain stage,158 km (98 mi),Cancelled
35,12B,12 July,Plain stage,96 km (60 mi),Jacques Esclassan (FRA)
36,13,13 July,Hilly stage,221 km (137 mi),Paul Wellens (BEL)
37,14,14 July,Individual time trial,52 km (32 mi),Joop Zoetemelk (NED)
38,15,15 July,Hilly stage,196 km (122 mi),Bernard Hinault (FRA)
39,16,16 July,Stage with mountain(s),241 km (150 mi),Hennie Kuiper (NED)
40,17,18 July,Stage with mountain(s),225 km (140 mi),Christian Seznec (FRA)
41,18,19 July,Plain stage,137 km (85 mi),Gerrie Knetemann (NED)
42,19,20 July,Plain stage,182 km (113 mi),Marc Demeyer (BEL)
43,20,21 July,Individual time trial,72 km (45 mi),Bernard Hinault (FRA)
44,21,22 July,Plain stage,207 km (129 mi),Jan Raas (NED)
45,22,23 July,Plain stage,162 km (101 mi),Gerrie Knetemann (NED)

25.csv : 203_475.csv		204_406.csv
Missing Values(NANs):  {'phase': '24/45', 'date': '0/45', 'terrain': '0/45', 'length': '0/45', 'race winner': '0/45', 'leader': '21/45'}
Columns that match with input_schema:
203_475.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
204_406.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'winner': 'race winner', 'race leader': 'leader'}
Coverage Score :  1.0 	 Completeness Score :  0.8333333333333334

,phase,date,terrain,length,race winner,leader
0,P,1 July,Individual time trial,7.3 km (4.5 mi),Jacky Durand (FRA),NaN
1,1,2 July,Plain stage,233.5 km (145.1 mi),Fabio Baldato (ITA),NaN
2,2,3 July,Plain stage,235.5 km (146.3 mi),Mario Cipollini (ITA),NaN
3,3,4 July,Team time trial,67.0 km (41.6 mi),Gewiss-Ballan (ITA),NaN
4,4,5 July,Plain stage,162.0 km (100.7 mi),Mario Cipollini (ITA),NaN
5,5,6 July,Plain stage,261.0 km (162.2 mi),Jeroen Blijlevens (NED),NaN
6,6,7 July,Plain stage,202.0 km (125.5 mi),Erik Zabel (GER),NaN
7,7,8 July,Hilly stage,203.0 km (126.1 mi),Johan Bruyneel (BEL),NaN
8,8,9 July,Individual time trial,54.0 km (33.6 mi),Miguel Indurain (ESP),NaN
9,9,11 July,Stage with mountain(s),160.0 km (99.4 mi),Alex Zulle (SUI),NaN
10,10,12 July,Stage with mountain(s),162.5 km (101.0 mi),Marco Pantani (ITA),NaN
11,11,13 July,Hilly stage,199.0 km (123.7 mi),Maximilian Sciandri (GBR),NaN
12,12,14 July,Hilly stage,222.5 km (138.3 mi),Laurent Jalabert (FRA),NaN
13,13,15 July,Plain stage,245.0 km (152.2 mi),Serhiy Utchakov (UKR),NaN
14,14,16 July,Stage with mountain(s),164.0 km (101.9 mi),Marco Pantani (ITA),NaN
15,15,18 July,Stage with mountain(s),206.0 km (128.0 mi),Richard Virenque (FRA),NaN
16,16,19 July,Stage with mountain(s),149.0 km (92.6 mi),Cancelled,NaN
17,17,20 July,Plain stage,246.0 km (152.9 mi),Erik Zabel (GER),NaN
18,18,21 July,Plain stage,166.5 km (103.5 mi),Lance Armstrong (USA),NaN
19,19,22 July,Individual time trial,46.5 km (28.9 mi),Miguel Indurain (ESP),NaN
20,20,23 July,Plain stage,155.0 km (96.3 mi),Djamolidine Abduzhaparov (UZB),NaN
21,NaN,30 June,Plain stage,208 km (129 mi),Alfred Haemerlinck (BEL),Alfred Haemerlinck (BEL)
22,NaN,1 July,Plain stage,212 km (132 mi),Max Bulla (AUT),Max Bulla (AUT)
23,NaN,2 July,Plain stage,206 km (128 mi),Fabio Battesini (ITA),Leon Le Calvez (FRA)
24,NaN,3 July,Plain stage,211 km (131 mi),Andre Godinat (FRA),Rafaele di Paco (ITA)
25,NaN,4 July,Plain stage,202 km (126 mi),Charles Pelissier (FRA),Charles Pelissier (FRA) Rafaele di Paco (ITA)
26,NaN,5 July,Plain stage,338 km (210 mi),Alfred Haemerlinck (BEL),Rafaele di Paco (ITA)
27,NaN,6 July,Plain stage,180 km (110 mi),Gerard Loncke (BEL),Rafaele di Paco (ITA)
28,NaN,7 July,Plain stage,106 km (66 mi),Charles Pelissier (FRA),Charles Pelissier (FRA)
29,NaN,8 July,Stage with mountain(s),231 km (144 mi),Antonin Magne (FRA),Antonin Magne (FRA)
30,NaN,10 July,Stage with mountain(s),322 km (200 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
31,NaN,12 July,Plain stage,164 km (102 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
32,NaN,13 July,Plain stage,207 km (129 mi),Max Bulla (AUT),Antonin Magne (FRA)
33,NaN,14 July,Plain stage,181 km (112 mi),Charles Pelissier (FRA),Antonin Magne (FRA)
34,NaN,15 July,Stage with mountain(s),132 km (82 mi),Eugenio Gestri (ITA),Antonin Magne (FRA)
35,NaN,17 July,Stage with mountain(s),233 km (145 mi),Jef Demuysere (BEL),Antonin Magne (FRA)
36,NaN,18 July,Stage with mountain(s),102 km (63 mi),Charles Pelissier (FRA),Antonin Magne (FRA)
37,NaN,19 July,Stage with mountain(s),230 km (140 mi),Max Bulla (AUT),Antonin Magne (FRA)
38,NaN,20 July,Stage with mountain(s),204 km (127 mi),Jef Demuysere (BEL),Antonin Magne (FRA)
39,NaN,21 July,Stage with mountain(s),282 km (175 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
40,NaN,22 July,Stage with mountain(s),209 km (130 mi),Andre Leducq (FRA),Antonin Magne (FRA)
41,NaN,23 July,Plain stage,192 km (119 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
42,NaN,24 July,Plain stage,159 km (99 mi),Raffaele di Paco (ITA),Antonin Magne (FRA)
43,NaN,25 July,Plain stage,271 km (168 mi),Gaston Rebry (BEL),Antonin Magne (FRA)
44,NaN,26 July,Plain stage,313 km (194 mi),Charles Pelissier (FRA),Antonin Magne (FRA)

26.csv : 204_312.csv		204_406.csv
Missing Values(NANs):  {'phase': '24/49', 'date': '0/49', 'terrain': '0/49', 'length': '0/49', 'race winner': '0/49', 'leader': '25/49'}
Columns that match with input_schema:
204_312.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'stage': 'phase', 'winner': 'race winner'}
204_406.csv :  {'date': 'date', 'terrain': 'terrain', 'length': 'length', 'winner': 'race winner', 'race leader': 'leader'}
Coverage Score :  1.0 	 Completeness Score :  0.8333333333333331

,phase,date,terrain,length,race winner,leader
0,P,29 June,Individual time trial,5 km (3.1 mi),Jan Raas (NED),NaN
1,1A,30 June,Plain stage,135 km (84 mi),Jan Raas (NED),NaN
2,1B,30 June,Plain stage,100 km (62 mi),Walter Planckaert (BEL),NaN
3,2,1 July,Plain stage,199 km (124 mi),Jacques Esclassan (FRA),NaN
4,3,2 July,Plain stage,244 km (152 mi),Klaus-Peter Thaler (GER),NaN
5,4,3 July,Team time trial,153 km (95 mi),TI-Raleigh,NaN
6,5,4 July,Plain stage,244 km (152 mi),Freddy Maertens (BEL),NaN
7,6,5 July,Plain stage,162 km (101 mi),Sean Kelly (IRE),NaN
8,7,6 July,Plain stage,242 km (150 mi),Freddy Maertens (BEL),NaN
9,8,7 July,Individual time trial,59 km (37 mi),Bernard Hinault (FRA),NaN
10,9,8 July,Plain stage,233 km (145 mi),Miguel Maria Lasa (ESP),NaN
11,10,10 July,Hilly stage,192 km (119 mi),Henk Lubberding (NED),NaN
12,11,11 July,Stage with mountain(s),161 km (100 mi),Mariano Martinez (FRA),NaN
13,12A,12 July,Plain stage,158 km (98 mi),Cancelled,NaN
14,12B,12 July,Plain stage,96 km (60 mi),Jacques Esclassan (FRA),NaN
15,13,13 July,Hilly stage,221 km (137 mi),Paul Wellens (BEL),NaN
16,14,14 July,Individual time trial,52 km (32 mi),Joop Zoetemelk (NED),NaN
17,15,15 July,Hilly stage,196 km (122 mi),Bernard Hinault (FRA),NaN
18,16,16 July,Stage with mountain(s),241 km (150 mi),Hennie Kuiper (NED),NaN
19,17,18 July,Stage with mountain(s),225 km (140 mi),Christian Seznec (FRA),NaN
20,18,19 July,Plain stage,137 km (85 mi),Gerrie Knetemann (NED),NaN
21,19,20 July,Plain stage,182 km (113 mi),Marc Demeyer (BEL),NaN
22,20,21 July,Individual time trial,72 km (45 mi),Bernard Hinault (FRA),NaN
23,21,22 July,Plain stage,207 km (129 mi),Jan Raas (NED),NaN
24,22,23 July,Plain stage,162 km (101 mi),Gerrie Knetemann (NED),NaN
25,NaN,30 June,Plain stage,208 km (129 mi),Alfred Haemerlinck (BEL),Alfred Haemerlinck (BEL)
26,NaN,1 July,Plain stage,212 km (132 mi),Max Bulla (AUT),Max Bulla (AUT)
27,NaN,2 July,Plain stage,206 km (128 mi),Fabio Battesini (ITA),Leon Le Calvez (FRA)
28,NaN,3 July,Plain stage,211 km (131 mi),Andre Godinat (FRA),Rafaele di Paco (ITA)
29,NaN,4 July,Plain stage,202 km (126 mi),Charles Pelissier (FRA),Charles Pelissier (FRA) Rafaele di Paco (ITA)
30,NaN,5 July,Plain stage,338 km (210 mi),Alfred Haemerlinck (BEL),Rafaele di Paco (ITA)
31,NaN,6 July,Plain stage,180 km (110 mi),Gerard Loncke (BEL),Rafaele di Paco (ITA)
32,NaN,7 July,Plain stage,106 km (66 mi),Charles Pelissier (FRA),Charles Pelissier (FRA)
33,NaN,8 July,Stage with mountain(s),231 km (144 mi),Antonin Magne (FRA),Antonin Magne (FRA)
34,NaN,10 July,Stage with mountain(s),322 km (200 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
35,NaN,12 July,Plain stage,164 km (102 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
36,NaN,13 July,Plain stage,207 km (129 mi),Max Bulla (AUT),Antonin Magne (FRA)
37,NaN,14 July,Plain stage,181 km (112 mi),Charles Pelissier (FRA),Antonin Magne (FRA)
38,NaN,15 July,Stage with mountain(s),132 km (82 mi),Eugenio Gestri (ITA),Antonin Magne (FRA)
39,NaN,17 July,Stage with mountain(s),233 km (145 mi),Jef Demuysere (BEL),Antonin Magne (FRA)
40,NaN,18 July,Stage with mountain(s),102 km (63 mi),Charles Pelissier (FRA),Antonin Magne (FRA)
41,NaN,19 July,Stage with mountain(s),230 km (140 mi),Max Bulla (AUT),Antonin Magne (FRA)
42,NaN,20 July,Stage with mountain(s),204 km (127 mi),Jef Demuysere (BEL),Antonin Magne (FRA)
43,NaN,21 July,Stage with mountain(s),282 km (175 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
44,NaN,22 July,Stage with mountain(s),209 km (130 mi),Andre Leducq (FRA),Antonin Magne (FRA)
45,NaN,23 July,Plain stage,192 km (119 mi),Rafaele di Paco (ITA),Antonin Magne (FRA)
46,NaN,24 July,Plain stage,159 km (99 mi),Raffaele di Paco (ITA),Antonin Magne (FRA)
47,NaN,25 July,Plain stage,271 km (168 mi),Gaston Rebry (BEL),Antonin Magne (FRA)
48,NaN,26 July,Plain stage,313 km (194 mi),Charles Pelissier (FRA),Antonin Magne (FRA)

Rank  1   :  output_1.csv         completeness score : 0.8333333333333335 		number of rows:  118
Rank  2   :  output_4.csv         completeness score : 0.8333333333333334 		number of rows:  97
Rank  3   :  output_6.csv         completeness score : 0.8333333333333334 		number of rows:  95
Rank  4   :  output_2.csv         completeness score : 0.8333333333333334 		number of rows:  94
Rank  5   :  output_3.csv         completeness score : 0.8333333333333334 		number of rows:  93
Rank  6   :  output_5.csv         completeness score : 0.8333333333333334 		number of rows:  93
Rank  7   :  output_15.csv        completeness score : 0.8333333333333334 		number of rows:  74
Rank  8   :  output_8.csv         completeness score : 0.8333333333333334 		number of rows:  73
Rank  9   :  output_13.csv        completeness score : 0.8333333333333334 		number of rows:  71
Rank  10  :  output_7.csv         completeness score : 0.8333333333333334 		number of rows:  69
Rank  11  :  output_10.csv        completeness score : 0.8333333333333334 		number of rows:  69
Rank  12  :  output_22.csv        completeness score : 0.8333333333333334 		number of rows:  50
Rank  13  :  output_17.csv        completeness score : 0.8333333333333334 		number of rows:  48
Rank  14  :  output_19.csv        completeness score : 0.8333333333333334 		number of rows:  48
Rank  15  :  output_20.csv        completeness score : 0.8333333333333334 		number of rows:  47
Rank  16  :  output_21.csv        completeness score : 0.8333333333333334 		number of rows:  46
Rank  17  :  output_24.csv        completeness score : 0.8333333333333334 		number of rows:  46
Rank  18  :  output_25.csv        completeness score : 0.8333333333333334 		number of rows:  45
Rank  19  :  output_18.csv        completeness score : 0.8333333333333334 		number of rows:  44
Rank  20  :  203_44.csv           completeness score : 0.8333333333333334 		number of rows:  25
Rank  21  :  204_312.csv          completeness score : 0.8333333333333334 		number of rows:  25
Rank  22  :  204_406.csv          completeness score : 0.8333333333333334 		number of rows:  24
Rank  23  :  203_25.csv           completeness score : 0.8333333333333334 		number of rows:  23
Rank  24  :  203_475.csv          completeness score : 0.8333333333333334 		number of rows:  21
Rank  25  :  output_9.csv         completeness score : 0.8333333333333331 		number of rows:  72
Rank  26  :  output_12.csv        completeness score : 0.8333333333333331 		number of rows:  72
Rank  27  :  output_14.csv        completeness score : 0.8333333333333331 		number of rows:  70
Rank  28  :  output_16.csv        completeness score : 0.8333333333333331 		number of rows:  70
Rank  29  :  output_11.csv        completeness score : 0.8333333333333331 		number of rows:  68
Rank  30  :  output_23.csv        completeness score : 0.8333333333333331 		number of rows:  49
Rank  31  :  output_26.csv        completeness score : 0.8333333333333331 		number of rows:  49

Ranking Complete!!

In [88]:
# Query 5 : Results
s='{"schema": {"team 1": "object", "team 2": "object"}, "categories": ["football"]}'
s=s.lower()
s=json.loads(s)
input_schema=s['schema'];input_categories=-1;transformations=-1;stats=-1
if "categories" in s:
    input_categories=s["categories"]
if "transformations" in s:
    transformations=s["transformations"]
if "stats" in s:
    stats=s["stats"]
# display query
print("Input Schema : ",input_schema)
if input_categories==-1:
    print("Input Categories : None")
else:
    print("Input Categories : ",input_categories)
if transformations==-1:
    print("Input Transformations : None")
else:
    print("Input Transformations : ",transformations)
if stats==-1:
    print("Input Condition based conditions : None")
else:
    print("Input Content based Conditions : ",stats)
print()
comp_score={}
no_of_rows={}
no_of_rows={}
get_matches()

Input Schema :  {'team 1': 'object', 'team 2': 'object'}
Input Categories :  ['football']
Input Transformations : None
Input Condition based conditions : None

category and schema
Matching Tables
203_414.csv  :  2008-09 Copa del Rey
203_526.csv  :  2006 UEFA European Under-21 Championship qualification
204_405.csv  :  2011-12 Taca da Liga
204_510.csv  :  2010-11 UEFA Europa League
204_702.csv  :  1977-78 Copa del Rey


203_414.csv(2008-09 Copa del Rey)
Missing Values(NANs score):  {'team 1': '0/16', 'team 2': '0/16'}
Columns that match with input_schema:
 203_414.csv :  {'team 1': 'team 1', 'team 2': 'team 2'}
Coverage Score :  1.0 	 Completeness Score :  1.0

            team 1       team 2
0       Real Union  Real Madrid
1      Portugalete     Valencia
2     Ponferradina      Sevilla
3         Orihuela     Atletico
4       Poli Ejido   Villarreal
5         Hercules   Valladolid
6   Rayo Vallecano      Almeria
7            Celta     Espanyol
8        Castellon        Betis
9      Real Murcia       Racing
10          Málaga     Mallorca
11        Athletic   Recreativo
12          Getafe      Osasuna
13        Benidorm    Barcelona
14           Elche    Deportivo
15        Numancia     Sporting

203_526.csv(2006 UEFA European Under-21 Championship qualification)
Missing Values(NANs score):  {'team 1': '0/8', 'team 2': '0/8'}
Columns that match with input_schema:
 203_526.csv :  {'team 1': 'team 1', 'team 2': 'team 2'}
Coverage Score :  1.0 	 Completeness Score :  1.0

                  team 1       team 2
0                England       France
1         Czech Republic      Germany
2                Hungary        Italy
3  Serbia and Montenegro      Croatia
4                Ukraine      Belgium
5                 Russia      Denmark
6            Switzerland     Portugal
7               Slovenia  Netherlands

204_405.csv(2011-12 Taca da Liga)
Missing Values(NANs score):  {'team 1': '0/8', 'team 2': '0/8'}
Columns that match with input_schema:
 204_405.csv :  {'team 1': 'team 1', 'team 2': 'team 2'}
Coverage Score :  1.0 	 Completeness Score :  1.0

             team 1              team 2
0  União da Madeira            Maritimo
1          Penafiel           Academica
2       Santa Clara     União de Leiria
3             Naval  Vitoria de Setúbal
4        Moreirense           Beira-Mar
5      Portimonense            Feirense
6           Estoril           Olhanense
7        Belenenses         Gil Vicente

204_510.csv(2010-11 UEFA Europa League)
Missing Values(NANs score):  {'team 1': '0/8', 'team 2': '0/8'}
Columns that match with input_schema:
 204_510.csv :  {'team 1': 'team 1', 'team 2': 'team 2'}
Coverage Score :  1.0 	 Completeness Score :  1.0

             team 1                  team 2
0           Benfica     Paris Saint-Germain
1       Dynamo Kyiv         Manchester City
2            Twente  Zenit Saint Petersburg
3       CSKA Moscow                   Porto
4     PSV Eindhoven                 Rangers
5  Bayer Leverkusen              Villarreal
6              Ajax          Spartak Moscow
7             Braga               Liverpool

204_702.csv(1977-78 Copa del Rey)
Missing Values(NANs score):  {'team 1': '0/42', 'team 2': '0/42'}
Columns that match with input_schema:
 204_702.csv :  {'team 1': 'team 1', 'team 2': 'team 2'}
Coverage Score :  1.0 	 Completeness Score :  1.0

                  team 1                  team 2
0    Valladolid Promesas                   Elche
1             Pena Sport              Valladolid
2              Algeciras             Real Madrid
3   Real Madrid Castilla                Sabadell
4                Leganes                 Eldense
5           Ciempozuelos                  Lleida
6                 Alcalá                Valencia
7                 Burgos                  Huesca
8                  Ceuta                Espanyol
9      Atletico Baleares                   Cádiz
10              Tudelano          Sporting Gijon
11              Figueres        Racing Santander
12           Carabanchel            Calvo Sotelo
13               Almansa          Rayo Vallecano
14               Osasuna             Guadalajara
15             Deportivo               Plasencia
16                Europa                  Málaga
17                  Jaen              Real Union
18             Ontinyent                Torrejon
19                Girona                Alcoyano
20     Valencia Mestalla        Sevilla Atletico
21       Espanol Raspeig                Mirandes
22                Toledo                 Badajoz
23              Talavera                   Arosa
24              Sarinena          Rayo Cantabria
25          San Fernando        Nàstic Tarragona
26               Sevilla             Sant Andreu
27              Orihuela                  Alaves
28                Oviedo        Cultural Leonesa
29               Langreo                 Granada
30         Racing Ferrol             Real Murcia
31               Levante                Moscardo
32         Real Sociedad                   Xerez
33              Marbella  Gimnástica Torrelavega
34               Cordoba         Bilbao Athletic
35            Recreativo                 Linense
36                  Reus                Zaragoza
37                 Celta               Cartagena
38              Tenerife                 Malgrat
39               La Cava                 Linares
40                  Gavà               Castellon
41                Fabril                Hercules

1.csv : 204_405.csv(2011-12 Taca da Liga)		204_510.csv(2010-11 UEFA Europa League)		204_702.csv(1977-78 Copa del Rey)
Missing Values(NANs):  {'team 1': '0/58', 'team 2': '0/58'}
Columns that match with input_schema:
204_405.csv :  {'team 1': 'team 1', 'team 2': 'team 2'}
204_510.csv :  {'team 1': 'team 1', 'team 2': 'team 2'}
204_702.csv :  {'team 1': 'team 1', 'team 2': 'team 2'}
Coverage Score :  1.0 	 Completeness Score :  1.0

                  team 1                  team 2
0       União da Madeira                Maritimo
1               Penafiel               Academica
2            Santa Clara         União de Leiria
3                  Naval      Vitoria de Setúbal
4             Moreirense               Beira-Mar
5           Portimonense                Feirense
6                Estoril               Olhanense
7             Belenenses             Gil Vicente
8                Benfica     Paris Saint-Germain
9            Dynamo Kyiv         Manchester City
10                Twente  Zenit Saint Petersburg
11           CSKA Moscow                   Porto
12         PSV Eindhoven                 Rangers
13      Bayer Leverkusen              Villarreal
14                  Ajax          Spartak Moscow
15                 Braga               Liverpool
16   Valladolid Promesas                   Elche
17            Pena Sport              Valladolid
18             Algeciras             Real Madrid
19  Real Madrid Castilla                Sabadell
20               Leganes                 Eldense
21          Ciempozuelos                  Lleida
22                Alcalá                Valencia
23                Burgos                  Huesca
24                 Ceuta                Espanyol
25     Atletico Baleares                   Cádiz
26              Tudelano          Sporting Gijon
27              Figueres        Racing Santander
28           Carabanchel            Calvo Sotelo
29               Almansa          Rayo Vallecano
30               Osasuna             Guadalajara
31             Deportivo               Plasencia
32                Europa                  Málaga
33                  Jaen              Real Union
34             Ontinyent                Torrejon
35                Girona                Alcoyano
36     Valencia Mestalla        Sevilla Atletico
37       Espanol Raspeig                Mirandes
38                Toledo                 Badajoz
39              Talavera                   Arosa
40              Sarinena          Rayo Cantabria
41          San Fernando        Nàstic Tarragona
42               Sevilla             Sant Andreu
43              Orihuela                  Alaves
44                Oviedo        Cultural Leonesa
45               Langreo                 Granada
46         Racing Ferrol             Real Murcia
47               Levante                Moscardo
48         Real Sociedad                   Xerez
49              Marbella  Gimnástica Torrelavega
50               Cordoba         Bilbao Athletic
51            Recreativo                 Linense
52                  Reus                Zaragoza
53                 Celta               Cartagena
54              Tenerife                 Malgrat
55               La Cava                 Linares
56                  Gavà               Castellon
57                Fabril                Hercules

2.csv : 203_414.csv(2008-09 Copa del Rey)		204_702.csv(1977-78 Copa del Rey)
Missing Values(NANs):  {'team 1': '0/58', 'team 2': '0/58'}
Columns that match with input_schema:
203_414.csv :  {'team 1': 'team 1', 'team 2': 'team 2'}
204_702.csv :  {'team 1': 'team 1', 'team 2': 'team 2'}
Coverage Score :  1.0 	 Completeness Score :  1.0

                  team 1                  team 2
0             Real Union             Real Madrid
1            Portugalete                Valencia
2           Ponferradina                 Sevilla
3               Orihuela                Atletico
4             Poli Ejido              Villarreal
5               Hercules              Valladolid
6         Rayo Vallecano                 Almeria
7                  Celta                Espanyol
8              Castellon                   Betis
9            Real Murcia                  Racing
10                Málaga                Mallorca
11              Athletic              Recreativo
12                Getafe                 Osasuna
13              Benidorm               Barcelona
14                 Elche               Deportivo
15              Numancia                Sporting
16   Valladolid Promesas                   Elche
17            Pena Sport              Valladolid
18             Algeciras             Real Madrid
19  Real Madrid Castilla                Sabadell
20               Leganes                 Eldense
21          Ciempozuelos                  Lleida
22                Alcalá                Valencia
23                Burgos                  Huesca
24                 Ceuta                Espanyol
25     Atletico Baleares                   Cádiz
26              Tudelano          Sporting Gijon
27              Figueres        Racing Santander
28           Carabanchel            Calvo Sotelo
29               Almansa          Rayo Vallecano
30               Osasuna             Guadalajara
31             Deportivo               Plasencia
32                Europa                  Málaga
33                  Jaen              Real Union
34             Ontinyent                Torrejon
35                Girona                Alcoyano
36     Valencia Mestalla        Sevilla Atletico
37       Espanol Raspeig                Mirandes
38                Toledo                 Badajoz
39              Talavera                   Arosa
40              Sarinena          Rayo Cantabria
41          San Fernando        Nàstic Tarragona
42               Sevilla             Sant Andreu
43              Orihuela                  Alaves
44                Oviedo        Cultural Leonesa
45               Langreo                 Granada
46         Racing Ferrol             Real Murcia
47               Levante                Moscardo
48         Real Sociedad                   Xerez
49              Marbella  Gimnástica Torrelavega
50               Cordoba         Bilbao Athletic
51            Recreativo                 Linense
52                  Reus                Zaragoza
53                 Celta               Cartagena
54              Tenerife                 Malgrat
55               La Cava                 Linares
56                  Gavà               Castellon
57                Fabril                Hercules

3.csv : 203_526.csv(2006 UEFA European Under-21 Championship qualification)		204_510.csv(2010-11 UEFA Europa League)
Missing Values(NANs):  {'team 1': '0/16', 'team 2': '0/16'}
Columns that match with input_schema:
203_526.csv :  {'team 1': 'team 1', 'team 2': 'team 2'}
204_510.csv :  {'team 1': 'team 1', 'team 2': 'team 2'}
Coverage Score :  1.0 	 Completeness Score :  1.0

                   team 1                  team 2
0                 England                  France
1          Czech Republic                 Germany
2                 Hungary                   Italy
3   Serbia and Montenegro                 Croatia
4                 Ukraine                 Belgium
5                  Russia                 Denmark
6             Switzerland                Portugal
7                Slovenia             Netherlands
8                 Benfica     Paris Saint-Germain
9             Dynamo Kyiv         Manchester City
10                 Twente  Zenit Saint Petersburg
11            CSKA Moscow                   Porto
12          PSV Eindhoven                 Rangers
13       Bayer Leverkusen              Villarreal
14                   Ajax          Spartak Moscow
15                  Braga               Liverpool

4.csv : 204_405.csv(2011-12 Taca da Liga)		204_510.csv(2010-11 UEFA Europa League)
Missing Values(NANs):  {'team 1': '0/16', 'team 2': '0/16'}
Columns that match with input_schema:
204_405.csv :  {'team 1': 'team 1', 'team 2': 'team 2'}
204_510.csv :  {'team 1': 'team 1', 'team 2': 'team 2'}
Coverage Score :  1.0 	 Completeness Score :  1.0

              team 1                  team 2
0   União da Madeira                Maritimo
1           Penafiel               Academica
2        Santa Clara         União de Leiria
3              Naval      Vitoria de Setúbal
4         Moreirense               Beira-Mar
5       Portimonense                Feirense
6            Estoril               Olhanense
7         Belenenses             Gil Vicente
8            Benfica     Paris Saint-Germain
9        Dynamo Kyiv         Manchester City
10            Twente  Zenit Saint Petersburg
11       CSKA Moscow                   Porto
12     PSV Eindhoven                 Rangers
13  Bayer Leverkusen              Villarreal
14              Ajax          Spartak Moscow
15             Braga               Liverpool

5.csv : 204_405.csv(2011-12 Taca da Liga)		204_702.csv(1977-78 Copa del Rey)
Missing Values(NANs):  {'team 1': '0/50', 'team 2': '0/50'}
Columns that match with input_schema:
204_405.csv :  {'team 1': 'team 1', 'team 2': 'team 2'}
204_702.csv :  {'team 1': 'team 1', 'team 2': 'team 2'}
Coverage Score :  1.0 	 Completeness Score :  1.0

                  team 1                  team 2
0       União da Madeira                Maritimo
1               Penafiel               Academica
2            Santa Clara         União de Leiria
3                  Naval      Vitoria de Setúbal
4             Moreirense               Beira-Mar
5           Portimonense                Feirense
6                Estoril               Olhanense
7             Belenenses             Gil Vicente
8    Valladolid Promesas                   Elche
9             Pena Sport              Valladolid
10             Algeciras             Real Madrid
11  Real Madrid Castilla                Sabadell
12               Leganes                 Eldense
13          Ciempozuelos                  Lleida
14                Alcalá                Valencia
15                Burgos                  Huesca
16                 Ceuta                Espanyol
17     Atletico Baleares                   Cádiz
18              Tudelano          Sporting Gijon
19              Figueres        Racing Santander
20           Carabanchel            Calvo Sotelo
21               Almansa          Rayo Vallecano
22               Osasuna             Guadalajara
23             Deportivo               Plasencia
24                Europa                  Málaga
25                  Jaen              Real Union
26             Ontinyent                Torrejon
27                Girona                Alcoyano
28     Valencia Mestalla        Sevilla Atletico
29       Espanol Raspeig                Mirandes
30                Toledo                 Badajoz
31              Talavera                   Arosa
32              Sarinena          Rayo Cantabria
33          San Fernando        Nàstic Tarragona
34               Sevilla             Sant Andreu
35              Orihuela                  Alaves
36                Oviedo        Cultural Leonesa
37               Langreo                 Granada
38         Racing Ferrol             Real Murcia
39               Levante                Moscardo
40         Real Sociedad                   Xerez
41              Marbella  Gimnástica Torrelavega
42               Cordoba         Bilbao Athletic
43            Recreativo                 Linense
44                  Reus                Zaragoza
45                 Celta               Cartagena
46              Tenerife                 Malgrat
47               La Cava                 Linares
48                  Gavà               Castellon
49                Fabril                Hercules

6.csv : 204_510.csv(2010-11 UEFA Europa League)		204_702.csv(1977-78 Copa del Rey)
Missing Values(NANs):  {'team 1': '0/50', 'team 2': '0/50'}
Columns that match with input_schema:
204_510.csv :  {'team 1': 'team 1', 'team 2': 'team 2'}
204_702.csv :  {'team 1': 'team 1', 'team 2': 'team 2'}
Coverage Score :  1.0 	 Completeness Score :  1.0

                  team 1                  team 2
0                Benfica     Paris Saint-Germain
1            Dynamo Kyiv         Manchester City
2                 Twente  Zenit Saint Petersburg
3            CSKA Moscow                   Porto
4          PSV Eindhoven                 Rangers
5       Bayer Leverkusen              Villarreal
6                   Ajax          Spartak Moscow
7                  Braga               Liverpool
8    Valladolid Promesas                   Elche
9             Pena Sport              Valladolid
10             Algeciras             Real Madrid
11  Real Madrid Castilla                Sabadell
12               Leganes                 Eldense
13          Ciempozuelos                  Lleida
14                Alcalá                Valencia
15                Burgos                  Huesca
16                 Ceuta                Espanyol
17     Atletico Baleares                   Cádiz
18              Tudelano          Sporting Gijon
19              Figueres        Racing Santander
20           Carabanchel            Calvo Sotelo
21               Almansa          Rayo Vallecano
22               Osasuna             Guadalajara
23             Deportivo               Plasencia
24                Europa                  Málaga
25                  Jaen              Real Union
26             Ontinyent                Torrejon
27                Girona                Alcoyano
28     Valencia Mestalla        Sevilla Atletico
29       Espanol Raspeig                Mirandes
30                Toledo                 Badajoz
31              Talavera                   Arosa
32              Sarinena          Rayo Cantabria
33          San Fernando        Nàstic Tarragona
34               Sevilla             Sant Andreu
35              Orihuela                  Alaves
36                Oviedo        Cultural Leonesa
37               Langreo                 Granada
38         Racing Ferrol             Real Murcia
39               Levante                Moscardo
40         Real Sociedad                   Xerez
41              Marbella  Gimnástica Torrelavega
42               Cordoba         Bilbao Athletic
43            Recreativo                 Linense
44                  Reus                Zaragoza
45                 Celta               Cartagena
46              Tenerife                 Malgrat
47               La Cava                 Linares
48                  Gavà               Castellon
49                Fabril                Hercules

Rank  1   :  output_1.csv         completeness score : 1.0000000000000000 		number of rows:  58
Rank  2   :  output_2.csv         completeness score : 1.0000000000000000 		number of rows:  58
Rank  3   :  output_5.csv         completeness score : 1.0000000000000000 		number of rows:  50
Rank  4   :  output_6.csv         completeness score : 1.0000000000000000 		number of rows:  50
Rank  5   :  204_702.csv          completeness score : 1.0000000000000000 		number of rows:  42
Rank  6   :  203_414.csv          completeness score : 1.0000000000000000 		number of rows:  16
Rank  7   :  output_3.csv         completeness score : 1.0000000000000000 		number of rows:  16
Rank  8   :  output_4.csv         completeness score : 1.0000000000000000 		number of rows:  16
Rank  9   :  203_526.csv          completeness score : 1.0000000000000000 		number of rows:  8
Rank  10  :  204_405.csv          completeness score : 1.0000000000000000 		number of rows:  8
Rank  11  :  204_510.csv          completeness score : 1.0000000000000000 		number of rows:  8

Ranking Complete!!

In [83]:
# Query 6 : Results
s='{"schema": {"team 1": "object", "team 2": "object"}, "categories": ["copa", "cups", "rey", "football", "del", "spanish"]}'
s=s.lower()
s=json.loads(s)
input_schema=s['schema'];input_categories=-1;transformations=-1;stats=-1
if "categories" in s:
    input_categories=s["categories"]
if "transformations" in s:
    transformations=s["transformations"]
if "stats" in s:
    stats=s["stats"]
# display query
print("Input Schema : ",input_schema)
if input_categories==-1:
    print("Input Categories : None")
else:
    print("Input Categories : ",input_categories)
if transformations==-1:
    print("Input Transformations : None")
else:
    print("Input Transformations : ",transformations)
if stats==-1:
    print("Input Condition based conditions : None")
else:
    print("Input Content based Conditions : ",stats)
print()
comp_score={}
no_of_rows={}
no_of_rows={}
get_matches()

Input Schema :  {'team 1': 'object', 'team 2': 'object'}
Input Categories :  ['copa', 'cups', 'rey', 'football', 'del', 'spanish']
Input Transformations : None
Input Condition based conditions : None

category and schema
Matching Tables
203_414.csv  :  2008-09 Copa del Rey
204_702.csv  :  1977-78 Copa del Rey


203_414.csv(2008-09 Copa del Rey)
Missing Values(NANs score):  {'team 1': '0/16', 'team 2': '0/16'}
Columns that match with input_schema:
 203_414.csv :  {'team 1': 'team 1', 'team 2': 'team 2'}
Coverage Score :  1.0 	 Completeness Score :  1.0

            team 1       team 2
0       Real Union  Real Madrid
1      Portugalete     Valencia
2     Ponferradina      Sevilla
3         Orihuela     Atletico
4       Poli Ejido   Villarreal
5         Hercules   Valladolid
6   Rayo Vallecano      Almeria
7            Celta     Espanyol
8        Castellon        Betis
9      Real Murcia       Racing
10          Málaga     Mallorca
11        Athletic   Recreativo
12          Getafe      Osasuna
13        Benidorm    Barcelona
14           Elche    Deportivo
15        Numancia     Sporting

204_702.csv(1977-78 Copa del Rey)
Missing Values(NANs score):  {'team 1': '0/42', 'team 2': '0/42'}
Columns that match with input_schema:
 204_702.csv :  {'team 1': 'team 1', 'team 2': 'team 2'}
Coverage Score :  1.0 	 Completeness Score :  1.0

                  team 1                  team 2
0    Valladolid Promesas                   Elche
1             Pena Sport              Valladolid
2              Algeciras             Real Madrid
3   Real Madrid Castilla                Sabadell
4                Leganes                 Eldense
5           Ciempozuelos                  Lleida
6                 Alcalá                Valencia
7                 Burgos                  Huesca
8                  Ceuta                Espanyol
9      Atletico Baleares                   Cádiz
10              Tudelano          Sporting Gijon
11              Figueres        Racing Santander
12           Carabanchel            Calvo Sotelo
13               Almansa          Rayo Vallecano
14               Osasuna             Guadalajara
15             Deportivo               Plasencia
16                Europa                  Málaga
17                  Jaen              Real Union
18             Ontinyent                Torrejon
19                Girona                Alcoyano
20     Valencia Mestalla        Sevilla Atletico
21       Espanol Raspeig                Mirandes
22                Toledo                 Badajoz
23              Talavera                   Arosa
24              Sarinena          Rayo Cantabria
25          San Fernando        Nàstic Tarragona
26               Sevilla             Sant Andreu
27              Orihuela                  Alaves
28                Oviedo        Cultural Leonesa
29               Langreo                 Granada
30         Racing Ferrol             Real Murcia
31               Levante                Moscardo
32         Real Sociedad                   Xerez
33              Marbella  Gimnástica Torrelavega
34               Cordoba         Bilbao Athletic
35            Recreativo                 Linense
36                  Reus                Zaragoza
37                 Celta               Cartagena
38              Tenerife                 Malgrat
39               La Cava                 Linares
40                  Gavà               Castellon
41                Fabril                Hercules

                  team 1                  team 2
0             Real Union             Real Madrid
1            Portugalete                Valencia
2           Ponferradina                 Sevilla
3               Orihuela                Atletico
4             Poli Ejido              Villarreal
5               Hercules              Valladolid
6         Rayo Vallecano                 Almeria
7                  Celta                Espanyol
8              Castellon                   Betis
9            Real Murcia                  Racing
10                Málaga                Mallorca
11              Athletic              Recreativo
12                Getafe                 Osasuna
13              Benidorm               Barcelona
14                 Elche               Deportivo
15              Numancia                Sporting
16   Valladolid Promesas                   Elche
17            Pena Sport              Valladolid
18             Algeciras             Real Madrid
19  Real Madrid Castilla                Sabadell
20               Leganes                 Eldense
21          Ciempozuelos                  Lleida
22                Alcalá                Valencia
23                Burgos                  Huesca
24                 Ceuta                Espanyol
25     Atletico Baleares                   Cádiz
26              Tudelano          Sporting Gijon
27              Figueres        Racing Santander
28           Carabanchel            Calvo Sotelo
29               Almansa          Rayo Vallecano
30               Osasuna             Guadalajara
31             Deportivo               Plasencia
32                Europa                  Málaga
33                  Jaen              Real Union
34             Ontinyent                Torrejon
35                Girona                Alcoyano
36     Valencia Mestalla        Sevilla Atletico
37       Espanol Raspeig                Mirandes
38                Toledo                 Badajoz
39              Talavera                   Arosa
40              Sarinena          Rayo Cantabria
41          San Fernando        Nàstic Tarragona
42               Sevilla             Sant Andreu
43              Orihuela                  Alaves
44                Oviedo        Cultural Leonesa
45               Langreo                 Granada
46         Racing Ferrol             Real Murcia
47               Levante                Moscardo
48         Real Sociedad                   Xerez
49              Marbella  Gimnástica Torrelavega
50               Cordoba         Bilbao Athletic
51            Recreativo                 Linense
52                  Reus                Zaragoza
53                 Celta               Cartagena
54              Tenerife                 Malgrat
55               La Cava                 Linares
56                  Gavà               Castellon
57                Fabril                Hercules

Rank  1   :  output_0.csv         completeness score : 1.0000000000000000 		number of rows:  58
Rank  2   :  204_702.csv          completeness score : 1.0000000000000000 		number of rows:  42
Rank  3   :  203_414.csv          completeness score : 1.0000000000000000 		number of rows:  16

Ranking Complete!!

In [30]:
# Query 7 : Results
s='{"schema": {"name": "object", "builder": "object", "launched": "object", "completed": "object", "fate": "object"}}'
s=s.lower()
s=json.loads(s)
input_schema=s['schema'];input_categories=-1;transformations=-1;stats=-1
if "categories" in s:
    input_categories=s["categories"]
if "transformations" in s:
    transformations=s["transformations"]
if "stats" in s:
    stats=s["stats"]
# display query
print("Input Schema : ",input_schema)
if input_categories==-1:
    print("Input Categories : None")
else:
    print("Input Categories : ",input_categories)
if transformations==-1:
    print("Input Transformations : None")
else:
    print("Input Transformations : ",transformations)
if stats==-1:
    print("Input Condition based conditions : None")
else:
    print("Input Content based Conditions : ",stats)
print()
comp_score={}
no_of_rows={}
no_of_rows={}
get_matches()

Input Schema :  {'name': 'object', 'builder': 'object', 'launched': 'object', 'completed': 'object', 'fate': 'object'}
Input Categories : None
Input Transformations : None
Input Condition based conditions : None

only schema
Matching Tables
203_404.csv  :  J, K and N-class destroyer
204_522.csv  :  Ha-201-class submarine


203_404.csv(J, K and N-class destroyer)
Missing Values(NANs score):  {'pennant number': '0/9', 'name': '0/9', 'builder': '0/9', 'laid down': '0/9', 'launched': '0/9', 'completed': '0/9', 'fate': '0/9'}
Columns that match with input_schema:
 203_404.csv :  {'name': 'name', 'builder': 'builder', 'launched': 'launched', 'completed': 'completed', 'fate': 'fate'}
Coverage Score :  1.0 	 Completeness Score :  1.0

,pennant number,name,builder,laid down,launched,completed,fate
0,F00,Jervis ‡,"Hawthorn Leslie & Company, Hebburn",26 August 1937,9 September 1938,12 May 1939,Sold for scrap 1949
1,F22,Jackal,"John Brown & Company, Clydebank",24 September 1937,25 October 1938,31 March 1939,Bombed off Mersa Matruh on 11 May 1942 and scu...
2,F34,Jaguar,"William Denny & Brothers, Dumbarton",25 November 1937,22 November 1938,12 September 1939,"Torpedoed by German U-boat U.652 off Sollum, 2..."
3,F46,Juno (ex-Jamaica),"Fairfield Shipbuilding & Engineering Company, ...",15 October 1937,8 December 1938,25 August 1939,"Bombed and sunk south of Crete, 21 May 1941"
4,F53,Janus,"Swan Hunter & Wigham Richardson, Wallsend",29 September 1937,11 October 1938,5 August 1939,Torpedoed and sunk off Anzio by German aircraf...
5,F61,Javelin (ex-Kashmir),John Brown,11 October 1937,21 December 1938,10 June 1939,Sold for scrap 1949
6,F72,Jersey,"J. Samuel White, Cowes",1937,26 September 1938,28 April 1939,"Mined off Valletta 2 May 1941, broke in two an..."
7,F85,Jupiter,"Yarrow & Company, Scotstoun",28 September 1937,27 October 1938,25 June 1939,Hit a Dutch mine during the battle of the Java...
8,-,Jubilant,-,-,-,-,"Ordered March 1937, cancelled December 1937"

204_522.csv(Ha-201-class submarine)
Missing Values(NANs score):  {'boat num': '0/44', 'name': '2/44', 'builder': '2/44', 'laid down': '2/44', 'launched': '22/44', 'completed': '34/44', 'fate': '0/44'}
Columns that match with input_schema:
 204_522.csv :  {'name': 'name', 'builder': 'builder', 'launched': 'launched', 'completed': 'completed', 'fate': 'fate'}
Coverage Score :  1.0 	 Completeness Score :  0.7272727272727273

,boat num,name,builder,laid down,launched,completed,fate
0,4911,Ha-201,Sasebo Naval Arsenal,01-03-1945,23-04-1945,31-05-1945,Decommissioned 30-11-1945. Scuttled off Goto I...
1,4912,Ha-202,Sasebo Naval Arsenal,01-03-1945,23-04-1945,31-05-1945,Decommissioned 30-11-1945. Scuttled off Goto I...
2,4913,Ha-203,Sasebo Naval Arsenal,05-04-1945,25-05-1945,26-06-1945,Decommissioned 30-11-1945. Scuttled off Goto I...
3,4914,Ha-204,Sasebo Naval Arsenal,05-04-1945,01-06-1945,25-06-1945,Decommissioned 30-11-1945. Grounded at Aburats...
4,4915,Ha-205,Sasebo Naval Arsenal,17-04-1945,14-05-1945,03-07-1945,Decommissioned 30-11-1945. Scuttled at Iyo Nad...
5,4916,Ha-206,Kawasaki-Senshū Shipyard,19-03-1945,10-07-1945,NaN,"Incomplete until the end of war (95%), sunk by..."
6,4917,Ha-207,Sasebo Naval Arsenal,23-04-1945,26-05-1945,14-08-1945,Decommissioned 30-11-1945. Scuttled off Sasebo...
7,4918,Ha-208,Sasebo Naval Arsenal,01-05-1945,26-05-1945,04-08-1945,Decommissioned 30-11-1945. Scuttled off Goto I...
8,4919,Ha-209,Sasebo Naval Arsenal,07-05-1945,31-05-1945,04-08-1945,Decommissioned 30-11-1945. Scrapped August 1946.
9,4920,Ha-210,Sasebo Naval Arsenal,14-05-1945,10-06-1945,11-08-1945,Decommissioned 30-11-1945. Scuttled off Sasebo...
10,4921,Ha-211,Kawasaki-Senshū Shipyard,01-04-1945,April 1946,NaN,Incomplete until the end of war (40%). Scuttle...
11,4922,Ha-212,Kawasaki-Kobe Shipyard,10-04-1945,25-06-1945,NaN,Incomplete until the end of war (95%). Scuttle...
12,4923,Ha-213,Mitsubishi-Kobe Shipyard,15-05-1945,29-07-1945,NaN,Incomplete until the end of war (93%). Scuttle...
13,4924,Ha-214,Mitsubishi-Kobe Shipyard,15-05-1945,15-08-1945,NaN,Incomplete until the end of war (75%). Scuttle...
14,4925,Ha-215,Sasebo Naval Arsenal,22-05-1945,15-05-1945,NaN,Incomplete until the end of war (95%). Scuttle...
15,4926,Ha-216,Sasebo Naval Arsenal,27-05-1945,19-06-1945,16-08-1945,Decommissioned 30-11-1945. Scuttled off Sasebo...
16,4927,Ha-217,Sasebo Naval Arsenal,02-06-1945,26-06-1945,NaN,Incomplete until the end of war (90%). Scuttle...
17,4928,Ha-218,Sasebo Naval Arsenal,08-06-1945,02-07-1945,NaN,Incomplete until the end of war (90%). Scrappe...
18,4929,Ha-219,Sasebo Naval Arsenal,15-06-1945,12-07-1945,NaN,Incomplete until the end of war (90%). Scuttle...
19,4930,Ha-220,Kawasaki-Senshū Shipyard,10-05-1945,NaN,NaN,Incomplete until the end of war (20%). Scrappe...
20,4931,Ha-221,Mitsubishi-Kobe Shipyard,20-04-1945,04-08-1945,NaN,Incomplete until the end of war (85%). Scuttle...
21,4932,Ha-222,Kawasaki-Senshū Shipyard,15-05-1945,NaN,NaN,Incomplete until the end of war (15%). Scrappe...
22,4933,Ha-223,Kawasaki-Kobe Shipyard,01-05-1945,NaN,NaN,Incomplete until the end of war (60%). Scrappe...
23,4934,Ha-224,Mitsubishi-Kobe Shipyard,07-06-1945,NaN,NaN,Incomplete until the end of war (55%). Scrappe...
24,4935,Ha-225,Mitsubishi-Kobe Shipyard,07-06-1945,NaN,NaN,Incomplete until the end of war (45%). Scrappe...
25,4936,Ha-226,Mitsubishi-Kobe Shipyard,16-06-1945,NaN,NaN,Incomplete until the end of war (35%). Scrappe...
26,4937,Ha-227,Mitsubishi-Kobe Shipyard,10-07-1945,NaN,NaN,Incomplete until the end of war (25%). Scrappe...
27,4938,Ha-228,Sasebo Naval Arsenal,21-06-1945,18-07-1945,NaN,Incomplete until the end of war (75%). Scuttle...
28,4939,Ha-229,Sasebo Naval Arsenal,27-06-1945,27-07-1945,NaN,Incomplete until the end of war (75%). Scrappe...
29,4940,Ha-230,Sasebo Naval Arsenal,03-07-1945,NaN,NaN,Incomplete until the end of war (60%). Scrappe...
30,4941,Ha-231,Sasebo Naval Arsenal,12-07-1945,NaN,NaN,Incomplete until the end of war (50%). Later s...
31,4942,Ha-232,Sasebo Naval Arsenal,18-07-1945,NaN,NaN,Incomplete until the end of war (40%). Later s...
32,4943,Ha-233,Kawasaki-Senshū Shipyard,01-06-1945,NaN,NaN,Incomplete until the end of war (10%). Later s...
33,4944,Ha-234,Kawasaki-Kobe Shipyard,15-05-1945,NaN,NaN,Incomplete until the end of war (50%). Scrappe...
34,4945,Ha-235,Kawasaki-Senshū Shipyard,01-06-1945,NaN,NaN,Incomplete until the end of war (10%). Later s...
35,4946,Ha-236,Kawasaki-Kobe Shipyard,01-06-1945,NaN,NaN,Incomplete until the end of war (40%). Scrappe...
36,4947,Ha-237,Mitsubishi-Kobe Shipyard,10-07-1945,NaN,NaN,Incomplete until the end of war (25%). Scrappe...
37,4948,Ha-238,Mitsubishi-Kobe Shipyard,01-08-1945,NaN,NaN,Incomplete until the end of war (15%). Scrappe...
38,4949,Ha-239,Mitsubishi-Kobe Shipyard,01-08-1945,NaN,NaN,"Incomplete until the end of war. Scrapped, Jun..."
39,4950,Ha-240,Mitsubishi-Kobe Shipyard,01-08-1945,NaN,NaN,"Incomplete until the end of war. Scrapped, Jun..."
40,4951 - 4955,NaN,NaN,NaN,NaN,NaN,Constructions were not started until the end o...
41,4956,Ha-246,Kawasaki-Senshū Shipyard,13-07-1945,NaN,NaN,Incomplete until the end of war (5%). Later sc...
42,4957,Ha-247,Kawasaki-Kobe Shipyard,26-06-1945,NaN,NaN,Incomplete until the end of war. Later scrapped.
43,4958 - 4989,NaN,NaN,NaN,NaN,NaN,Constructions were not started until the end o...

,name,builder,laid down,launched,completed,fate,boat num
0,Jervis ‡,"Hawthorn Leslie & Company, Hebburn",26 August 1937,9 September 1938,12 May 1939,Sold for scrap 1949,NaN
1,Jackal,"John Brown & Company, Clydebank",24 September 1937,25 October 1938,31 March 1939,Bombed off Mersa Matruh on 11 May 1942 and scu...,NaN
2,Jaguar,"William Denny & Brothers, Dumbarton",25 November 1937,22 November 1938,12 September 1939,"Torpedoed by German U-boat U.652 off Sollum, 2...",NaN
3,Juno (ex-Jamaica),"Fairfield Shipbuilding & Engineering Company, ...",15 October 1937,8 December 1938,25 August 1939,"Bombed and sunk south of Crete, 21 May 1941",NaN
4,Janus,"Swan Hunter & Wigham Richardson, Wallsend",29 September 1937,11 October 1938,5 August 1939,Torpedoed and sunk off Anzio by German aircraf...,NaN
5,Javelin (ex-Kashmir),John Brown,11 October 1937,21 December 1938,10 June 1939,Sold for scrap 1949,NaN
6,Jersey,"J. Samuel White, Cowes",1937,26 September 1938,28 April 1939,"Mined off Valletta 2 May 1941, broke in two an...",NaN
7,Jupiter,"Yarrow & Company, Scotstoun",28 September 1937,27 October 1938,25 June 1939,Hit a Dutch mine during the battle of the Java...,NaN
8,Jubilant,-,-,-,-,"Ordered March 1937, cancelled December 1937",NaN
9,Ha-201,Sasebo Naval Arsenal,01-03-1945,23-04-1945,31-05-1945,Decommissioned 30-11-1945. Scuttled off Goto I...,4911
10,Ha-202,Sasebo Naval Arsenal,01-03-1945,23-04-1945,31-05-1945,Decommissioned 30-11-1945. Scuttled off Goto I...,4912
11,Ha-203,Sasebo Naval Arsenal,05-04-1945,25-05-1945,26-06-1945,Decommissioned 30-11-1945. Scuttled off Goto I...,4913
12,Ha-204,Sasebo Naval Arsenal,05-04-1945,01-06-1945,25-06-1945,Decommissioned 30-11-1945. Grounded at Aburats...,4914
13,Ha-205,Sasebo Naval Arsenal,17-04-1945,14-05-1945,03-07-1945,Decommissioned 30-11-1945. Scuttled at Iyo Nad...,4915
14,Ha-206,Kawasaki-Senshū Shipyard,19-03-1945,10-07-1945,NaN,"Incomplete until the end of war (95%), sunk by...",4916
15,Ha-207,Sasebo Naval Arsenal,23-04-1945,26-05-1945,14-08-1945,Decommissioned 30-11-1945. Scuttled off Sasebo...,4917
16,Ha-208,Sasebo Naval Arsenal,01-05-1945,26-05-1945,04-08-1945,Decommissioned 30-11-1945. Scuttled off Goto I...,4918
17,Ha-209,Sasebo Naval Arsenal,07-05-1945,31-05-1945,04-08-1945,Decommissioned 30-11-1945. Scrapped August 1946.,4919
18,Ha-210,Sasebo Naval Arsenal,14-05-1945,10-06-1945,11-08-1945,Decommissioned 30-11-1945. Scuttled off Sasebo...,4920
19,Ha-211,Kawasaki-Senshū Shipyard,01-04-1945,April 1946,NaN,Incomplete until the end of war (40%). Scuttle...,4921
20,Ha-212,Kawasaki-Kobe Shipyard,10-04-1945,25-06-1945,NaN,Incomplete until the end of war (95%). Scuttle...,4922
21,Ha-213,Mitsubishi-Kobe Shipyard,15-05-1945,29-07-1945,NaN,Incomplete until the end of war (93%). Scuttle...,4923
22,Ha-214,Mitsubishi-Kobe Shipyard,15-05-1945,15-08-1945,NaN,Incomplete until the end of war (75%). Scuttle...,4924
23,Ha-215,Sasebo Naval Arsenal,22-05-1945,15-05-1945,NaN,Incomplete until the end of war (95%). Scuttle...,4925
24,Ha-216,Sasebo Naval Arsenal,27-05-1945,19-06-1945,16-08-1945,Decommissioned 30-11-1945. Scuttled off Sasebo...,4926
25,Ha-217,Sasebo Naval Arsenal,02-06-1945,26-06-1945,NaN,Incomplete until the end of war (90%). Scuttle...,4927
26,Ha-218,Sasebo Naval Arsenal,08-06-1945,02-07-1945,NaN,Incomplete until the end of war (90%). Scrappe...,4928
27,Ha-219,Sasebo Naval Arsenal,15-06-1945,12-07-1945,NaN,Incomplete until the end of war (90%). Scuttle...,4929
28,Ha-220,Kawasaki-Senshū Shipyard,10-05-1945,NaN,NaN,Incomplete until the end of war (20%). Scrappe...,4930
29,Ha-221,Mitsubishi-Kobe Shipyard,20-04-1945,04-08-1945,NaN,Incomplete until the end of war (85%). Scuttle...,4931
30,Ha-222,Kawasaki-Senshū Shipyard,15-05-1945,NaN,NaN,Incomplete until the end of war (15%). Scrappe...,4932
31,Ha-223,Kawasaki-Kobe Shipyard,01-05-1945,NaN,NaN,Incomplete until the end of war (60%). Scrappe...,4933
32,Ha-224,Mitsubishi-Kobe Shipyard,07-06-1945,NaN,NaN,Incomplete until the end of war (55%). Scrappe...,4934
33,Ha-225,Mitsubishi-Kobe Shipyard,07-06-1945,NaN,NaN,Incomplete until the end of war (45%). Scrappe...,4935
34,Ha-226,Mitsubishi-Kobe Shipyard,16-06-1945,NaN,NaN,Incomplete until the end of war (35%). Scrappe...,4936
35,Ha-227,Mitsubishi-Kobe Shipyard,10-07-1945,NaN,NaN,Incomplete until the end of war (25%). Scrappe...,4937
36,Ha-228,Sasebo Naval Arsenal,21-06-1945,18-07-1945,NaN,Incomplete until the end of war (75%). Scuttle...,4938
37,Ha-229,Sasebo Naval Arsenal,27-06-1945,27-07-1945,NaN,Incomplete until the end of war (75%). Scrappe...,4939
38,Ha-230,Sasebo Naval Arsenal,03-07-1945,NaN,NaN,Incomplete until the end of war (60%). Scrappe...,4940
39,Ha-231,Sasebo Naval Arsenal,12-07-1945,NaN,NaN,Incomplete until the end of war (50%). Later s...,4941
40,Ha-232,Sasebo Naval Arsenal,18-07-1945,NaN,NaN,Incomplete until the end of war (40%). Later s...,4942
41,Ha-233,Kawasaki-Senshū Shipyard,01-06-1945,NaN,NaN,Incomplete until the end of war (10%). Later s...,4943
42,Ha-234,Kawasaki-Kobe Shipyard,15-05-1945,NaN,NaN,Incomplete until the end of war (50%). Scrappe...,4944
43,Ha-235,Kawasaki-Senshū Shipyard,01-06-1945,NaN,NaN,Incomplete until the end of war (10%). Later s...,4945
44,Ha-236,Kawasaki-Kobe Shipyard,01-06-1945,NaN,NaN,Incomplete until the end of war (40%). Scrappe...,4946
45,Ha-237,Mitsubishi-Kobe Shipyard,10-07-1945,NaN,NaN,Incomplete until the end of war (25%). Scrappe...,4947
46,Ha-238,Mitsubishi-Kobe Shipyard,01-08-1945,NaN,NaN,Incomplete until the end of war (15%). Scrappe...,4948
47,Ha-239,Mitsubishi-Kobe Shipyard,01-08-1945,NaN,NaN,"Incomplete until the end of war. Scrapped, Jun...",4949
48,Ha-240,Mitsubishi-Kobe Shipyard,01-08-1945,NaN,NaN,"Incomplete until the end of war. Scrapped, Jun...",4950
49,NaN,NaN,NaN,NaN,NaN,Constructions were not started until the end o...,4951 - 4955
50,NaN,NaN,NaN,NaN,NaN,Constructions were not started until the end o...,4958 - 4989
51,Ha-246,Kawasaki-Senshū Shipyard,13-07-1945,NaN,NaN,Incomplete until the end of war (5%). Later sc...,4956
52,Ha-247,Kawasaki-Kobe Shipyard,26-06-1945,NaN,NaN,Incomplete until the end of war. Later scrapped.,4957

Rank  1   :  203_404.csv          completeness score : 1.0000000000000000 		number of rows:  9
Rank  2   :  output_0.csv         completeness score : 0.7735849056603774 		number of rows:  53
Rank  3   :  204_522.csv          completeness score : 0.7272727272727273 		number of rows:  44

Ranking Complete!!

In [37]:
# Query 8 : Results
# "categories": ["diving", "summer", "1984", "womens", "olympics", "springboard", "events"]}
s='{"schema": {"rank": "float64", "diver": "object", "preliminary points": "float64", "preliminary rank": "int64", "points": "float64"},"categories": ["womens","diving"]}'
s=s.lower()
s=json.loads(s)
input_schema=s['schema'];input_categories=-1;transformations=-1;stats=-1
if "categories" in s:
    input_categories=s["categories"]
if "transformations" in s:
    transformations=s["transformations"]
if "stats" in s:
    stats=s["stats"]
# display query
print("Input Schema : ",input_schema)
if input_categories==-1:
    print("Input Categories : None")
else:
    print("Input Categories : ",input_categories)
if transformations==-1:
    print("Input Transformations : None")
else:
    print("Input Transformations : ",transformations)
if stats==-1:
    print("Input Condition based conditions : None")
else:
    print("Input Content based Conditions : ",stats)
print()
comp_score={}
no_of_rows={}
no_of_rows={}
get_matches()

Input Schema :  {'rank': 'float64', 'diver': 'object', 'preliminary points': 'float64', 'preliminary rank': 'int64', 'points': 'float64'}
Input Categories :  ['womens', 'diving']
Input Transformations : None
Input Condition based conditions : None

category and schema
Matching Tables
203_373.csv  :  Diving at the 1984 Summer Olympics - Women's 3 metre springboard
203_780.csv  :  Diving at the 1960 Summer Olympics - Women's 10 metre platform
204_316.csv  :  Diving at the 2011 World Aquatics Championships - Women's 1 metre springboard


203_373.csv(Diving at the 1984 Summer Olympics - Women's 3 metre springboard)
Missing Values(NANs score):  {'rank': '3/24', 'diver': '0/24', 'preliminary points': '0/24', 'preliminary rank': '0/24', 'final points': '12/24'}
Columns that match with input_schema:
 203_373.csv :  {'rank': 'rank', 'diver': 'diver', 'preliminary points': 'preliminary points', 'preliminary rank': 'preliminary rank', 'final points': 'points'}
Coverage Score :  1.0 	 Completeness Score :  0.875

,rank,diver,preliminary points,preliminary rank,points
0,NaN,Sylvie Bernier (CAN),489.51,3,530.70
1,NaN,Kelly McCormick (USA),516.75,2,527.46
2,NaN,Christina Seufert (USA),481.41,5,517.62
3,4.0,Li Yihua (CHN),517.92,1,506.52
4,5.0,Li Qiaoxian (CHN),466.83,6,487.68
5,6.0,Elsa Tenorio (MEX),460.56,8,463.56
6,7.0,Lesley Smith (ZIM),438.72,10,451.89
7,8.0,Debbie Fuller (CAN),437.04,11,450.99
8,9.0,Jennifer Donnet (AUS),432.78,12,443.13
9,10.0,Daphne Jongejans (NED),487.95,4,437.40
10,11.0,Anita Rossing (SWE),464.58,7,424.98
11,12.0,Veronica Ribot (ARG),443.25,9,422.52
12,13.0,Ann Fargher (NZL),421.65,13,NaN
13,14.0,Tine Tollan (NOR),419.55,14,NaN
14,15.0,Antonette Wilken (ZIM),414.66,15,NaN
15,16.0,Guadalupe Canseco (MEX),411.96,16,NaN
16,17.0,Claire Izacard (FRA),403.17,17,NaN
17,18.0,Valerie McFarland-Beddoe (AUS),401.13,18,NaN
18,19.0,Alison Childs (GBR),400.68,19,NaN
19,20.0,Kerstin Finke (FRG),393.93,20,NaN
20,21.0,Nicole Kreil (AUT),382.68,21,NaN
21,22.0,Joana Figueiredo (POR),374.07,22,NaN
22,23.0,Angela Ribeiro (BRA),370.68,23,NaN
23,24.0,Rim Hassan (EGY),258.63,24,NaN

203_780.csv(Diving at the 1960 Summer Olympics - Women's 10 metre platform)
Missing Values(NANs score):  {'rank': '3/18', 'diver': '0/18', 'preliminary points': '0/18', 'preliminary rank': '0/18', 'final points': '6/18', 'final rank': '6/18', 'final total': '6/18'}
Columns that match with input_schema:
 203_780.csv :  {'rank': 'rank', 'diver': 'diver', 'preliminary points': 'preliminary points', 'preliminary rank': 'preliminary rank', 'final points': 'points'}
Coverage Score :  1.0 	 Completeness Score :  0.9

,rank,diver,preliminary points,preliminary rank,points,final rank,final total
0,NaN,Ingrid Krämer (EUA),56.30,1,34.98,2.0,91.28
1,NaN,Paula Jean Myers-Pope (USA),54.70,2,35.24,1.0,89.94
2,NaN,Ninel Krutova (URS),53.38,3,33.61,3.0,86.99
3,4.0,Juno Stover-Irwin (USA),51.90,6,31.69,4.0,83.59
4,5.0,Raisa Gorokhovskaya (URS),51.53,8,31.50,5.0,83.03
5,6.0,Norma Thomas (GBR),51.77,7,30.44,7.0,82.21
6,7.0,Nicolle Darrigrand-Pellissard (FRA),49.68,12,31.50,5.0,81.18
7,8.0,Phyllis Long (GBR),52.12,5,28.86,9.0,80.98
8,9.0,Irene MacDonald (CAN),51.31,9,29.18,8.0,80.49
9,10.0,Kumiko Watanabe (JPN),51.04,10,28.56,10.0,79.60
10,11.0,Kanoko Tsutani-Mabuchi (JPN),49.76,11,28.14,11.0,77.90
11,12.0,Birte Christoffersen-Hanson (SWE),53.03,4,24.40,12.0,77.43
12,13.0,Maria Teresa Adames (MEX),49.54,13,NaN,NaN,NaN
13,14.0,Hanna Laursen (DEN),48.89,14,NaN,NaN,NaN
14,15.0,Gabriele Schöpe (EUA),48.81,15,NaN,NaN,NaN
15,16.0,Bende Velin (DEN),48.35,16,NaN,NaN,NaN
16,17.0,Laura Conter (ITA),45.55,17,NaN,NaN,NaN
17,18.0,Susan Knight (AUS),43.03,18,NaN,NaN,NaN

204_316.csv(Diving at the 2011 World Aquatics Championships - Women's 1 metre springboard)
Missing Values(NANs score):  {'rank': '3/40', 'diver': '0/40', 'nationality': '0/40', 'preliminary points': '0/40', 'preliminary rank': '0/40', 'final points': '28/40', 'final rank': '28/40'}
Columns that match with input_schema:
 204_316.csv :  {'rank': 'rank', 'diver': 'diver', 'preliminary points': 'preliminary points', 'preliminary rank': 'preliminary rank', 'final points': 'points'}
Coverage Score :  1.0 	 Completeness Score :  0.845

,rank,diver,nationality,preliminary points,preliminary rank,points,final rank
0,NaN,Shi Tingmao,China,294.65,2,318.65,1.0
1,NaN,Wang Han,China,306.60,1,310.20,2.0
2,NaN,Tania Cagnotto,Italy,253.15,12,295.45,3.0
3,4.0,Maria Marconi,Italy,264.25,6,290.15,4.0
4,5.0,Nadezhda Bazhina,Russia,262.75,7,286.20,5.0
5,6.0,Abby Johnston,United States,282.40,4,282.85,6.0
6,7.0,Sharleen Stratton,Australia,282.45,3,281.65,7.0
7,8.0,Anna Lindberg,Sweden,276.05,5,279.55,8.0
8,9.0,Kelci Bryant,United States,257.00,11,274.25,9.0
9,10.0,Olena Fedorova,Ukraine,258.30,9,274.15,10.0
10,11.0,Brittany Broben,Australia,257.10,10,267.20,11.0
11,12.0,Anastasia Pozdniakova,Russia,260.00,8,251.70,12.0
12,13.0,Hanna Pysmenska,Ukraine,251.40,13,NaN,NaN
13,14.0,Jennifer Abel,Canada,250.95,14,NaN,NaN
14,15.0,Sophie Somloi,Austria,249.45,15,NaN,NaN
15,16.0,Uschi Freitag,Germany,247.70,16,NaN,NaN
16,17.0,Sharon Chan,Hong Kong,245.10,17,NaN,NaN
17,18.0,Inge Jansen,Netherlands,241.95,18,NaN,NaN
18,19.0,Jun Hoong Cheong,Malaysia,241.95,18,NaN,NaN
19,20.0,Sayaka Shibusawa,Japan,240.80,20,NaN,NaN
20,21.0,Jennifer Benitez,Spain,232.50,21,NaN,NaN
21,22.0,Arantxa Chavez,Mexico,232.35,22,NaN,NaN
22,23.0,Vianey Hernandez,Mexico,227.85,23,NaN,NaN
23,24.0,Fanny Bouvet,France,227.10,24,NaN,NaN
24,25.0,Hannah Starling,Great Britain,226.40,25,NaN,NaN
25,26.0,Choi Sut Ian,Macau,224.50,26,NaN,NaN
26,27.0,Marion Farissier,France,221.65,27,NaN,NaN
27,28.0,Julia Loennegren,Sweden,221.05,28,NaN,NaN
28,29.0,Yuka Mabuchi,Japan,219.50,29,NaN,NaN
29,30.0,Alicia Blagg,Great Britain,212.50,30,NaN,NaN
30,31.0,Beannelys Velasquez,Venezuela,211.30,31,NaN,NaN
31,32.0,Diana Pineda,Colombia,209.60,32,NaN,NaN
32,33.0,Tina Punzel,Germany,206.05,33,NaN,NaN
33,34.0,Maria Florencia Betancourt,Venezuela,204.90,34,NaN,NaN
34,35.0,Sari Ambarwati,Indonesia,200.05,35,NaN,NaN
35,36.0,Lei Sio I,Macau,192.00,36,NaN,NaN
36,37.0,Leyre Eizaguirre,Spain,189.95,37,NaN,NaN
37,38.0,Huang En-Tien,Chinese Taipei,187.25,38,NaN,NaN
38,39.0,Carolina Murillo,Colombia,181.85,39,NaN,NaN
39,40.0,Hsu Shi-Han,Chinese Taipei,146.15,40,NaN,NaN

1.csv : 203_373.csv(Diving at the 1984 Summer Olympics - Women's 3 metre springboard)		203_780.csv(Diving at the 1960 Summer Olympics - Women's 10 metre platform)		204_316.csv(Diving at the 2011 World Aquatics Championships - Women's 1 metre springboard)
Missing Values(NANs):  {'rank': '9/82', 'diver': '0/82', 'preliminary points': '0/82', 'preliminary rank': '0/82', 'points': '46/82'}
Columns that match with input_schema:
203_373.csv :  {'rank': 'rank', 'diver': 'diver', 'preliminary points': 'preliminary points', 'preliminary rank': 'preliminary rank', 'final points': 'points'}
203_780.csv :  {'rank': 'rank', 'diver': 'diver', 'preliminary points': 'preliminary points', 'preliminary rank': 'preliminary rank', 'final points': 'points'}
204_316.csv :  {'rank': 'rank', 'diver': 'diver', 'preliminary points': 'preliminary points', 'preliminary rank': 'preliminary rank', 'final points': 'points'}
Coverage Score :  1.0 	 Completeness Score :  0.8658536585365854

,rank,diver,preliminary points,preliminary rank,points
0,NaN,Sylvie Bernier (CAN),489.51,3,530.70
1,NaN,Kelly McCormick (USA),516.75,2,527.46
2,NaN,Christina Seufert (USA),481.41,5,517.62
3,4.0,Li Yihua (CHN),517.92,1,506.52
4,5.0,Li Qiaoxian (CHN),466.83,6,487.68
5,6.0,Elsa Tenorio (MEX),460.56,8,463.56
6,7.0,Lesley Smith (ZIM),438.72,10,451.89
7,8.0,Debbie Fuller (CAN),437.04,11,450.99
8,9.0,Jennifer Donnet (AUS),432.78,12,443.13
9,10.0,Daphne Jongejans (NED),487.95,4,437.40
10,11.0,Anita Rossing (SWE),464.58,7,424.98
11,12.0,Veronica Ribot (ARG),443.25,9,422.52
12,13.0,Ann Fargher (NZL),421.65,13,NaN
13,14.0,Tine Tollan (NOR),419.55,14,NaN
14,15.0,Antonette Wilken (ZIM),414.66,15,NaN
15,16.0,Guadalupe Canseco (MEX),411.96,16,NaN
16,17.0,Claire Izacard (FRA),403.17,17,NaN
17,18.0,Valerie McFarland-Beddoe (AUS),401.13,18,NaN
18,19.0,Alison Childs (GBR),400.68,19,NaN
19,20.0,Kerstin Finke (FRG),393.93,20,NaN
20,21.0,Nicole Kreil (AUT),382.68,21,NaN
21,22.0,Joana Figueiredo (POR),374.07,22,NaN
22,23.0,Angela Ribeiro (BRA),370.68,23,NaN
23,24.0,Rim Hassan (EGY),258.63,24,NaN
24,NaN,Ingrid Krämer (EUA),56.30,1,34.98
25,NaN,Paula Jean Myers-Pope (USA),54.70,2,35.24
26,NaN,Ninel Krutova (URS),53.38,3,33.61
27,4.0,Juno Stover-Irwin (USA),51.90,6,31.69
28,5.0,Raisa Gorokhovskaya (URS),51.53,8,31.50
29,6.0,Norma Thomas (GBR),51.77,7,30.44
...,...,...,...,...,...
52,11.0,Brittany Broben,257.10,10,267.20
53,12.0,Anastasia Pozdniakova,260.00,8,251.70
54,13.0,Hanna Pysmenska,251.40,13,NaN
55,14.0,Jennifer Abel,250.95,14,NaN
56,15.0,Sophie Somloi,249.45,15,NaN
57,16.0,Uschi Freitag,247.70,16,NaN
58,17.0,Sharon Chan,245.10,17,NaN
59,18.0,Inge Jansen,241.95,18,NaN
60,19.0,Jun Hoong Cheong,241.95,18,NaN
61,20.0,Sayaka Shibusawa,240.80,20,NaN
62,21.0,Jennifer Benitez,232.50,21,NaN
63,22.0,Arantxa Chavez,232.35,22,NaN
64,23.0,Vianey Hernandez,227.85,23,NaN
65,24.0,Fanny Bouvet,227.10,24,NaN
66,25.0,Hannah Starling,226.40,25,NaN
67,26.0,Choi Sut Ian,224.50,26,NaN
68,27.0,Marion Farissier,221.65,27,NaN
69,28.0,Julia Loennegren,221.05,28,NaN
70,29.0,Yuka Mabuchi,219.50,29,NaN
71,30.0,Alicia Blagg,212.50,30,NaN
72,31.0,Beannelys Velasquez,211.30,31,NaN
73,32.0,Diana Pineda,209.60,32,NaN
74,33.0,Tina Punzel,206.05,33,NaN
75,34.0,Maria Florencia Betancourt,204.90,34,NaN
76,35.0,Sari Ambarwati,200.05,35,NaN
77,36.0,Lei Sio I,192.00,36,NaN
78,37.0,Leyre Eizaguirre,189.95,37,NaN
79,38.0,Huang En-Tien,187.25,38,NaN
80,39.0,Carolina Murillo,181.85,39,NaN
81,40.0,Hsu Shi-Han,146.15,40,NaN

2.csv : 203_373.csv(Diving at the 1984 Summer Olympics - Women's 3 metre springboard)		203_780.csv(Diving at the 1960 Summer Olympics - Women's 10 metre platform)
Missing Values(NANs):  {'rank': '6/42', 'diver': '0/42', 'preliminary points': '0/42', 'preliminary rank': '0/42', 'points': '18/42'}
Columns that match with input_schema:
203_373.csv :  {'rank': 'rank', 'diver': 'diver', 'preliminary points': 'preliminary points', 'preliminary rank': 'preliminary rank', 'final points': 'points'}
203_780.csv :  {'rank': 'rank', 'diver': 'diver', 'preliminary points': 'preliminary points', 'preliminary rank': 'preliminary rank', 'final points': 'points'}
Coverage Score :  1.0 	 Completeness Score :  0.8857142857142858

,rank,diver,preliminary points,preliminary rank,points
0,NaN,Sylvie Bernier (CAN),489.51,3,530.70
1,NaN,Kelly McCormick (USA),516.75,2,527.46
2,NaN,Christina Seufert (USA),481.41,5,517.62
3,4.0,Li Yihua (CHN),517.92,1,506.52
4,5.0,Li Qiaoxian (CHN),466.83,6,487.68
5,6.0,Elsa Tenorio (MEX),460.56,8,463.56
6,7.0,Lesley Smith (ZIM),438.72,10,451.89
7,8.0,Debbie Fuller (CAN),437.04,11,450.99
8,9.0,Jennifer Donnet (AUS),432.78,12,443.13
9,10.0,Daphne Jongejans (NED),487.95,4,437.40
10,11.0,Anita Rossing (SWE),464.58,7,424.98
11,12.0,Veronica Ribot (ARG),443.25,9,422.52
12,13.0,Ann Fargher (NZL),421.65,13,NaN
13,14.0,Tine Tollan (NOR),419.55,14,NaN
14,15.0,Antonette Wilken (ZIM),414.66,15,NaN
15,16.0,Guadalupe Canseco (MEX),411.96,16,NaN
16,17.0,Claire Izacard (FRA),403.17,17,NaN
17,18.0,Valerie McFarland-Beddoe (AUS),401.13,18,NaN
18,19.0,Alison Childs (GBR),400.68,19,NaN
19,20.0,Kerstin Finke (FRG),393.93,20,NaN
20,21.0,Nicole Kreil (AUT),382.68,21,NaN
21,22.0,Joana Figueiredo (POR),374.07,22,NaN
22,23.0,Angela Ribeiro (BRA),370.68,23,NaN
23,24.0,Rim Hassan (EGY),258.63,24,NaN
24,NaN,Ingrid Krämer (EUA),56.30,1,34.98
25,NaN,Paula Jean Myers-Pope (USA),54.70,2,35.24
26,NaN,Ninel Krutova (URS),53.38,3,33.61
27,4.0,Juno Stover-Irwin (USA),51.90,6,31.69
28,5.0,Raisa Gorokhovskaya (URS),51.53,8,31.50
29,6.0,Norma Thomas (GBR),51.77,7,30.44
30,7.0,Nicolle Darrigrand-Pellissard (FRA),49.68,12,31.50
31,8.0,Phyllis Long (GBR),52.12,5,28.86
32,9.0,Irene MacDonald (CAN),51.31,9,29.18
33,10.0,Kumiko Watanabe (JPN),51.04,10,28.56
34,11.0,Kanoko Tsutani-Mabuchi (JPN),49.76,11,28.14
35,12.0,Birte Christoffersen-Hanson (SWE),53.03,4,24.40
36,13.0,Maria Teresa Adames (MEX),49.54,13,NaN
37,14.0,Hanna Laursen (DEN),48.89,14,NaN
38,15.0,Gabriele Schöpe (EUA),48.81,15,NaN
39,16.0,Bende Velin (DEN),48.35,16,NaN
40,17.0,Laura Conter (ITA),45.55,17,NaN
41,18.0,Susan Knight (AUS),43.03,18,NaN

3.csv : 203_373.csv(Diving at the 1984 Summer Olympics - Women's 3 metre springboard)		204_316.csv(Diving at the 2011 World Aquatics Championships - Women's 1 metre springboard)
Missing Values(NANs):  {'rank': '6/64', 'diver': '0/64', 'preliminary points': '0/64', 'preliminary rank': '0/64', 'points': '40/64'}
Columns that match with input_schema:
203_373.csv :  {'rank': 'rank', 'diver': 'diver', 'preliminary points': 'preliminary points', 'preliminary rank': 'preliminary rank', 'final points': 'points'}
204_316.csv :  {'rank': 'rank', 'diver': 'diver', 'preliminary points': 'preliminary points', 'preliminary rank': 'preliminary rank', 'final points': 'points'}
Coverage Score :  1.0 	 Completeness Score :  0.85625

,rank,diver,preliminary points,preliminary rank,points
0,NaN,Sylvie Bernier (CAN),489.51,3,530.70
1,NaN,Kelly McCormick (USA),516.75,2,527.46
2,NaN,Christina Seufert (USA),481.41,5,517.62
3,4.0,Li Yihua (CHN),517.92,1,506.52
4,5.0,Li Qiaoxian (CHN),466.83,6,487.68
5,6.0,Elsa Tenorio (MEX),460.56,8,463.56
6,7.0,Lesley Smith (ZIM),438.72,10,451.89
7,8.0,Debbie Fuller (CAN),437.04,11,450.99
8,9.0,Jennifer Donnet (AUS),432.78,12,443.13
9,10.0,Daphne Jongejans (NED),487.95,4,437.40
10,11.0,Anita Rossing (SWE),464.58,7,424.98
11,12.0,Veronica Ribot (ARG),443.25,9,422.52
12,13.0,Ann Fargher (NZL),421.65,13,NaN
13,14.0,Tine Tollan (NOR),419.55,14,NaN
14,15.0,Antonette Wilken (ZIM),414.66,15,NaN
15,16.0,Guadalupe Canseco (MEX),411.96,16,NaN
16,17.0,Claire Izacard (FRA),403.17,17,NaN
17,18.0,Valerie McFarland-Beddoe (AUS),401.13,18,NaN
18,19.0,Alison Childs (GBR),400.68,19,NaN
19,20.0,Kerstin Finke (FRG),393.93,20,NaN
20,21.0,Nicole Kreil (AUT),382.68,21,NaN
21,22.0,Joana Figueiredo (POR),374.07,22,NaN
22,23.0,Angela Ribeiro (BRA),370.68,23,NaN
23,24.0,Rim Hassan (EGY),258.63,24,NaN
24,NaN,Shi Tingmao,294.65,2,318.65
25,NaN,Wang Han,306.60,1,310.20
26,NaN,Tania Cagnotto,253.15,12,295.45
27,4.0,Maria Marconi,264.25,6,290.15
28,5.0,Nadezhda Bazhina,262.75,7,286.20
29,6.0,Abby Johnston,282.40,4,282.85
...,...,...,...,...,...
34,11.0,Brittany Broben,257.10,10,267.20
35,12.0,Anastasia Pozdniakova,260.00,8,251.70
36,13.0,Hanna Pysmenska,251.40,13,NaN
37,14.0,Jennifer Abel,250.95,14,NaN
38,15.0,Sophie Somloi,249.45,15,NaN
39,16.0,Uschi Freitag,247.70,16,NaN
40,17.0,Sharon Chan,245.10,17,NaN
41,18.0,Inge Jansen,241.95,18,NaN
42,19.0,Jun Hoong Cheong,241.95,18,NaN
43,20.0,Sayaka Shibusawa,240.80,20,NaN
44,21.0,Jennifer Benitez,232.50,21,NaN
45,22.0,Arantxa Chavez,232.35,22,NaN
46,23.0,Vianey Hernandez,227.85,23,NaN
47,24.0,Fanny Bouvet,227.10,24,NaN
48,25.0,Hannah Starling,226.40,25,NaN
49,26.0,Choi Sut Ian,224.50,26,NaN
50,27.0,Marion Farissier,221.65,27,NaN
51,28.0,Julia Loennegren,221.05,28,NaN
52,29.0,Yuka Mabuchi,219.50,29,NaN
53,30.0,Alicia Blagg,212.50,30,NaN
54,31.0,Beannelys Velasquez,211.30,31,NaN
55,32.0,Diana Pineda,209.60,32,NaN
56,33.0,Tina Punzel,206.05,33,NaN
57,34.0,Maria Florencia Betancourt,204.90,34,NaN
58,35.0,Sari Ambarwati,200.05,35,NaN
59,36.0,Lei Sio I,192.00,36,NaN
60,37.0,Leyre Eizaguirre,189.95,37,NaN
61,38.0,Huang En-Tien,187.25,38,NaN
62,39.0,Carolina Murillo,181.85,39,NaN
63,40.0,Hsu Shi-Han,146.15,40,NaN

4.csv : 203_780.csv(Diving at the 1960 Summer Olympics - Women's 10 metre platform)		204_316.csv(Diving at the 2011 World Aquatics Championships - Women's 1 metre springboard)
Missing Values(NANs):  {'rank': '6/58', 'diver': '0/58', 'preliminary points': '0/58', 'preliminary rank': '0/58', 'points': '34/58'}
Columns that match with input_schema:
203_780.csv :  {'rank': 'rank', 'diver': 'diver', 'preliminary points': 'preliminary points', 'preliminary rank': 'preliminary rank', 'final points': 'points'}
204_316.csv :  {'rank': 'rank', 'diver': 'diver', 'preliminary points': 'preliminary points', 'preliminary rank': 'preliminary rank', 'final points': 'points'}
Coverage Score :  1.0 	 Completeness Score :  0.8620689655172414

,rank,diver,preliminary points,preliminary rank,points
0,NaN,Ingrid Krämer (EUA),56.30,1,34.98
1,NaN,Paula Jean Myers-Pope (USA),54.70,2,35.24
2,NaN,Ninel Krutova (URS),53.38,3,33.61
3,4.0,Juno Stover-Irwin (USA),51.90,6,31.69
4,5.0,Raisa Gorokhovskaya (URS),51.53,8,31.50
5,6.0,Norma Thomas (GBR),51.77,7,30.44
6,7.0,Nicolle Darrigrand-Pellissard (FRA),49.68,12,31.50
7,8.0,Phyllis Long (GBR),52.12,5,28.86
8,9.0,Irene MacDonald (CAN),51.31,9,29.18
9,10.0,Kumiko Watanabe (JPN),51.04,10,28.56
10,11.0,Kanoko Tsutani-Mabuchi (JPN),49.76,11,28.14
11,12.0,Birte Christoffersen-Hanson (SWE),53.03,4,24.40
12,13.0,Maria Teresa Adames (MEX),49.54,13,NaN
13,14.0,Hanna Laursen (DEN),48.89,14,NaN
14,15.0,Gabriele Schöpe (EUA),48.81,15,NaN
15,16.0,Bende Velin (DEN),48.35,16,NaN
16,17.0,Laura Conter (ITA),45.55,17,NaN
17,18.0,Susan Knight (AUS),43.03,18,NaN
18,NaN,Shi Tingmao,294.65,2,318.65
19,NaN,Wang Han,306.60,1,310.20
20,NaN,Tania Cagnotto,253.15,12,295.45
21,4.0,Maria Marconi,264.25,6,290.15
22,5.0,Nadezhda Bazhina,262.75,7,286.20
23,6.0,Abby Johnston,282.40,4,282.85
24,7.0,Sharleen Stratton,282.45,3,281.65
25,8.0,Anna Lindberg,276.05,5,279.55
26,9.0,Kelci Bryant,257.00,11,274.25
27,10.0,Olena Fedorova,258.30,9,274.15
28,11.0,Brittany Broben,257.10,10,267.20
29,12.0,Anastasia Pozdniakova,260.00,8,251.70
30,13.0,Hanna Pysmenska,251.40,13,NaN
31,14.0,Jennifer Abel,250.95,14,NaN
32,15.0,Sophie Somloi,249.45,15,NaN
33,16.0,Uschi Freitag,247.70,16,NaN
34,17.0,Sharon Chan,245.10,17,NaN
35,18.0,Inge Jansen,241.95,18,NaN
36,19.0,Jun Hoong Cheong,241.95,18,NaN
37,20.0,Sayaka Shibusawa,240.80,20,NaN
38,21.0,Jennifer Benitez,232.50,21,NaN
39,22.0,Arantxa Chavez,232.35,22,NaN
40,23.0,Vianey Hernandez,227.85,23,NaN
41,24.0,Fanny Bouvet,227.10,24,NaN
42,25.0,Hannah Starling,226.40,25,NaN
43,26.0,Choi Sut Ian,224.50,26,NaN
44,27.0,Marion Farissier,221.65,27,NaN
45,28.0,Julia Loennegren,221.05,28,NaN
46,29.0,Yuka Mabuchi,219.50,29,NaN
47,30.0,Alicia Blagg,212.50,30,NaN
48,31.0,Beannelys Velasquez,211.30,31,NaN
49,32.0,Diana Pineda,209.60,32,NaN
50,33.0,Tina Punzel,206.05,33,NaN
51,34.0,Maria Florencia Betancourt,204.90,34,NaN
52,35.0,Sari Ambarwati,200.05,35,NaN
53,36.0,Lei Sio I,192.00,36,NaN
54,37.0,Leyre Eizaguirre,189.95,37,NaN
55,38.0,Huang En-Tien,187.25,38,NaN
56,39.0,Carolina Murillo,181.85,39,NaN
57,40.0,Hsu Shi-Han,146.15,40,NaN

Rank  1   :  203_780.csv          completeness score : 0.9000000000000000 		number of rows:  18
Rank  2   :  output_2.csv         completeness score : 0.8857142857142858 		number of rows:  42
Rank  3   :  203_373.csv          completeness score : 0.8750000000000000 		number of rows:  24
Rank  4   :  output_1.csv         completeness score : 0.8658536585365854 		number of rows:  82
Rank  5   :  output_4.csv         completeness score : 0.8620689655172414 		number of rows:  58
Rank  6   :  output_3.csv         completeness score : 0.8562500000000000 		number of rows:  64
Rank  7   :  204_316.csv          completeness score : 0.8450000000000000 		number of rows:  40

Ranking Complete!!

In [38]:
# Query 9 : Results
# "schema": {"pos": "object", "rider": "object", "manufacturer": "object"}
# "categories": ["prix", "motorsport", "motogp", "grand", "1996", "italian", "reports", "motorcycle", "race"]}
s='{"schema": {"pos": "object", "rider": "object", "manufacturer": "object"}}'
s=s.lower()
s=json.loads(s)
input_schema=s['schema'];input_categories=-1;transformations=-1;stats=-1
if "categories" in s:
    input_categories=s["categories"]
if "transformations" in s:
    transformations=s["transformations"]
if "stats" in s:
    stats=s["stats"]
# display query
print("Input Schema : ",input_schema)
if input_categories==-1:
    print("Input Categories : None")
else:
    print("Input Categories : ",input_categories)
if transformations==-1:
    print("Input Transformations : None")
else:
    print("Input Transformations : ",transformations)
if stats==-1:
    print("Input Condition based conditions : None")
else:
    print("Input Content based Conditions : ",stats)
print()
comp_score={}
no_of_rows={}
no_of_rows={}
get_matches()

Input Schema :  {'pos': 'object', 'rider': 'object', 'manufacturer': 'object'}
Input Categories : None
Input Transformations : None
Input Condition based conditions : None

only schema
Matching Tables
203_244.csv  :  1994 French motorcycle Grand Prix
203_35.csv  :  1996 Italian motorcycle Grand Prix
203_718.csv  :  1999 Valencian Community motorcycle Grand Prix
204_892.csv  :  1999 Dutch TT


203_244.csv(1994 French motorcycle Grand Prix)
Missing Values(NANs score):  {'pos': '0/34', 'rider': '0/34', 'manufacturer': '0/34', 'time/retired': '0/34', 'points': '19/34'}
Columns that match with input_schema:
 203_244.csv :  {'pos': 'pos', 'rider': 'rider', 'manufacturer': 'manufacturer'}
Coverage Score :  1.0 	 Completeness Score :  1.0

    pos                 rider manufacturer time/retired  points
0     1       Loris Capirossi        Honda    43:06.089    25.0
1     2       Doriano Romboni        Honda       +0.689    20.0
2     3            Max Biaggi      Aprilia       +1.181    16.0
3     4         Ralf Waldmann        Honda       +5.123    13.0
4     5     Jean-Michel Bayle      Aprilia       +5.528    11.0
5     6         Nobuatsu Aoki        Honda       +5.821    10.0
6     7  Jean Philippe Ruggia      Aprilia       +9.018     9.0
7     8        Tetsuya Harada       Yamaha      +24.059     8.0
8     9        Tadayuki Okada        Honda      +29.043     7.0
9    10      Wilco Zeelenberg        Honda      +36.273     6.0
10   11       Toshihiko Honma       Yamaha      +41.787     5.0
11   12       Adrien Bosshard        Honda      +52.489     4.0
12   13          Carlos Checa        Honda      +57.206     3.0
13   14           Eskil Suter      Aprilia    +1:01.503     2.0
14   15           Luis Maurel        Honda    +1:03.353     1.0
15   16  Patrick vd Goorbergh      Aprilia    +1:04.277     NaN
16   17         Adolf Stadler        Honda    +1:16.427     NaN
17   18            Juan Borja        Honda    +1:19.607     NaN
18   19    Chrisrian Boudinot      Aprilia    +1:20.163     NaN
19   20         Bernd Kassner      Aprilia    +1:20.761     NaN
20   21      Andreas Preining      Aprilia    +1:26.864     NaN
21   22            Noel Ferro        Honda    +1:27.009     NaN
22   23    Sebastien Scarnato        Honda    +1:36.321     NaN
23   24           Krisse Kaas       Yamaha       +1 Lap     NaN
24   25          Donnie Hough        Honda       +1 Lap     NaN
25  Ret            Rodney Fee        Honda   Retirement     NaN
26  Ret   Jurgen vd Goorbergh      Aprilia   Retirement     NaN
27  Ret          Luis D'Antin        Honda   Retirement     NaN
28  Ret      Manuel Hernandez      Aprilia   Retirement     NaN
29  Ret       Frederic Protat        Honda   Retirement     NaN
30  Ret     Giuseppe Fiorillo        Honda   Retirement     NaN
31  Ret     Jose Luis Cardoso      Aprilia   Retirement     NaN
32  Ret       Enrique de Juan      Aprilia   Retirement     NaN
33  Ret   Alessandro Gramigni      Aprilia   Retirement     NaN

203_35.csv(1996 Italian motorcycle Grand Prix)
Missing Values(NANs score):  {'pos': '0/31', 'rider': '0/31', 'manufacturer': '0/31', 'time/retired': '0/31', 'points': '16/31'}
Columns that match with input_schema:
 203_35.csv :  {'pos': 'pos', 'rider': 'rider', 'manufacturer': 'manufacturer'}
Coverage Score :  1.0 	 Completeness Score :  1.0

    pos                 rider manufacturer time/retired  points
0     1            Max Biaggi      Aprilia    40:36.299    25.0
1     2     Marcellino Lucchi      Aprilia       +6.914    20.0
2     3         Ralf Waldmann        Honda      +18.294    16.0
3     4        Olivier Jacque        Honda      +18.607    13.0
4     5          Jurgen Fuchs        Honda      +31.617    11.0
5     6        Tetsuya Harada       Yamaha      +31.649    10.0
6     7  Jean-Philippe Ruggia        Honda      +31.683     9.0
7     8         Nobuatsu Aoki        Honda      +47.701     8.0
8     9          Luis d'Antin        Honda      +51.186     7.0
9    10  Cristiano Migliorati        Honda      +51.556     6.0
10   11       Massimo Ottobre      Aprilia      +51.563     5.0
11   12           Eskil Suter      Aprilia      +51.613     4.0
12   13       Luca Boscoscuro      Aprilia      +51.617     3.0
13   14          Regis Laconi        Honda      +52.394     2.0
14   15   Jurgen vd Goorbergh        Honda      +52.569     1.0
15   16       Sebastian Porto      Aprilia    +1:03.619     NaN
16   17        Jamie Robinson      Aprilia    +1:06.917     NaN
17   18   Olivier Petrucciani      Aprilia    +1:06.945     NaN
18   19  Alessandro Antonello      Aprilia    +1:07.099     NaN
19   20        Osamu Miyazaki      Aprilia    +1:32.873     NaN
20   21         Davide Bulega      Aprilia    +1:32.902     NaN
21   22   Yasumasa Hatakeyama        Honda    +1:34.039     NaN
22   23       Franco Battaini      Aprilia    +1:34.363     NaN
23   24         Sete Gibernau        Honda    +1:34.931     NaN
24   25    Christian Boudinot      Aprilia    +1:41.263     NaN
25   26          Jose Barresi       Yamaha       +1 Lap     NaN
26   27         Roberto Rolfo      Aprilia       +1 Lap     NaN
27   28       Cristophe Cogan        Honda       +1 Lap     NaN
28  Ret    Gianluigi Scalvini        Honda   Retirement     NaN
29  Ret     Roberto Locatelli      Aprilia   Retirement     NaN
30  Ret     Takeshi Tsujimura        Honda   Retirement     NaN

203_718.csv(1999 Valencian Community motorcycle Grand Prix)
Missing Values(NANs score):  {'pos': '0/31', 'rider': '0/31', 'manufacturer': '0/31', 'time/retired': '0/31', 'points': '16/31'}
Columns that match with input_schema:
 203_718.csv :  {'pos': 'pos', 'rider': 'rider', 'manufacturer': 'manufacturer'}
Coverage Score :  1.0 	 Completeness Score :  1.0

    pos               rider manufacturer time/retired  points
0     1         Tohru Ukawa        Honda    49:50.449    25.0
1     2     Franco Battaini      Aprilia       +5.125    20.0
2     3     Loris Capirossi        Honda      +10.224    16.0
3     4       Shinya Nakano       Yamaha      +14.848    13.0
4     5    Stefano Perugini        Honda      +34.042    11.0
5     6     Sebastian Porto       Yamaha      +37.495    10.0
6     7       Jason Vincent        Honda      +44.911     9.0
7     8     Valentino Rossi      Aprilia    +1:01.110     8.0
8     9        Anthony West    TSR-Honda    +1:10.352     7.0
9    10        Alex Hofmann    TSR-Honda    +1:18.683     6.0
10   11     Luca Boscoscuro    TSR-Honda    +1:20.847     5.0
11   12  Lucas Oliver Bulto       Yamaha    +1:23.052     4.0
12   13       Roberto Rolfo      Aprilia    +1:24.329     3.0
13   14     Masaki Tokudome    TSR-Honda    +1:26.837     2.0
14   15         Fonsi Nieto       Yamaha    +1:45.669     1.0
15   16        David Garcia       Yamaha    +1:48.926     NaN
16   17         Scott Smart      Aprilia    +1:49.730     NaN
17   18          Alex Debon        Honda       +1 Lap     NaN
18   19       Jarno Janssen    TSR-Honda       +1 Lap     NaN
19  Ret       Alvaro Molina        Honda   Retirement     NaN
20  Ret     Julien Allemand    TSR-Honda   Retirement     NaN
21  Ret      Ismael Bonilla        Honda   Retirement     NaN
22  Ret      Daniel Ribalta      Aprilia   Retirement     NaN
23  Ret     Maurice Bolwerk        Honda   Retirement     NaN
24  Ret       Tomomi Manako       Yamaha   Retirement     NaN
25  Ret    Johann Stigefelt       Yamaha   Retirement     NaN
26  Ret      Olivier Jacque       Yamaha   Retirement     NaN
27  Ret   Jeremy McWilliams      Aprilia   Retirement     NaN
28  Ret        David Ortega    TSR-Honda   Retirement     NaN
29  Ret        Alfredo Rios      Aprilia   Retirement     NaN
30  Ret       Ralf Waldmann      Aprilia   Retirement     NaN

204_892.csv(1999 Dutch TT)
Missing Values(NANs score):  {'pos': '0/28', 'rider': '0/28', 'manufacturer': '0/28', 'time/retired': '0/28', 'points': '13/28'}
Columns that match with input_schema:
 204_892.csv :  {'pos': 'pos', 'rider': 'rider', 'manufacturer': 'manufacturer'}
Coverage Score :  1.0 	 Completeness Score :  1.0

    pos                 rider manufacturer time/retired  points
0     1       Loris Capirossi        Honda    38:04.730    25.0
1     2       Valentino Rossi      Aprilia       +0.180    20.0
2     3     Jeremy McWilliams      Aprilia       +0.534    16.0
3     4           Tohru Ukawa        Honda       +0.537    13.0
4     5         Shinya Nakano       Yamaha       +0.742    11.0
5     6         Ralf Waldmann      Aprilia       +7.019    10.0
6     7       Franco Battaini      Aprilia      +20.889     9.0
7     8      Stefano Perugini        Honda      +20.891     8.0
8     9         Jason Vincent        Honda      +21.310     7.0
9    10          Anthony West    TSR-Honda      +26.816     6.0
10   11          Alex Hofmann    TSR-Honda      +26.933     5.0
11   12       Sebastian Porto       Yamaha      +27.054     4.0
12   13         Tomomi Manako       Yamaha      +27.903     3.0
13   14       Masaki Tokudome    TSR-Honda      +33.161     2.0
14   15         Jarno Janssen    TSR-Honda      +56.248     1.0
15   16       Luca Boscoscuro    TSR-Honda      +56.432     NaN
16   17      Johann Stigefelt       Yamaha    +1:07.433     NaN
17   18       Julien Allemand    TSR-Honda    +1:16.347     NaN
18   19           Fonsi Nieto       Yamaha    +1:25.622     NaN
19   20    Lucas Oliver Bulto       Yamaha    +1:25.758     NaN
20   21          David Garcia       Yamaha    +1:33.867     NaN
21   22         Rudie Markink      Aprilia    +1:40.280     NaN
22   23         Arno Visscher      Aprilia    +1:40.635     NaN
23   24  Henk Van De Lagemaat        Honda       +1 Lap     NaN
24  Ret       Maurice Bolwerk    TSR-Honda   Retirement     NaN
25  Ret          Andre Romein        Honda   Retirement     NaN
26  Ret         Roberto Rolfo      Aprilia   Retirement     NaN
27  Ret     Marcellino Lucchi      Aprilia   Retirement     NaN

1.csv : 203_244.csv(1994 French motorcycle Grand Prix)		203_35.csv(1996 Italian motorcycle Grand Prix)		203_718.csv(1999 Valencian Community motorcycle Grand Prix)		204_892.csv(1999 Dutch TT)
Missing Values(NANs):  {'pos': '0/124', 'rider': '0/124', 'manufacturer': '0/124', 'time/retired': '0/124'}
Columns that match with input_schema:
203_244.csv :  {'pos': 'pos', 'rider': 'rider', 'manufacturer': 'manufacturer'}
203_35.csv :  {'pos': 'pos', 'rider': 'rider', 'manufacturer': 'manufacturer'}
203_718.csv :  {'pos': 'pos', 'rider': 'rider', 'manufacturer': 'manufacturer'}
204_892.csv :  {'pos': 'pos', 'rider': 'rider', 'manufacturer': 'manufacturer'}
Coverage Score :  1.0 	 Completeness Score :  1.0

     pos                 rider manufacturer time/retired
0      1       Loris Capirossi        Honda    43:06.089
1      2       Doriano Romboni        Honda       +0.689
2      3            Max Biaggi      Aprilia       +1.181
3      4         Ralf Waldmann        Honda       +5.123
4      5     Jean-Michel Bayle      Aprilia       +5.528
5      6         Nobuatsu Aoki        Honda       +5.821
6      7  Jean Philippe Ruggia      Aprilia       +9.018
7      8        Tetsuya Harada       Yamaha      +24.059
8      9        Tadayuki Okada        Honda      +29.043
9     10      Wilco Zeelenberg        Honda      +36.273
10    11       Toshihiko Honma       Yamaha      +41.787
11    12       Adrien Bosshard        Honda      +52.489
12    13          Carlos Checa        Honda      +57.206
13    14           Eskil Suter      Aprilia    +1:01.503
14    15           Luis Maurel        Honda    +1:03.353
15    16  Patrick vd Goorbergh      Aprilia    +1:04.277
16    17         Adolf Stadler        Honda    +1:16.427
17    18            Juan Borja        Honda    +1:19.607
18    19    Chrisrian Boudinot      Aprilia    +1:20.163
19    20         Bernd Kassner      Aprilia    +1:20.761
20    21      Andreas Preining      Aprilia    +1:26.864
21    22            Noel Ferro        Honda    +1:27.009
22    23    Sebastien Scarnato        Honda    +1:36.321
23    24           Krisse Kaas       Yamaha       +1 Lap
24    25          Donnie Hough        Honda       +1 Lap
25   Ret            Rodney Fee        Honda   Retirement
26   Ret   Jurgen vd Goorbergh      Aprilia   Retirement
27   Ret          Luis D'Antin        Honda   Retirement
28   Ret      Manuel Hernandez      Aprilia   Retirement
29   Ret       Frederic Protat        Honda   Retirement
..   ...                   ...          ...          ...
94   Ret          Alfredo Rios      Aprilia   Retirement
95   Ret         Ralf Waldmann      Aprilia   Retirement
96     1       Loris Capirossi        Honda    38:04.730
97     2       Valentino Rossi      Aprilia       +0.180
98     3     Jeremy McWilliams      Aprilia       +0.534
99     4           Tohru Ukawa        Honda       +0.537
100    5         Shinya Nakano       Yamaha       +0.742
101    6         Ralf Waldmann      Aprilia       +7.019
102    7       Franco Battaini      Aprilia      +20.889
103    8      Stefano Perugini        Honda      +20.891
104    9         Jason Vincent        Honda      +21.310
105   10          Anthony West    TSR-Honda      +26.816
106   11          Alex Hofmann    TSR-Honda      +26.933
107   12       Sebastian Porto       Yamaha      +27.054
108   13         Tomomi Manako       Yamaha      +27.903
109   14       Masaki Tokudome    TSR-Honda      +33.161
110   15         Jarno Janssen    TSR-Honda      +56.248
111   16       Luca Boscoscuro    TSR-Honda      +56.432
112   17      Johann Stigefelt       Yamaha    +1:07.433
113   18       Julien Allemand    TSR-Honda    +1:16.347
114   19           Fonsi Nieto       Yamaha    +1:25.622
115   20    Lucas Oliver Bulto       Yamaha    +1:25.758
116   21          David Garcia       Yamaha    +1:33.867
117   22         Rudie Markink      Aprilia    +1:40.280
118   23         Arno Visscher      Aprilia    +1:40.635
119   24  Henk Van De Lagemaat        Honda       +1 Lap
120  Ret       Maurice Bolwerk    TSR-Honda   Retirement
121  Ret          Andre Romein        Honda   Retirement
122  Ret         Roberto Rolfo      Aprilia   Retirement
123  Ret     Marcellino Lucchi      Aprilia   Retirement

[124 rows x 4 columns]

2.csv : 203_244.csv(1994 French motorcycle Grand Prix)		203_35.csv(1996 Italian motorcycle Grand Prix)		203_718.csv(1999 Valencian Community motorcycle Grand Prix)
Missing Values(NANs):  {'pos': '0/96', 'rider': '0/96', 'manufacturer': '0/96', 'time/retired': '0/96'}
Columns that match with input_schema:
203_244.csv :  {'pos': 'pos', 'rider': 'rider', 'manufacturer': 'manufacturer'}
203_35.csv :  {'pos': 'pos', 'rider': 'rider', 'manufacturer': 'manufacturer'}
203_718.csv :  {'pos': 'pos', 'rider': 'rider', 'manufacturer': 'manufacturer'}
Coverage Score :  1.0 	 Completeness Score :  1.0

    pos                 rider manufacturer time/retired
0     1       Loris Capirossi        Honda    43:06.089
1     2       Doriano Romboni        Honda       +0.689
2     3            Max Biaggi      Aprilia       +1.181
3     4         Ralf Waldmann        Honda       +5.123
4     5     Jean-Michel Bayle      Aprilia       +5.528
5     6         Nobuatsu Aoki        Honda       +5.821
6     7  Jean Philippe Ruggia      Aprilia       +9.018
7     8        Tetsuya Harada       Yamaha      +24.059
8     9        Tadayuki Okada        Honda      +29.043
9    10      Wilco Zeelenberg        Honda      +36.273
10   11       Toshihiko Honma       Yamaha      +41.787
11   12       Adrien Bosshard        Honda      +52.489
12   13          Carlos Checa        Honda      +57.206
13   14           Eskil Suter      Aprilia    +1:01.503
14   15           Luis Maurel        Honda    +1:03.353
15   16  Patrick vd Goorbergh      Aprilia    +1:04.277
16   17         Adolf Stadler        Honda    +1:16.427
17   18            Juan Borja        Honda    +1:19.607
18   19    Chrisrian Boudinot      Aprilia    +1:20.163
19   20         Bernd Kassner      Aprilia    +1:20.761
20   21      Andreas Preining      Aprilia    +1:26.864
21   22            Noel Ferro        Honda    +1:27.009
22   23    Sebastien Scarnato        Honda    +1:36.321
23   24           Krisse Kaas       Yamaha       +1 Lap
24   25          Donnie Hough        Honda       +1 Lap
25  Ret            Rodney Fee        Honda   Retirement
26  Ret   Jurgen vd Goorbergh      Aprilia   Retirement
27  Ret          Luis D'Antin        Honda   Retirement
28  Ret      Manuel Hernandez      Aprilia   Retirement
29  Ret       Frederic Protat        Honda   Retirement
..  ...                   ...          ...          ...
66    2       Franco Battaini      Aprilia       +5.125
67    3       Loris Capirossi        Honda      +10.224
68    4         Shinya Nakano       Yamaha      +14.848
69    5      Stefano Perugini        Honda      +34.042
70    6       Sebastian Porto       Yamaha      +37.495
71    7         Jason Vincent        Honda      +44.911
72    8       Valentino Rossi      Aprilia    +1:01.110
73    9          Anthony West    TSR-Honda    +1:10.352
74   10          Alex Hofmann    TSR-Honda    +1:18.683
75   11       Luca Boscoscuro    TSR-Honda    +1:20.847
76   12    Lucas Oliver Bulto       Yamaha    +1:23.052
77   13         Roberto Rolfo      Aprilia    +1:24.329
78   14       Masaki Tokudome    TSR-Honda    +1:26.837
79   15           Fonsi Nieto       Yamaha    +1:45.669
80   16          David Garcia       Yamaha    +1:48.926
81   17           Scott Smart      Aprilia    +1:49.730
82   18            Alex Debon        Honda       +1 Lap
83   19         Jarno Janssen    TSR-Honda       +1 Lap
84  Ret         Alvaro Molina        Honda   Retirement
85  Ret       Julien Allemand    TSR-Honda   Retirement
86  Ret        Ismael Bonilla        Honda   Retirement
87  Ret        Daniel Ribalta      Aprilia   Retirement
88  Ret       Maurice Bolwerk        Honda   Retirement
89  Ret         Tomomi Manako       Yamaha   Retirement
90  Ret      Johann Stigefelt       Yamaha   Retirement
91  Ret        Olivier Jacque       Yamaha   Retirement
92  Ret     Jeremy McWilliams      Aprilia   Retirement
93  Ret          David Ortega    TSR-Honda   Retirement
94  Ret          Alfredo Rios      Aprilia   Retirement
95  Ret         Ralf Waldmann      Aprilia   Retirement

[96 rows x 4 columns]

3.csv : 203_244.csv(1994 French motorcycle Grand Prix)		203_35.csv(1996 Italian motorcycle Grand Prix)		204_892.csv(1999 Dutch TT)
Missing Values(NANs):  {'pos': '0/93', 'rider': '0/93', 'manufacturer': '0/93', 'time/retired': '0/93'}
Columns that match with input_schema:
203_244.csv :  {'pos': 'pos', 'rider': 'rider', 'manufacturer': 'manufacturer'}
203_35.csv :  {'pos': 'pos', 'rider': 'rider', 'manufacturer': 'manufacturer'}
204_892.csv :  {'pos': 'pos', 'rider': 'rider', 'manufacturer': 'manufacturer'}
Coverage Score :  1.0 	 Completeness Score :  1.0

    pos                 rider manufacturer time/retired
0     1       Loris Capirossi        Honda    43:06.089
1     2       Doriano Romboni        Honda       +0.689
2     3            Max Biaggi      Aprilia       +1.181
3     4         Ralf Waldmann        Honda       +5.123
4     5     Jean-Michel Bayle      Aprilia       +5.528
5     6         Nobuatsu Aoki        Honda       +5.821
6     7  Jean Philippe Ruggia      Aprilia       +9.018
7     8        Tetsuya Harada       Yamaha      +24.059
8     9        Tadayuki Okada        Honda      +29.043
9    10      Wilco Zeelenberg        Honda      +36.273
10   11       Toshihiko Honma       Yamaha      +41.787
11   12       Adrien Bosshard        Honda      +52.489
12   13          Carlos Checa        Honda      +57.206
13   14           Eskil Suter      Aprilia    +1:01.503
14   15           Luis Maurel        Honda    +1:03.353
15   16  Patrick vd Goorbergh      Aprilia    +1:04.277
16   17         Adolf Stadler        Honda    +1:16.427
17   18            Juan Borja        Honda    +1:19.607
18   19    Chrisrian Boudinot      Aprilia    +1:20.163
19   20         Bernd Kassner      Aprilia    +1:20.761
20   21      Andreas Preining      Aprilia    +1:26.864
21   22            Noel Ferro        Honda    +1:27.009
22   23    Sebastien Scarnato        Honda    +1:36.321
23   24           Krisse Kaas       Yamaha       +1 Lap
24   25          Donnie Hough        Honda       +1 Lap
25  Ret            Rodney Fee        Honda   Retirement
26  Ret   Jurgen vd Goorbergh      Aprilia   Retirement
27  Ret          Luis D'Antin        Honda   Retirement
28  Ret      Manuel Hernandez      Aprilia   Retirement
29  Ret       Frederic Protat        Honda   Retirement
..  ...                   ...          ...          ...
63  Ret     Roberto Locatelli      Aprilia   Retirement
64  Ret     Takeshi Tsujimura        Honda   Retirement
65    1       Loris Capirossi        Honda    38:04.730
66    2       Valentino Rossi      Aprilia       +0.180
67    3     Jeremy McWilliams      Aprilia       +0.534
68    4           Tohru Ukawa        Honda       +0.537
69    5         Shinya Nakano       Yamaha       +0.742
70    6         Ralf Waldmann      Aprilia       +7.019
71    7       Franco Battaini      Aprilia      +20.889
72    8      Stefano Perugini        Honda      +20.891
73    9         Jason Vincent        Honda      +21.310
74   10          Anthony West    TSR-Honda      +26.816
75   11          Alex Hofmann    TSR-Honda      +26.933
76   12       Sebastian Porto       Yamaha      +27.054
77   13         Tomomi Manako       Yamaha      +27.903
78   14       Masaki Tokudome    TSR-Honda      +33.161
79   15         Jarno Janssen    TSR-Honda      +56.248
80   16       Luca Boscoscuro    TSR-Honda      +56.432
81   17      Johann Stigefelt       Yamaha    +1:07.433
82   18       Julien Allemand    TSR-Honda    +1:16.347
83   19           Fonsi Nieto       Yamaha    +1:25.622
84   20    Lucas Oliver Bulto       Yamaha    +1:25.758
85   21          David Garcia       Yamaha    +1:33.867
86   22         Rudie Markink      Aprilia    +1:40.280
87   23         Arno Visscher      Aprilia    +1:40.635
88   24  Henk Van De Lagemaat        Honda       +1 Lap
89  Ret       Maurice Bolwerk    TSR-Honda   Retirement
90  Ret          Andre Romein        Honda   Retirement
91  Ret         Roberto Rolfo      Aprilia   Retirement
92  Ret     Marcellino Lucchi      Aprilia   Retirement

[93 rows x 4 columns]

4.csv : 203_244.csv(1994 French motorcycle Grand Prix)		203_718.csv(1999 Valencian Community motorcycle Grand Prix)		204_892.csv(1999 Dutch TT)
Missing Values(NANs):  {'pos': '0/93', 'rider': '0/93', 'manufacturer': '0/93', 'time/retired': '0/93'}
Columns that match with input_schema:
203_244.csv :  {'pos': 'pos', 'rider': 'rider', 'manufacturer': 'manufacturer'}
203_718.csv :  {'pos': 'pos', 'rider': 'rider', 'manufacturer': 'manufacturer'}
204_892.csv :  {'pos': 'pos', 'rider': 'rider', 'manufacturer': 'manufacturer'}
Coverage Score :  1.0 	 Completeness Score :  1.0

    pos                 rider manufacturer time/retired
0     1       Loris Capirossi        Honda    43:06.089
1     2       Doriano Romboni        Honda       +0.689
2     3            Max Biaggi      Aprilia       +1.181
3     4         Ralf Waldmann        Honda       +5.123
4     5     Jean-Michel Bayle      Aprilia       +5.528
5     6         Nobuatsu Aoki        Honda       +5.821
6     7  Jean Philippe Ruggia      Aprilia       +9.018
7     8        Tetsuya Harada       Yamaha      +24.059
8     9        Tadayuki Okada        Honda      +29.043
9    10      Wilco Zeelenberg        Honda      +36.273
10   11       Toshihiko Honma       Yamaha      +41.787
11   12       Adrien Bosshard        Honda      +52.489
12   13          Carlos Checa        Honda      +57.206
13   14           Eskil Suter      Aprilia    +1:01.503
14   15           Luis Maurel        Honda    +1:03.353
15   16  Patrick vd Goorbergh      Aprilia    +1:04.277
16   17         Adolf Stadler        Honda    +1:16.427
17   18            Juan Borja        Honda    +1:19.607
18   19    Chrisrian Boudinot      Aprilia    +1:20.163
19   20         Bernd Kassner      Aprilia    +1:20.761
20   21      Andreas Preining      Aprilia    +1:26.864
21   22            Noel Ferro        Honda    +1:27.009
22   23    Sebastien Scarnato        Honda    +1:36.321
23   24           Krisse Kaas       Yamaha       +1 Lap
24   25          Donnie Hough        Honda       +1 Lap
25  Ret            Rodney Fee        Honda   Retirement
26  Ret   Jurgen vd Goorbergh      Aprilia   Retirement
27  Ret          Luis D'Antin        Honda   Retirement
28  Ret      Manuel Hernandez      Aprilia   Retirement
29  Ret       Frederic Protat        Honda   Retirement
..  ...                   ...          ...          ...
63  Ret          Alfredo Rios      Aprilia   Retirement
64  Ret         Ralf Waldmann      Aprilia   Retirement
65    1       Loris Capirossi        Honda    38:04.730
66    2       Valentino Rossi      Aprilia       +0.180
67    3     Jeremy McWilliams      Aprilia       +0.534
68    4           Tohru Ukawa        Honda       +0.537
69    5         Shinya Nakano       Yamaha       +0.742
70    6         Ralf Waldmann      Aprilia       +7.019
71    7       Franco Battaini      Aprilia      +20.889
72    8      Stefano Perugini        Honda      +20.891
73    9         Jason Vincent        Honda      +21.310
74   10          Anthony West    TSR-Honda      +26.816
75   11          Alex Hofmann    TSR-Honda      +26.933
76   12       Sebastian Porto       Yamaha      +27.054
77   13         Tomomi Manako       Yamaha      +27.903
78   14       Masaki Tokudome    TSR-Honda      +33.161
79   15         Jarno Janssen    TSR-Honda      +56.248
80   16       Luca Boscoscuro    TSR-Honda      +56.432
81   17      Johann Stigefelt       Yamaha    +1:07.433
82   18       Julien Allemand    TSR-Honda    +1:16.347
83   19           Fonsi Nieto       Yamaha    +1:25.622
84   20    Lucas Oliver Bulto       Yamaha    +1:25.758
85   21          David Garcia       Yamaha    +1:33.867
86   22         Rudie Markink      Aprilia    +1:40.280
87   23         Arno Visscher      Aprilia    +1:40.635
88   24  Henk Van De Lagemaat        Honda       +1 Lap
89  Ret       Maurice Bolwerk    TSR-Honda   Retirement
90  Ret          Andre Romein        Honda   Retirement
91  Ret         Roberto Rolfo      Aprilia   Retirement
92  Ret     Marcellino Lucchi      Aprilia   Retirement

[93 rows x 4 columns]

5.csv : 203_35.csv(1996 Italian motorcycle Grand Prix)		203_718.csv(1999 Valencian Community motorcycle Grand Prix)		204_892.csv(1999 Dutch TT)
Missing Values(NANs):  {'pos': '0/90', 'rider': '0/90', 'manufacturer': '0/90', 'time/retired': '0/90'}
Columns that match with input_schema:
203_35.csv :  {'pos': 'pos', 'rider': 'rider', 'manufacturer': 'manufacturer'}
203_718.csv :  {'pos': 'pos', 'rider': 'rider', 'manufacturer': 'manufacturer'}
204_892.csv :  {'pos': 'pos', 'rider': 'rider', 'manufacturer': 'manufacturer'}
Coverage Score :  1.0 	 Completeness Score :  1.0

    pos                 rider manufacturer time/retired
0     1            Max Biaggi      Aprilia    40:36.299
1     2     Marcellino Lucchi      Aprilia       +6.914
2     3         Ralf Waldmann        Honda      +18.294
3     4        Olivier Jacque        Honda      +18.607
4     5          Jurgen Fuchs        Honda      +31.617
5     6        Tetsuya Harada       Yamaha      +31.649
6     7  Jean-Philippe Ruggia        Honda      +31.683
7     8         Nobuatsu Aoki        Honda      +47.701
8     9          Luis d'Antin        Honda      +51.186
9    10  Cristiano Migliorati        Honda      +51.556
10   11       Massimo Ottobre      Aprilia      +51.563
11   12           Eskil Suter      Aprilia      +51.613
12   13       Luca Boscoscuro      Aprilia      +51.617
13   14          Regis Laconi        Honda      +52.394
14   15   Jurgen vd Goorbergh        Honda      +52.569
15   16       Sebastian Porto      Aprilia    +1:03.619
16   17        Jamie Robinson      Aprilia    +1:06.917
17   18   Olivier Petrucciani      Aprilia    +1:06.945
18   19  Alessandro Antonello      Aprilia    +1:07.099
19   20        Osamu Miyazaki      Aprilia    +1:32.873
20   21         Davide Bulega      Aprilia    +1:32.902
21   22   Yasumasa Hatakeyama        Honda    +1:34.039
22   23       Franco Battaini      Aprilia    +1:34.363
23   24         Sete Gibernau        Honda    +1:34.931
24   25    Christian Boudinot      Aprilia    +1:41.263
25   26          Jose Barresi       Yamaha       +1 Lap
26   27         Roberto Rolfo      Aprilia       +1 Lap
27   28       Cristophe Cogan        Honda       +1 Lap
28  Ret    Gianluigi Scalvini        Honda   Retirement
29  Ret     Roberto Locatelli      Aprilia   Retirement
..  ...                   ...          ...          ...
60  Ret          Alfredo Rios      Aprilia   Retirement
61  Ret         Ralf Waldmann      Aprilia   Retirement
62    1       Loris Capirossi        Honda    38:04.730
63    2       Valentino Rossi      Aprilia       +0.180
64    3     Jeremy McWilliams      Aprilia       +0.534
65    4           Tohru Ukawa        Honda       +0.537
66    5         Shinya Nakano       Yamaha       +0.742
67    6         Ralf Waldmann      Aprilia       +7.019
68    7       Franco Battaini      Aprilia      +20.889
69    8      Stefano Perugini        Honda      +20.891
70    9         Jason Vincent        Honda      +21.310
71   10          Anthony West    TSR-Honda      +26.816
72   11          Alex Hofmann    TSR-Honda      +26.933
73   12       Sebastian Porto       Yamaha      +27.054
74   13         Tomomi Manako       Yamaha      +27.903
75   14       Masaki Tokudome    TSR-Honda      +33.161
76   15         Jarno Janssen    TSR-Honda      +56.248
77   16       Luca Boscoscuro    TSR-Honda      +56.432
78   17      Johann Stigefelt       Yamaha    +1:07.433
79   18       Julien Allemand    TSR-Honda    +1:16.347
80   19           Fonsi Nieto       Yamaha    +1:25.622
81   20    Lucas Oliver Bulto       Yamaha    +1:25.758
82   21          David Garcia       Yamaha    +1:33.867
83   22         Rudie Markink      Aprilia    +1:40.280
84   23         Arno Visscher      Aprilia    +1:40.635
85   24  Henk Van De Lagemaat        Honda       +1 Lap
86  Ret       Maurice Bolwerk    TSR-Honda   Retirement
87  Ret          Andre Romein        Honda   Retirement
88  Ret         Roberto Rolfo      Aprilia   Retirement
89  Ret     Marcellino Lucchi      Aprilia   Retirement

[90 rows x 4 columns]

6.csv : 203_244.csv(1994 French motorcycle Grand Prix)		203_35.csv(1996 Italian motorcycle Grand Prix)
Missing Values(NANs):  {'pos': '0/65', 'rider': '0/65', 'manufacturer': '0/65', 'time/retired': '0/65'}
Columns that match with input_schema:
203_244.csv :  {'pos': 'pos', 'rider': 'rider', 'manufacturer': 'manufacturer'}
203_35.csv :  {'pos': 'pos', 'rider': 'rider', 'manufacturer': 'manufacturer'}
Coverage Score :  1.0 	 Completeness Score :  1.0

    pos                 rider manufacturer time/retired
0     1       Loris Capirossi        Honda    43:06.089
1     2       Doriano Romboni        Honda       +0.689
2     3            Max Biaggi      Aprilia       +1.181
3     4         Ralf Waldmann        Honda       +5.123
4     5     Jean-Michel Bayle      Aprilia       +5.528
5     6         Nobuatsu Aoki        Honda       +5.821
6     7  Jean Philippe Ruggia      Aprilia       +9.018
7     8        Tetsuya Harada       Yamaha      +24.059
8     9        Tadayuki Okada        Honda      +29.043
9    10      Wilco Zeelenberg        Honda      +36.273
10   11       Toshihiko Honma       Yamaha      +41.787
11   12       Adrien Bosshard        Honda      +52.489
12   13          Carlos Checa        Honda      +57.206
13   14           Eskil Suter      Aprilia    +1:01.503
14   15           Luis Maurel        Honda    +1:03.353
15   16  Patrick vd Goorbergh      Aprilia    +1:04.277
16   17         Adolf Stadler        Honda    +1:16.427
17   18            Juan Borja        Honda    +1:19.607
18   19    Chrisrian Boudinot      Aprilia    +1:20.163
19   20         Bernd Kassner      Aprilia    +1:20.761
20   21      Andreas Preining      Aprilia    +1:26.864
21   22            Noel Ferro        Honda    +1:27.009
22   23    Sebastien Scarnato        Honda    +1:36.321
23   24           Krisse Kaas       Yamaha       +1 Lap
24   25          Donnie Hough        Honda       +1 Lap
25  Ret            Rodney Fee        Honda   Retirement
26  Ret   Jurgen vd Goorbergh      Aprilia   Retirement
27  Ret          Luis D'Antin        Honda   Retirement
28  Ret      Manuel Hernandez      Aprilia   Retirement
29  Ret       Frederic Protat        Honda   Retirement
..  ...                   ...          ...          ...
35    2     Marcellino Lucchi      Aprilia       +6.914
36    3         Ralf Waldmann        Honda      +18.294
37    4        Olivier Jacque        Honda      +18.607
38    5          Jurgen Fuchs        Honda      +31.617
39    6        Tetsuya Harada       Yamaha      +31.649
40    7  Jean-Philippe Ruggia        Honda      +31.683
41    8         Nobuatsu Aoki        Honda      +47.701
42    9          Luis d'Antin        Honda      +51.186
43   10  Cristiano Migliorati        Honda      +51.556
44   11       Massimo Ottobre      Aprilia      +51.563
45   12           Eskil Suter      Aprilia      +51.613
46   13       Luca Boscoscuro      Aprilia      +51.617
47   14          Regis Laconi        Honda      +52.394
48   15   Jurgen vd Goorbergh        Honda      +52.569
49   16       Sebastian Porto      Aprilia    +1:03.619
50   17        Jamie Robinson      Aprilia    +1:06.917
51   18   Olivier Petrucciani      Aprilia    +1:06.945
52   19  Alessandro Antonello      Aprilia    +1:07.099
53   20        Osamu Miyazaki      Aprilia    +1:32.873
54   21         Davide Bulega      Aprilia    +1:32.902
55   22   Yasumasa Hatakeyama        Honda    +1:34.039
56   23       Franco Battaini      Aprilia    +1:34.363
57   24         Sete Gibernau        Honda    +1:34.931
58   25    Christian Boudinot      Aprilia    +1:41.263
59   26          Jose Barresi       Yamaha       +1 Lap
60   27         Roberto Rolfo      Aprilia       +1 Lap
61   28       Cristophe Cogan        Honda       +1 Lap
62  Ret    Gianluigi Scalvini        Honda   Retirement
63  Ret     Roberto Locatelli      Aprilia   Retirement
64  Ret     Takeshi Tsujimura        Honda   Retirement

[65 rows x 4 columns]

7.csv : 203_244.csv(1994 French motorcycle Grand Prix)		203_718.csv(1999 Valencian Community motorcycle Grand Prix)
Missing Values(NANs):  {'pos': '0/65', 'rider': '0/65', 'manufacturer': '0/65', 'time/retired': '0/65'}
Columns that match with input_schema:
203_244.csv :  {'pos': 'pos', 'rider': 'rider', 'manufacturer': 'manufacturer'}
203_718.csv :  {'pos': 'pos', 'rider': 'rider', 'manufacturer': 'manufacturer'}
Coverage Score :  1.0 	 Completeness Score :  1.0

    pos                 rider manufacturer time/retired
0     1       Loris Capirossi        Honda    43:06.089
1     2       Doriano Romboni        Honda       +0.689
2     3            Max Biaggi      Aprilia       +1.181
3     4         Ralf Waldmann        Honda       +5.123
4     5     Jean-Michel Bayle      Aprilia       +5.528
5     6         Nobuatsu Aoki        Honda       +5.821
6     7  Jean Philippe Ruggia      Aprilia       +9.018
7     8        Tetsuya Harada       Yamaha      +24.059
8     9        Tadayuki Okada        Honda      +29.043
9    10      Wilco Zeelenberg        Honda      +36.273
10   11       Toshihiko Honma       Yamaha      +41.787
11   12       Adrien Bosshard        Honda      +52.489
12   13          Carlos Checa        Honda      +57.206
13   14           Eskil Suter      Aprilia    +1:01.503
14   15           Luis Maurel        Honda    +1:03.353
15   16  Patrick vd Goorbergh      Aprilia    +1:04.277
16   17         Adolf Stadler        Honda    +1:16.427
17   18            Juan Borja        Honda    +1:19.607
18   19    Chrisrian Boudinot      Aprilia    +1:20.163
19   20         Bernd Kassner      Aprilia    +1:20.761
20   21      Andreas Preining      Aprilia    +1:26.864
21   22            Noel Ferro        Honda    +1:27.009
22   23    Sebastien Scarnato        Honda    +1:36.321
23   24           Krisse Kaas       Yamaha       +1 Lap
24   25          Donnie Hough        Honda       +1 Lap
25  Ret            Rodney Fee        Honda   Retirement
26  Ret   Jurgen vd Goorbergh      Aprilia   Retirement
27  Ret          Luis D'Antin        Honda   Retirement
28  Ret      Manuel Hernandez      Aprilia   Retirement
29  Ret       Frederic Protat        Honda   Retirement
..  ...                   ...          ...          ...
35    2       Franco Battaini      Aprilia       +5.125
36    3       Loris Capirossi        Honda      +10.224
37    4         Shinya Nakano       Yamaha      +14.848
38    5      Stefano Perugini        Honda      +34.042
39    6       Sebastian Porto       Yamaha      +37.495
40    7         Jason Vincent        Honda      +44.911
41    8       Valentino Rossi      Aprilia    +1:01.110
42    9          Anthony West    TSR-Honda    +1:10.352
43   10          Alex Hofmann    TSR-Honda    +1:18.683
44   11       Luca Boscoscuro    TSR-Honda    +1:20.847
45   12    Lucas Oliver Bulto       Yamaha    +1:23.052
46   13         Roberto Rolfo      Aprilia    +1:24.329
47   14       Masaki Tokudome    TSR-Honda    +1:26.837
48   15           Fonsi Nieto       Yamaha    +1:45.669
49   16          David Garcia       Yamaha    +1:48.926
50   17           Scott Smart      Aprilia    +1:49.730
51   18            Alex Debon        Honda       +1 Lap
52   19         Jarno Janssen    TSR-Honda       +1 Lap
53  Ret         Alvaro Molina        Honda   Retirement
54  Ret       Julien Allemand    TSR-Honda   Retirement
55  Ret        Ismael Bonilla        Honda   Retirement
56  Ret        Daniel Ribalta      Aprilia   Retirement
57  Ret       Maurice Bolwerk        Honda   Retirement
58  Ret         Tomomi Manako       Yamaha   Retirement
59  Ret      Johann Stigefelt       Yamaha   Retirement
60  Ret        Olivier Jacque       Yamaha   Retirement
61  Ret     Jeremy McWilliams      Aprilia   Retirement
62  Ret          David Ortega    TSR-Honda   Retirement
63  Ret          Alfredo Rios      Aprilia   Retirement
64  Ret         Ralf Waldmann      Aprilia   Retirement

[65 rows x 4 columns]

8.csv : 203_244.csv(1994 French motorcycle Grand Prix)		204_892.csv(1999 Dutch TT)
Missing Values(NANs):  {'pos': '0/62', 'rider': '0/62', 'manufacturer': '0/62', 'time/retired': '0/62'}
Columns that match with input_schema:
203_244.csv :  {'pos': 'pos', 'rider': 'rider', 'manufacturer': 'manufacturer'}
204_892.csv :  {'pos': 'pos', 'rider': 'rider', 'manufacturer': 'manufacturer'}
Coverage Score :  1.0 	 Completeness Score :  1.0

    pos                 rider manufacturer time/retired
0     1       Loris Capirossi        Honda    43:06.089
1     2       Doriano Romboni        Honda       +0.689
2     3            Max Biaggi      Aprilia       +1.181
3     4         Ralf Waldmann        Honda       +5.123
4     5     Jean-Michel Bayle      Aprilia       +5.528
5     6         Nobuatsu Aoki        Honda       +5.821
6     7  Jean Philippe Ruggia      Aprilia       +9.018
7     8        Tetsuya Harada       Yamaha      +24.059
8     9        Tadayuki Okada        Honda      +29.043
9    10      Wilco Zeelenberg        Honda      +36.273
10   11       Toshihiko Honma       Yamaha      +41.787
11   12       Adrien Bosshard        Honda      +52.489
12   13          Carlos Checa        Honda      +57.206
13   14           Eskil Suter      Aprilia    +1:01.503
14   15           Luis Maurel        Honda    +1:03.353
15   16  Patrick vd Goorbergh      Aprilia    +1:04.277
16   17         Adolf Stadler        Honda    +1:16.427
17   18            Juan Borja        Honda    +1:19.607
18   19    Chrisrian Boudinot      Aprilia    +1:20.163
19   20         Bernd Kassner      Aprilia    +1:20.761
20   21      Andreas Preining      Aprilia    +1:26.864
21   22            Noel Ferro        Honda    +1:27.009
22   23    Sebastien Scarnato        Honda    +1:36.321
23   24           Krisse Kaas       Yamaha       +1 Lap
24   25          Donnie Hough        Honda       +1 Lap
25  Ret            Rodney Fee        Honda   Retirement
26  Ret   Jurgen vd Goorbergh      Aprilia   Retirement
27  Ret          Luis D'Antin        Honda   Retirement
28  Ret      Manuel Hernandez      Aprilia   Retirement
29  Ret       Frederic Protat        Honda   Retirement
..  ...                   ...          ...          ...
32  Ret       Enrique de Juan      Aprilia   Retirement
33  Ret   Alessandro Gramigni      Aprilia   Retirement
34    1       Loris Capirossi        Honda    38:04.730
35    2       Valentino Rossi      Aprilia       +0.180
36    3     Jeremy McWilliams      Aprilia       +0.534
37    4           Tohru Ukawa        Honda       +0.537
38    5         Shinya Nakano       Yamaha       +0.742
39    6         Ralf Waldmann      Aprilia       +7.019
40    7       Franco Battaini      Aprilia      +20.889
41    8      Stefano Perugini        Honda      +20.891
42    9         Jason Vincent        Honda      +21.310
43   10          Anthony West    TSR-Honda      +26.816
44   11          Alex Hofmann    TSR-Honda      +26.933
45   12       Sebastian Porto       Yamaha      +27.054
46   13         Tomomi Manako       Yamaha      +27.903
47   14       Masaki Tokudome    TSR-Honda      +33.161
48   15         Jarno Janssen    TSR-Honda      +56.248
49   16       Luca Boscoscuro    TSR-Honda      +56.432
50   17      Johann Stigefelt       Yamaha    +1:07.433
51   18       Julien Allemand    TSR-Honda    +1:16.347
52   19           Fonsi Nieto       Yamaha    +1:25.622
53   20    Lucas Oliver Bulto       Yamaha    +1:25.758
54   21          David Garcia       Yamaha    +1:33.867
55   22         Rudie Markink      Aprilia    +1:40.280
56   23         Arno Visscher      Aprilia    +1:40.635
57   24  Henk Van De Lagemaat        Honda       +1 Lap
58  Ret       Maurice Bolwerk    TSR-Honda   Retirement
59  Ret          Andre Romein        Honda   Retirement
60  Ret         Roberto Rolfo      Aprilia   Retirement
61  Ret     Marcellino Lucchi      Aprilia   Retirement

[62 rows x 4 columns]

9.csv : 203_35.csv(1996 Italian motorcycle Grand Prix)		203_718.csv(1999 Valencian Community motorcycle Grand Prix)
Missing Values(NANs):  {'pos': '0/62', 'rider': '0/62', 'manufacturer': '0/62', 'time/retired': '0/62'}
Columns that match with input_schema:
203_35.csv :  {'pos': 'pos', 'rider': 'rider', 'manufacturer': 'manufacturer'}
203_718.csv :  {'pos': 'pos', 'rider': 'rider', 'manufacturer': 'manufacturer'}
Coverage Score :  1.0 	 Completeness Score :  1.0

    pos                 rider manufacturer time/retired
0     1            Max Biaggi      Aprilia    40:36.299
1     2     Marcellino Lucchi      Aprilia       +6.914
2     3         Ralf Waldmann        Honda      +18.294
3     4        Olivier Jacque        Honda      +18.607
4     5          Jurgen Fuchs        Honda      +31.617
5     6        Tetsuya Harada       Yamaha      +31.649
6     7  Jean-Philippe Ruggia        Honda      +31.683
7     8         Nobuatsu Aoki        Honda      +47.701
8     9          Luis d'Antin        Honda      +51.186
9    10  Cristiano Migliorati        Honda      +51.556
10   11       Massimo Ottobre      Aprilia      +51.563
11   12           Eskil Suter      Aprilia      +51.613
12   13       Luca Boscoscuro      Aprilia      +51.617
13   14          Regis Laconi        Honda      +52.394
14   15   Jurgen vd Goorbergh        Honda      +52.569
15   16       Sebastian Porto      Aprilia    +1:03.619
16   17        Jamie Robinson      Aprilia    +1:06.917
17   18   Olivier Petrucciani      Aprilia    +1:06.945
18   19  Alessandro Antonello      Aprilia    +1:07.099
19   20        Osamu Miyazaki      Aprilia    +1:32.873
20   21         Davide Bulega      Aprilia    +1:32.902
21   22   Yasumasa Hatakeyama        Honda    +1:34.039
22   23       Franco Battaini      Aprilia    +1:34.363
23   24         Sete Gibernau        Honda    +1:34.931
24   25    Christian Boudinot      Aprilia    +1:41.263
25   26          Jose Barresi       Yamaha       +1 Lap
26   27         Roberto Rolfo      Aprilia       +1 Lap
27   28       Cristophe Cogan        Honda       +1 Lap
28  Ret    Gianluigi Scalvini        Honda   Retirement
29  Ret     Roberto Locatelli      Aprilia   Retirement
..  ...                   ...          ...          ...
32    2       Franco Battaini      Aprilia       +5.125
33    3       Loris Capirossi        Honda      +10.224
34    4         Shinya Nakano       Yamaha      +14.848
35    5      Stefano Perugini        Honda      +34.042
36    6       Sebastian Porto       Yamaha      +37.495
37    7         Jason Vincent        Honda      +44.911
38    8       Valentino Rossi      Aprilia    +1:01.110
39    9          Anthony West    TSR-Honda    +1:10.352
40   10          Alex Hofmann    TSR-Honda    +1:18.683
41   11       Luca Boscoscuro    TSR-Honda    +1:20.847
42   12    Lucas Oliver Bulto       Yamaha    +1:23.052
43   13         Roberto Rolfo      Aprilia    +1:24.329
44   14       Masaki Tokudome    TSR-Honda    +1:26.837
45   15           Fonsi Nieto       Yamaha    +1:45.669
46   16          David Garcia       Yamaha    +1:48.926
47   17           Scott Smart      Aprilia    +1:49.730
48   18            Alex Debon        Honda       +1 Lap
49   19         Jarno Janssen    TSR-Honda       +1 Lap
50  Ret         Alvaro Molina        Honda   Retirement
51  Ret       Julien Allemand    TSR-Honda   Retirement
52  Ret        Ismael Bonilla        Honda   Retirement
53  Ret        Daniel Ribalta      Aprilia   Retirement
54  Ret       Maurice Bolwerk        Honda   Retirement
55  Ret         Tomomi Manako       Yamaha   Retirement
56  Ret      Johann Stigefelt       Yamaha   Retirement
57  Ret        Olivier Jacque       Yamaha   Retirement
58  Ret     Jeremy McWilliams      Aprilia   Retirement
59  Ret          David Ortega    TSR-Honda   Retirement
60  Ret          Alfredo Rios      Aprilia   Retirement
61  Ret         Ralf Waldmann      Aprilia   Retirement

[62 rows x 4 columns]

10.csv : 203_35.csv(1996 Italian motorcycle Grand Prix)		204_892.csv(1999 Dutch TT)
Missing Values(NANs):  {'pos': '0/59', 'rider': '0/59', 'manufacturer': '0/59', 'time/retired': '0/59'}
Columns that match with input_schema:
203_35.csv :  {'pos': 'pos', 'rider': 'rider', 'manufacturer': 'manufacturer'}
204_892.csv :  {'pos': 'pos', 'rider': 'rider', 'manufacturer': 'manufacturer'}
Coverage Score :  1.0 	 Completeness Score :  1.0

    pos                 rider manufacturer time/retired
0     1            Max Biaggi      Aprilia    40:36.299
1     2     Marcellino Lucchi      Aprilia       +6.914
2     3         Ralf Waldmann        Honda      +18.294
3     4        Olivier Jacque        Honda      +18.607
4     5          Jurgen Fuchs        Honda      +31.617
5     6        Tetsuya Harada       Yamaha      +31.649
6     7  Jean-Philippe Ruggia        Honda      +31.683
7     8         Nobuatsu Aoki        Honda      +47.701
8     9          Luis d'Antin        Honda      +51.186
9    10  Cristiano Migliorati        Honda      +51.556
10   11       Massimo Ottobre      Aprilia      +51.563
11   12           Eskil Suter      Aprilia      +51.613
12   13       Luca Boscoscuro      Aprilia      +51.617
13   14          Regis Laconi        Honda      +52.394
14   15   Jurgen vd Goorbergh        Honda      +52.569
15   16       Sebastian Porto      Aprilia    +1:03.619
16   17        Jamie Robinson      Aprilia    +1:06.917
17   18   Olivier Petrucciani      Aprilia    +1:06.945
18   19  Alessandro Antonello      Aprilia    +1:07.099
19   20        Osamu Miyazaki      Aprilia    +1:32.873
20   21         Davide Bulega      Aprilia    +1:32.902
21   22   Yasumasa Hatakeyama        Honda    +1:34.039
22   23       Franco Battaini      Aprilia    +1:34.363
23   24         Sete Gibernau        Honda    +1:34.931
24   25    Christian Boudinot      Aprilia    +1:41.263
25   26          Jose Barresi       Yamaha       +1 Lap
26   27         Roberto Rolfo      Aprilia       +1 Lap
27   28       Cristophe Cogan        Honda       +1 Lap
28  Ret    Gianluigi Scalvini        Honda   Retirement
29  Ret     Roberto Locatelli      Aprilia   Retirement
30  Ret     Takeshi Tsujimura        Honda   Retirement
31    1       Loris Capirossi        Honda    38:04.730
32    2       Valentino Rossi      Aprilia       +0.180
33    3     Jeremy McWilliams      Aprilia       +0.534
34    4           Tohru Ukawa        Honda       +0.537
35    5         Shinya Nakano       Yamaha       +0.742
36    6         Ralf Waldmann      Aprilia       +7.019
37    7       Franco Battaini      Aprilia      +20.889
38    8      Stefano Perugini        Honda      +20.891
39    9         Jason Vincent        Honda      +21.310
40   10          Anthony West    TSR-Honda      +26.816
41   11          Alex Hofmann    TSR-Honda      +26.933
42   12       Sebastian Porto       Yamaha      +27.054
43   13         Tomomi Manako       Yamaha      +27.903
44   14       Masaki Tokudome    TSR-Honda      +33.161
45   15         Jarno Janssen    TSR-Honda      +56.248
46   16       Luca Boscoscuro    TSR-Honda      +56.432
47   17      Johann Stigefelt       Yamaha    +1:07.433
48   18       Julien Allemand    TSR-Honda    +1:16.347
49   19           Fonsi Nieto       Yamaha    +1:25.622
50   20    Lucas Oliver Bulto       Yamaha    +1:25.758
51   21          David Garcia       Yamaha    +1:33.867
52   22         Rudie Markink      Aprilia    +1:40.280
53   23         Arno Visscher      Aprilia    +1:40.635
54   24  Henk Van De Lagemaat        Honda       +1 Lap
55  Ret       Maurice Bolwerk    TSR-Honda   Retirement
56  Ret          Andre Romein        Honda   Retirement
57  Ret         Roberto Rolfo      Aprilia   Retirement
58  Ret     Marcellino Lucchi      Aprilia   Retirement

11.csv : 203_718.csv(1999 Valencian Community motorcycle Grand Prix)		204_892.csv(1999 Dutch TT)
Missing Values(NANs):  {'pos': '0/59', 'rider': '0/59', 'manufacturer': '0/59', 'time/retired': '0/59'}
Columns that match with input_schema:
203_718.csv :  {'pos': 'pos', 'rider': 'rider', 'manufacturer': 'manufacturer'}
204_892.csv :  {'pos': 'pos', 'rider': 'rider', 'manufacturer': 'manufacturer'}
Coverage Score :  1.0 	 Completeness Score :  1.0

    pos                 rider manufacturer time/retired
0     1           Tohru Ukawa        Honda    49:50.449
1     2       Franco Battaini      Aprilia       +5.125
2     3       Loris Capirossi        Honda      +10.224
3     4         Shinya Nakano       Yamaha      +14.848
4     5      Stefano Perugini        Honda      +34.042
5     6       Sebastian Porto       Yamaha      +37.495
6     7         Jason Vincent        Honda      +44.911
7     8       Valentino Rossi      Aprilia    +1:01.110
8     9          Anthony West    TSR-Honda    +1:10.352
9    10          Alex Hofmann    TSR-Honda    +1:18.683
10   11       Luca Boscoscuro    TSR-Honda    +1:20.847
11   12    Lucas Oliver Bulto       Yamaha    +1:23.052
12   13         Roberto Rolfo      Aprilia    +1:24.329
13   14       Masaki Tokudome    TSR-Honda    +1:26.837
14   15           Fonsi Nieto       Yamaha    +1:45.669
15   16          David Garcia       Yamaha    +1:48.926
16   17           Scott Smart      Aprilia    +1:49.730
17   18            Alex Debon        Honda       +1 Lap
18   19         Jarno Janssen    TSR-Honda       +1 Lap
19  Ret         Alvaro Molina        Honda   Retirement
20  Ret       Julien Allemand    TSR-Honda   Retirement
21  Ret        Ismael Bonilla        Honda   Retirement
22  Ret        Daniel Ribalta      Aprilia   Retirement
23  Ret       Maurice Bolwerk        Honda   Retirement
24  Ret         Tomomi Manako       Yamaha   Retirement
25  Ret      Johann Stigefelt       Yamaha   Retirement
26  Ret        Olivier Jacque       Yamaha   Retirement
27  Ret     Jeremy McWilliams      Aprilia   Retirement
28  Ret          David Ortega    TSR-Honda   Retirement
29  Ret          Alfredo Rios      Aprilia   Retirement
30  Ret         Ralf Waldmann      Aprilia   Retirement
31    1       Loris Capirossi        Honda    38:04.730
32    2       Valentino Rossi      Aprilia       +0.180
33    3     Jeremy McWilliams      Aprilia       +0.534
34    4           Tohru Ukawa        Honda       +0.537
35    5         Shinya Nakano       Yamaha       +0.742
36    6         Ralf Waldmann      Aprilia       +7.019
37    7       Franco Battaini      Aprilia      +20.889
38    8      Stefano Perugini        Honda      +20.891
39    9         Jason Vincent        Honda      +21.310
40   10          Anthony West    TSR-Honda      +26.816
41   11          Alex Hofmann    TSR-Honda      +26.933
42   12       Sebastian Porto       Yamaha      +27.054
43   13         Tomomi Manako       Yamaha      +27.903
44   14       Masaki Tokudome    TSR-Honda      +33.161
45   15         Jarno Janssen    TSR-Honda      +56.248
46   16       Luca Boscoscuro    TSR-Honda      +56.432
47   17      Johann Stigefelt       Yamaha    +1:07.433
48   18       Julien Allemand    TSR-Honda    +1:16.347
49   19           Fonsi Nieto       Yamaha    +1:25.622
50   20    Lucas Oliver Bulto       Yamaha    +1:25.758
51   21          David Garcia       Yamaha    +1:33.867
52   22         Rudie Markink      Aprilia    +1:40.280
53   23         Arno Visscher      Aprilia    +1:40.635
54   24  Henk Van De Lagemaat        Honda       +1 Lap
55  Ret       Maurice Bolwerk    TSR-Honda   Retirement
56  Ret          Andre Romein        Honda   Retirement
57  Ret         Roberto Rolfo      Aprilia   Retirement
58  Ret     Marcellino Lucchi      Aprilia   Retirement

Rank  1   :  output_1.csv         completeness score : 1.0000000000000000 		number of rows:  124
Rank  2   :  output_2.csv         completeness score : 1.0000000000000000 		number of rows:  96
Rank  3   :  output_3.csv         completeness score : 1.0000000000000000 		number of rows:  93
Rank  4   :  output_4.csv         completeness score : 1.0000000000000000 		number of rows:  93
Rank  5   :  output_5.csv         completeness score : 1.0000000000000000 		number of rows:  90
Rank  6   :  output_6.csv         completeness score : 1.0000000000000000 		number of rows:  65
Rank  7   :  output_7.csv         completeness score : 1.0000000000000000 		number of rows:  65
Rank  8   :  output_8.csv         completeness score : 1.0000000000000000 		number of rows:  62
Rank  9   :  output_9.csv         completeness score : 1.0000000000000000 		number of rows:  62
Rank  10  :  output_10.csv        completeness score : 1.0000000000000000 		number of rows:  59
Rank  11  :  output_11.csv        completeness score : 1.0000000000000000 		number of rows:  59
Rank  12  :  203_244.csv          completeness score : 1.0000000000000000 		number of rows:  34
Rank  13  :  203_35.csv           completeness score : 1.0000000000000000 		number of rows:  31
Rank  14  :  203_718.csv          completeness score : 1.0000000000000000 		number of rows:  31
Rank  15  :  204_892.csv          completeness score : 1.0000000000000000 		number of rows:  28

Ranking Complete!!